### ISSUE TITLE
firefox オプションのメニューの誤訳

### ISSUE THREAD

**Issue by bateleurX** [mozilla-japan/gecko-l10n#119]
https://github.com/mozilla-japan/gecko-l10n/blob/a0377a5e559eb3cad6b994c358f8893c8f2717e7/ja/browser/browser/preferences/preferences.ftl#L849

「読み込みが遅くならないトラッカーのみブロックします。」という訳になっていますが、原語では" Block just the trackers that keep pages from loading quickly."なので、「ページの読み込みを遅くするトラッカーのみブロックします。」といったほうが適切かと思われます。

**Comment by marsf** [comment]
ご指摘ありがとうございます。
修正しました。
