### ISSUE TITLE
Old Firefox Data フォルダー

### ISSUE THREAD

**Issue by dskmori** [mozilla-japan/gecko-l10n#158]
Firefox をリフレッシュすると作成される ([c.f.]) フォルダー名のようですが、この部分はなぜローカライズされていないのでしょうか？
https://github.com/mozilla-japan/gecko-l10n/blob/fafea4a99ac977aa15b1911cbe3ee6ad12538023/ja/toolkit/chrome/mozapps/profile/profileSelection.properties#L53

他のロケールをいくつか (de, fr, it, ko, pt-BR, zh-CN) 確認したところ、ローカライズされていました。

[c.f.]: https://support.mozilla.org/ja/kb/recovering-important-data-from-an-old-profile

**Comment by marsf** [comment]
日本語版の慣習として、アプリケーション外部に出力される文字列は英語のままにしています。ローカライズされている言語は、ローカライズしても問題のない文字コードを使っているか、何も考えていないかのどちらかです。

日本語版の OS で日本語版の Firefox を使っている分には、今はどの OS でも問題にならないと思います。
Unicode でシステム環境が統一されていればいいですが、システムが Unicode でない場合や外国語ロケールの OS で日本語版 Firefox を使う場合、問題になる可能性があります。

なので、不要な問題を避けるために英語のままにしています。
全く問題ないことが分かればローカライズしてもよいです。

**Comment by dskmori** [comment]
抜け漏れでなく、ポリシーがあっての対応だとわかったので問題ないです。特にローカライズしてほしいという要望もありません。
