### ISSUE TITLE
セキュリティリスク警告ページの詳細リンクと詳細ボタンについて

### ISSUE THREAD

**Issue by dskmori** [mozilla-japan/gecko-l10n#159]
Firefox のセキュリティ警告ページに、それぞれ違う機能を持つ **詳細** リンクと **詳細** ボタンがあって、わかりにくいと Twitter に投稿がありました。修正ご検討ください。

https://twitter.com/wraith13/status/1138995764875542528
https://twitter.com/shima_tetsuo/status/1139017051429728256

**Comment by marsf** [comment]
"Learn more..." と "Advanced..." はオプション画面にもあって、こちらは「詳細情報」と「詳細設定」で明確に分けられています。

このセキュリティ警告の場合、どちらも情報表示といえば同じで、はっきり区別しないといけませんね。
案として、
"Learn more" は「エラーの説明」とか「～の説明」という訳語にする。
"Advanced" は「詳細設定」または「詳細」 のまま。
ではいかがでしょうか。
他にも何かあれば提案してください。

**Comment by dskmori** [comment]
コメント遅くなりました。
"Learn more" については、異論ありません。
"Advanced" のほうは、設定を行えるわけではないので、「詳細」のままのほうが無難だと思います。それか「詳細情報」。

**Comment by marsf** [comment]
@hATrayflood 場所はここです。対応お願いします。

https://github.com/mozilla-japan/gecko-l10n/blob/master/ja/browser/chrome/overrides/netError.dtd#L196
https://searchfox.org/mozilla-central/source/browser/base/content/aboutNetError.xhtml#179

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/pull/163/commits/7fa0a7329bc29fa100140410defa0d846c4edc3a これでどうでしょうか @dskmori @marsf

**Comment by marsf** [comment]
良いと思います。

**Comment by dskmori** [comment]
いいと思います。
