### ISSUE TITLE
Firefox Monitor の警告ポップアップ

### ISSUE THREAD

**Issue by dskmori** [mozilla-japan/gecko-l10n#161]
年を表す数字のところに、**年** が抜けていると思います。下図の例では、2019 年のはず。

<img width="380" alt="monitor-alert-on-the-breached-website" src="https://user-images.githubusercontent.com/13865683/63139765-66ecfa00-c01a-11e9-8f89-e40adfd272b7.png">

### 該当箇所
https://github.com/mozilla-japan/gecko-l10n/blob/25438e7183e3001af55ceaa07096bebe417512f2/ja/browser/extensions/fxmonitor/fxmonitor.properties#L24
https://github.com/mozilla-japan/gecko-l10n/blob/25438e7183e3001af55ceaa07096bebe417512f2/ja/browser/extensions/fxmonitor/fxmonitor.properties#L37

**Comment by marsf** [comment]
@hATrayflood 修正お願いします。

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/pull/163/commits/fdce6b32a9d4a4b43f06f70db807e1d1f03476a6 修正しました @dskmori @marsf

**Comment by marsf** [comment]
OK です。ありがとうございます。
