### ISSUE TITLE
/messenger/openpgp まわりの L10n

### ISSUE THREAD

**Issue by marsf** [mozilla-japan/gecko-l10n#215]
Thunderbird 78.1.0 で Engmail が統合され、78.2.0 で有効化される予定になっている。
[Thunderbird OpenPGP strings landed](https://groups.google.com/forum/#!topic/mozilla.dev.l10n/RznnPkiSng4)

L10n リソース:
https://github.com/mozilla-japan/gecko-l10n/tree/master/ja/mail/messenger/openpgp

この部分は、Enigmail アドオンをローカライズしている @Cai0407 さんに依頼することにした。(Slack で快諾済み)

**Comment by marsf** [comment]
cai0407 wrote:
> やります。ざっと確認しましたが、だいたいは Enigmail から流用でいけそうですhttps://bugzilla.mozilla.org/show_bug.cgi?id=1638822
> もともと Enigmail の英語リソースをほぼそのまま持ってきたのが原型であまり手を入れてないようですgpg 1.x から 2.x に変わるときに鍵の信頼性に関するローカライズが変わったのを Enigmail の日本語ロケールではそのままにしているんですが、これどうしよう？
> リソースだと openpgp.ftl 547 行目あたり定義としては、
> 
>     ultimate: 自分自身の鍵
>     full: 自分が直接署名した鍵 (キーサインパーティーなどで持ち主を確認しているもの) あるいは Web of Trust でそれと同等と判定された鍵 (信頼性が full の鍵 3 つから署名されている)
>     marginal: Web of Trust でそれなりの信頼性と判定された鍵 (信頼性が full の鍵 1 つあるいは 2 つから署名されている)
> 
> gpg2 の日本語訳だと marginal と ultimate がラフすぎる、full の意味がちゃんと訳出されていない、というのが個人的な意見
> 
> gpg2 ja.po
> marginal: まぁまぁ
> full: 充分
> ultimate: 究極
> 
> Enigmail ja
> marginal: ある程度
> full: 完全
> ultimate: 絶対的

**Comment by marsf** [comment]
基本的には、Enigmail のをそのまま継承していただければと思います。
以下は単語の意味だけで見た場合の提案です。

untrusted: 信用しない
marginal: 信用できる
　類語は borderline、ギリギリOK
full: 完全に信用
　full = 条件を「完全に満たす」
ultimate: 根本的に信用
　類語は fundamental

**Comment by marsf** [comment]
full: 十分に信用
ultimate: 完全に信用

でもよいかもしれません。

**Comment by Cai0407** [comment]
手元での作業が一通り終わりました。
pull request あげるまでにいくつか。

1. personal key
`e2e-intro-description-more = Select your personal key to enable the use of OpenPGP, or your personal certificate to enable the use of S/MIME. For a personal key or certificate you own the corresponding secret key.`
`e2e-intro-description-more = OpenPGP を有効化するためのあなたの個人鍵か、S/MIME を有効化するためのあなたの個人証明書を選択してください。どちらの場合にも、対応する秘密鍵を保有している必要があります。`
OpenPGP の秘密鍵/プライベート鍵etc.を指して "personal key"、それと対比する形で S/MIME の "personal certificate" という表現があります。とりあえず「個人鍵」「個人証明書」と訳を当てました。Thunderbird 本体の証明書マネージャーでは秘密鍵を所有している証明書について「あなたの証明書」としていますが、これに合わせて「あなたの鍵」とすると何か落ち着かない。

2. Import/Export
Import/Export については、ja.filters に従いました。GnuPG では OS 問わず単一リソースでインポート/エクスポートですが、Mozilla としての OpenPGP 別実装ということで gpg にすべて従う必要もないだろうと判断しました。

3. 鍵の信用度
`key-trust-untrusted = 信用していない`
`key-trust-marginal = 最低限の信用`
`key-trust-full = 完全な信用`
`key-trust-ultimate = 絶対的な信用`
信用度についてはこのようにしました。full: 十分、ultimate: 完全もいいと思ったのですが、既存の Enigmail ユーザーにとっては「十分」が full (Enigmail) なのか ultimate (Thunderbird) なのか混乱することになりそうなので、marginal をより弱い表現に修正するに留めました。

**Comment by marsf** [comment]
@Cai0407 
> 1. personal key
> Thunderbird 本体の証明書マネージャーでは秘密鍵を所有している証明書について「あなたの証明書」としていますが

Thunderbird でも [personal certificate](https://transvision.mozfr.org/?recherche=personal+certificate&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings) の訳は「個人証明書」です。証明書マネージャーの「[あなたの証明書](https://transvision.mozfr.org/?recherche=%E3%81%82%E3%81%AA%E3%81%9F%E3%81%AE%E8%A8%BC%E6%98%8E%E6%9B%B8&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings)」 は your certificates の訳です。

> 2. Import/Export
> Import/Export については、ja.filters に従いました。GnuPG では OS 問わず単一リソースでインポート/エクスポートですが

OS ごとに厳密に用語を区別しているクロスプラットフォームのソフトウェアは、日本語ネイティブのメーカーのものを除いて、Mozilla 以外にはほとんど無いんじゃないでしょうか。

**Comment by Cai0407** [comment]
#216 で merge request 上げました。

> @Cai0407
> 
> > 1. personal key
> >    Thunderbird 本体の証明書マネージャーでは秘密鍵を所有している証明書について「あなたの証明書」としていますが
> 
> Thunderbird でも [personal certificate](https://transvision.mozfr.org/?recherche=personal+certificate&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings) の訳は「個人証明書」です。証明書マネージャーの「[あなたの証明書](https://transvision.mozfr.org/?recherche=%E3%81%82%E3%81%AA%E3%81%9F%E3%81%AE%E8%A8%BC%E6%98%8E%E6%9B%B8&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings)」 は your certificates の訳です。

了解です。「個人鍵」のままでいきます。

> > 2. Import/Export
> >    Import/Export については、ja.filters に従いました。GnuPG では OS 問わず単一リソースでインポート/エクスポートですが
> 
> OS ごとに厳密に用語を区別しているクロスプラットフォームのソフトウェアは、日本語ネイティブのメーカーのものを除いて、Mozilla 以外にはほとんど無いんじゃないでしょうか。

たしかに。
整理・統一についても ja.filters にお任せします。

**Comment by marsf** [comment]
@Cai0407 ありがとうございました。
コミットログのユーザー名はどうしましょうか。 "Kosuke Kaizuka" でいいですか？

**Comment by Cai0407** [comment]
> @Cai0407 ありがとうございました。
> コミットログのユーザー名はどうしましょうか。 "Kosuke Kaizuka" でいいですか？

OK です。

**Comment by marsf** [comment]
本家にコミットしたのでこの issue を閉じます。
