### ISSUE TITLE
メッセージ作成ウインドウの暗号化関連

### ISSUE THREAD

**Issue by Cai0407** [mozilla-japan/gecko-l10n#223]
/ja/mail/chrome/messenger-smime/msgCompSMIMEOverlay.dtd
```
<!ENTITY menu_securityDoNotEncrypt.label	"暗号化しない">
<!ENTITY menu_securityDoNotEncrypt.accesskey	"o">

<!ENTITY menu_securityEncryptRequire2.label	"暗号が必要">
<!ENTITY menu_securityEncryptRequire.accesskey	"E">
```
メッセージ作成ウインドウのオプションの中に出てくるものです。
メッセージを暗号化するか否かの選択肢なのですが、「暗号化しない」と対にするのは「暗号化する」あたりのほうが適切と思われます。
原文は "Do Not Encrypt" と "Require Encryption" なので直訳ではたしかに「暗号が必要」なのですが、利用状況を考えると意訳したほうがよいのでは？

```
<!ENTITY menu_securityTech.label		"暗号技術">
<!ENTITY menu_securityTech.accesskey		"T">
```
原文は "Encryption Technology"
アカウント設定→エンドツーエンド暗号化の項では「暗号化技術」としています。こちらで統一すべき。

**Comment by marsf** [comment]
> メッセージ作成ウインドウのオプションの中に出てくるものです。
メッセージを暗号化するか否かの選択肢なのですが、「暗号化しない」と対にするのは「暗号化する」あたりのほうが適切と思われます。

これは、[「メッセージを暗号化する」から変更されたものです。](https://hg.mozilla.org/l10n-central/ja/diff/42604137ba0d7eb38fbe9ddf8a2ed1287b0606be/mail/chrome/messenger-smime/msgCompSMIMEOverlay.dtd)
```
<!ENTITY menu_securityEncryptRequire.label	"Encrypt This Message">
<!ENTITY menu_securityEncryptRequire2.label	"Require Encryption">
```
[Bug 1603813 - Unify general encryption options in composer window](https://bugzilla.mozilla.org/show_bug.cgi?id=1603813#c1)
あとで第三の選択肢が追加される予定なので、そのままのほうがよいです。


> 原文は "Encryption Technology"
> アカウント設定→エンドツーエンド暗号化の項では「暗号化技術」としています。こちらで統一すべき。

こちらはその通りですね。統一したほうがよいです。
https://transvision.mozfr.org/?recherche=Encryption+Technology&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings_entities

**Comment by Cai0407** [comment]
> > メッセージ作成ウインドウのオプションの中に出てくるものです。
> > メッセージを暗号化するか否かの選択肢なのですが、「暗号化しない」と対にするのは「暗号化する」あたりのほうが適切と思われます。
> 
> これは、[「メッセージを暗号化する」から変更されたものです。](https://hg.mozilla.org/l10n-central/ja/diff/42604137ba0d7eb38fbe9ddf8a2ed1287b0606be/mail/chrome/messenger-smime/msgCompSMIMEOverlay.dtd)
> 
> ```
> <!ENTITY menu_securityEncryptRequire.label	"Encrypt This Message">
> <!ENTITY menu_securityEncryptRequire2.label	"Require Encryption">
> ```
> 
> [Bug 1603813 - Unify general encryption options in composer window](https://bugzilla.mozilla.org/show_bug.cgi?id=1603813#c1)
> あとで第三の選択肢が追加される予定なので、そのままのほうがよいです。

なるほど。であれば、コメントアウトされてる
```
<!ENTITY menu_securityEncryptOptional.label	"暗号を許可">
```
も含めて、「暗号化が必要」「暗号化を許可」のように "encryption" には「暗号」ではなく「暗号化」をあてるべきです。
メッセージに施すのは「暗号化」です。「暗号」とすると "cryptography" の意に取られるかと。

**Comment by marsf** [comment]
> 「暗号化が必要」「暗号化を許可」のように "encryption" には「暗号」ではなく「暗号化」をあてるべきです。

はい、そのように修正してください。

**Comment by Cai0407** [comment]
pull request #224
