### ISSUE TITLE
ブラウジングライブラリーの「復元」の日付表示

### ISSUE THREAD

**Issue by Cai0407** [mozilla-japan/gecko-l10n#235]
某掲示板より
84 以降で、ブラウジングライブラリー → インポートとバックアップ → 復元 で表示されるバックアップ一覧の日付表示が文字化けしています。
78 ESR および 83 は問題なし。

84.0 candidate 20201207203640 NG
![84.0b8](https://user-images.githubusercontent.com/2016274/101462316-7155a480-397f-11eb-8b29-741a12e1371e.png)
83.0 OK
![83.0](https://user-images.githubusercontent.com/2016274/101462433-8fbba000-397f-11eb-8b3a-5dd090a164a3.png)

/ja/browser/chrome/browser/places/ 以下に該当しそうなものは見当たりません。
本体側で日付処理に関して何か変更ありましたっけ？

**Comment by marsf** [comment]
メニュー項目を生成しているソースはこのあたり。
https://searchfox.org/mozilla-central/source/browser/components/places/content/places.js#531

https://github.com/mozilla-japan/gecko-l10n/blob/master/ja/browser/chrome/browser/places/places.properties#L52
detailsPane.itemsCountLabel	=項目の数: #1 個

特に変更されていないはずですが。

**Comment by marsf** [comment]
日付生成部分
https://searchfox.org/mozilla-central/source/toolkit/components/places/PlacesBackups.jsm#230

[Bug 1649615 - PlacesBackups.jsm imports OS.File during startup](https://bugzilla.mozilla.org/show_bug.cgi?id=1649615) の影響かな？

**Comment by Cai0407** [comment]
84.0 リリース版 (20201211215739)、85.0 beta 3 (20201217185930)、86.0a1 (20201219214357) ですが、いずれも再現しなくなりました。
78.6.0 ESR (20201207224150) も問題なし。
何だったんでしょう？

**Comment by marsf** [comment]
詳しいことは分かりませんが、先の Bug 1649615 で修正されたのではないかと思います。

**Comment by Cai0407** [comment]
はい。クローズで。
