### ISSUE TITLE
Android Firefox の Sync 設定の「開いているタブ」

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/gecko-l10n#236]
取り急ぎ issue にメモを残します (最近リソースファイル何処で修正するかついて行けてないですゴメンナサイ):

こちらの「タブを開く」は多分よくある Open Tab の誤訳で「開いているタブ」です:

![image](https://user-images.githubusercontent.com/188166/103059664-18297a00-45e9-11eb-9ee6-e062fce7b1ac.png)

**Comment by marsf** [comment]
https://github.com/mozilla-mobile/fenix/blob/07748f69b75144e8e247b742f66a756f999cb299/app/src/main/res/xml/account_settings_preferences.xml#L48

dskmori さんが修正してくれました。おそらく、86.0 に反映されます。
https://pontoon.mozilla.org/ja/android-l10n/all-resources/?string=212508
