### ISSUE TITLE
タブメニューの「コンテナーを開き直す」

### ISSUE THREAD

**Issue by vyv03354** [mozilla-japan/gecko-l10n#240]
選択したタブを指定したコンテナー内で開き直す機能であり、開き直しているのはタブであってコンテナーではないので、「コンテナーで開き直す」のほうが適切だと思います。

**Comment by marsf** [comment]
https://github.com/mozilla-japan/gecko-l10n/blob/master/ja/browser/browser/tabContextMenu.ftl#L45

**Comment by marsf** [comment]
@vyv03354  ありがとうございます。
修正は 86.0 に反映されます。

https://hg.mozilla.org/l10n-central/ja/rev/f686d51ba8bc79cc9fc90de68e48c6061605ab6b
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/0de19509536d25f15c1f3198c7c2d9b165a19ba4
