### ISSUE TITLE
MathML 関係の訳語

### ISSUE THREAD

**Issue by scivola** [mozilla-japan/gecko-l10n#26]
https://github.com/mozilla-japan/gecko-l10n/commit/4498d2a4f8dd5027ed2541622d02eb3830abd100

mathmltable って「数表」なんでしょうか。数とは限らないので「表」か「テーブル」でいいんじゃないでしょうか。
mtable 要素に関係するのでしたら，そもそも表ですらなくて，行列の中身を記述するなど，表のように縦横に何かを並べるものにも使います。

base はどういうところに出てくるのか分かりませんが，何かの本体（添字をはべらせたり根号に入れたりするもの）を指しているわけではありませんか。

overscript, underscript は定着した訳語が無いので悩ましいですね。

madruwb（مضروب）はアラビア語の数学表記で階乗を表すためにラームという文字（ل U+0644）に似た線で囲むもののようですね。発音の仮名表記は「マドルーブ」だと思います。訳語は「アラビア語の階乗」とかになるんでしょうか。
http://www.w3.org/TR/arabic-math/arabic.xhtml#N106E1

**Comment by marsf** [comment]
フィードバックありがとうございます。
このファイルは MathML のアクセシビリティサポートのために、MathML 関連タグの Accessibility Roles 等を表すもののようです。
https://wiki.mozilla.org/Accessibility/MathML
https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/a11y
https://developer.mozilla.org/en-US/docs/Web/MathML/Element
http://hg.mozilla.org/releases/mozilla-aurora/rev/95a508b38259

上記の wiki ページを見てみると、おっしゃる通り、base はいわゆる本体になる数字のようです。「基線」ではありませんね。何かよい訳語はあるでしょうか？

overscript / underscript / presubscript / presuperscript については、base の後の上下に付く添え字を通常の「上付き・下付き」として、「真上付き・真下付き」「前上付き・前下付き」にしてしまおうと思います。
いかがでしょうか？

madruwb もまだ訳語は無いようです。Google 翻訳にかけてみると「マッドゥルーブ」のように聞こえます。
https://translate.google.co.jp/#en/ar/factorial
「マドルーブ」「マドゥルーブ」ではまだ通じないのが悩ましいです。「アラビア階乗」ではいかがでしょうか。

**Comment by scivola** [comment]
アクセシビリティサポートってことは，MathML で書かれた数式を読み上げたりするときに使われるってことでしょうか。

base ですが，和志武功久さんという MathML 仕様書の部分訳を発表されている方のご提案では「基底」のようです。下記のページは和志武さんの対訳表です。
http://washitake.com/MathML/ver2/appendixl.html
「本体」もありかなと漠然と思っていたのですが，本体より「基底」のほうがそれらしい気もします。受け取り手が分かるかどうかは別ですが。

overscript，underscript も，定着した訳語が無い以上，何を持ってきても馴染みは無いわけで，新語を造るなら頑張って普及させるしかないですよね。
和志武さんは「上ルビ／下ルビ」とされています。
「上ルビ／下ルビ」も「真上付き／真下付き」もナルホドとは思います。
私は，MathML 用語としては，もう日本語の造語を諦めて「オーバースクリプト」「アンダースクリプト」という外来語で流通させるのはどうかな，とも思っています。

私はアラビア語を知っているわけではないのですが，下記のページの発音表記（文字の上下に記号がついた表記）を見ると，madruwb の d の部分は重子音ではないので，「マ」の次に「ッ」は付けないほうがいいと思います。
http://www.almaany.com/en/dict/ar-en/%D9%85%D8%B6%D8%B1%D9%88%D8%A8/
Google 翻訳の発音を私も聞いてみました。「マッド…」のようにも聞こえるのは「マ」が強いせいでしょうかね。
母音のつかない d の部分は「ド」でなく「ドゥ」の表記もありですね。よって仮名表記は「マドルーブ」か「マドゥルーブ」になると思います。
何にしても MathML に関係なく日本でマドゥルーブが話題になることはほとんど無いんじゃないでしょうか。
Gecko もマドゥルーブは実装していないんでしたよね。

「アラビア階乗」だと，普通の階乗ではないアラビア数学特有の階乗があるかのように聞こえませんか。

**Comment by marsf** [comment]
> アクセシビリティサポートってことは，MathML で書かれた数式を読み上げたりするときに使われるってことでしょうか。

はい、そうです。

以下のようにしました。

mathmltable　= 表
base = 基底
overscript = 真上付き
presubscript = 前下付き
presuperscript = 前上付き
underscript =真下付き
notation-madruwb = アラビア語の階乗
notation-madruwbAbbr = 階乗

まだ open にしておきます。何かあればコメントください。
