### ISSUE TITLE
Firefox about:addonsページの翻訳手直しのご提案

### ISSUE THREAD

**Issue by githubonlydigdig** [mozilla-japan/gecko-l10n#263]
Firefox(ESRでない通常版)のUI翻訳につきまして､
about:addonsページの一番上の歯車の中に以下の文言があります(Firefox90にて)
アドオンを自動的に更新
すべてのアドオンを自動的に更新

その英語原文は
Update Add-ons Autmatically
Reset All Add-ons to Update Autmatically
![aboutAddon_90 0 2](https://user-images.githubusercontent.com/78333856/128646857-99084533-741f-4695-afac-ee799934ecd8.jpg)

下段｢すべてのアドオンを自動的に更新｣は
上段との違いが直感できないです｡
どちらもアドオン1つ1つの自動更新設定をその場で一括して上書きするコマンドに読めてしまいます｡

ついては､下段の方は若干の翻訳手直しを提案いたします｡｢**リセット**｣を追加が趣旨です｡
代案1
すべてのアドオンをリセットして自動的に更新
代案2
すべてのアドオンの自動更新設定をリセット

**私はこのリポジトリのファイルにはコミットやプルリクエストは入れていませんので､
識者の方､ご検討とリアクションをどうぞお願いいたします**｡

なお､FirefoxESR78では英語原文自体が下段だけ相違しています｡
Update Add-ons Autmatically
Reset All Add-ons to Update **Manually**
これはバグでしょうか?､ESR独自仕様でしょうか?
![aboutAddon_78 12 0esr](https://user-images.githubusercontent.com/78333856/128646866-ebe18136-8468-4c2a-93ca-829173ce664f.jpg)

**Comment by marsf** [comment]
ご提案ありがとうございます。
このメニューは確かに分かりづらい（UX 最悪）です。

まず機能を確認しておきます。
この 2 行は連動していて、
上段の "Update Add-ons Autmatically" にチェックを入れると、
下段が "Reset All Add-ons to Update **Autmatically**" になり、
チェックを外すと "Reset All Add-ons to Update **Manually**" になります。

上段は、自動更新の有効/無効を切り替える**スイッチ**になっています。
下段は、この有効/無効のグローバル設定をすべてのアドオンに適用する**コマンド**です。（各アドオンのオプションで、[自動更新の許可] を [既定] に設定します）

ローカライズのソースのコメントにも以下のように書かれています。
https://hg.mozilla.org/l10n-central/ja/file/default/toolkit/toolkit/about/aboutAddons.ftl#l200
```
# This menu item is a checkbox that toggles the default global behavior for
# add-on update checking.

addon-updates-update-addons-automatically = アドオンを自動的に更新
    .accesskey = A

## Specific add-ons can have custom update checking behaviors ("Manually",
## "Automatically", "Use default global behavior"). These menu items reset the
## update checking behavior for all add-ons to the default global behavior
## (which itself is either "Automatically" or "Manually", controlled by the
## extensions-updates-update-addons-automatically.label menu item).

addon-updates-reset-updates-to-automatic = すべてのアドオンを自動的に更新
    .accesskey = R
addon-updates-reset-updates-to-manual = すべてのアドオンを手動で更新
    .accesskey = R
```

**Comment by marsf** [comment]
これを踏まえると、automatic と manual の両方を変更する必要があります。
```
addon-updates-reset-updates-to-automatic = すべてのアドオンを自動的に更新
addon-updates-reset-updates-to-manual = すべてのアドオンを手動で更新
```

> ついては､下段の方は若干の翻訳手直しを提案いたします｡｢リセット｣を追加が趣旨です｡
> 代案1: すべてのアドオンをリセットして自動的に更新
> 代案2: すべてのアドオンの自動更新設定をリセット

上段のチェック状態によって文が自動と手動で切り替わるため、その動作は「リセット」とは違うような気がします。ご意見ください。

**Comment by githubonlydigdig** [comment]
ご検討いただきありがとうございます｡
仕様を理解しました｡
原文がResetなので悩ましい翻訳ですね｡
原文に極力忠実で日本語としても仕様としても察しがつく感じ､悩ましいですね｡

代案3
すべてのアドオンの更新設定をリセットして､自動更新に
すべてのアドオンの更新設定をリセットして､手動更新に

私のセンスの問題もありますので､後のご判断はお任せ申し上げます｡

**Comment by EarlgreyPicard** [comment]
無難なところでこんなのではどうでしょう。

すべてのアドオンを自動的に更新するように設定
すべてのアドオンを手動で更新するように設定

**Comment by githubonlydigdig** [comment]
こんな感じでしょうか｡
Resetの語感が滲んで､現行より私は良いと思います｡

レ アドオンを自動的に更新
__すべてのアドオンを自動的に更新するように設定
.
__アドオンを自動的に更新
__すべてのアドオンを手動で更新するように設定

**Comment by marsf** [comment]
後出しですみません。先に書いたこの動作の補足です。

> 下段は、この有効/無効のグローバル設定をすべてのアドオンに適用するコマンドです。（各アドオンのオプションで、[自動更新の許可] を [既定] に設定します）

各アドオンの自動更新設定はオン・オフの 2 モードではなく、既定・オン・オフの 3 モードです。
歯車メニューから下段の "Reset All Add-ons to Update ..." をクリックすると、全アドオンの自動更新の許可を [オン] / [オフ] ではなく、[既定] に設定します。
下段のメニューはすべてのアドオンを [既定] に変更するものなので、自動だろうが手動だろうが中身の動作は同じです。
つまり、メニュー下段の項目は [既定] にリセットする、とも言えます。

これは、ユーザーの意図しない動作に設定される可能性があります。

仮に、あるアドオン (A) を「自動更新しない」ように個別設定 （[自動更新の許可] を [オフ] に設定）していた場合、
上段のメニューで「アドオンを自動的に更新」のチェックを外し、
他のアドオンも自動更新しないように、「すべてのアドオンを手動で更新」をクリックしてしまうと、(A) のアドオンの更新設定は「既定」に変更されます。
ここまでは使用上問題ありませんが、
他のアドオンを再び自動更新させたいと思って上段のメニューにチェックを入れてすべての自動更新を ON にすると、アドオン (A) もそれに従って自動更新されるように変更されてしまいます。
（知らないうちに個別設定が削除されるということです。）

**Comment by githubonlydigdig** [comment]
下段の英語原文が仮にこんな感じであった方が単純で良いですね｡
Reset All Add-ons-update-settings to "default"

でも現行は
Reset All Add-ons to Update Automatically
Reset All Add-ons to Update Manually

"default"を意図して"Reset"が使われていると感じます｡

でも翻訳においては､意訳はほどほどに､と言われますので悩ましいところです｡
では､原文に極力忠実で日本語としても仕様としても察しがつく手直しができないか?
というご提案でした｡

後のご判断はお任せ申し上げます｡

**Comment by EarlgreyPicard** [comment]
marsf さん
> つまり、メニュー下段の項目は [既定] にリセットする、とも言えます。

了解です。
その動作に関しては承知しておりましたが、

> 上段のチェック状態によって文が自動と手動で切り替わるため、その動作は「リセット」とは違うような気がします。

とのことでしたので、リセットを避けたテキスト考えてみました。

それでは、
```
addon-updates-reset-updates-to-automatic = すべてのアドオンを自動的に更新するようにリセット
addon-updates-reset-updates-to-manual = すべてのアドオンを手動で更新するようにリセット
```
ではどうでしょう。
他の項目のスタイルに合わせて体言止めにし、なるべく大きく変えないようにしてみました。
元のテキストから大きく変えてしまうと、ユーザーに翻訳の修正ではなく機能自体の変更と誤認させてしまう恐れがあるかとおもいますので、変えるならこの程度かなと思います。

**Comment by marsf** [comment]
Mozilla 製品のローカライズについて、原文に忠実にしなければならないというルールはありません。
[L10n ガイドライン](https://github.com/mozilla-japan/translation/wiki/L10N-Guideline) からピックアップすると、今回の場合は以下のガイドラインが適用できます。
> - 原文の表現が不適切あるいは不明瞭なところは独自表現に変えることも厭わない。
> - メニュー項目
>   - OS の慣用表現に従う他は簡潔な体言を基本とする

不適切なのは、同じ動作なのに「自動」「手動」と表現が変わり、かつ、別の項目の状態によってユーザーの意図しない設定に変更されてしまうことです。
このような UI の設計ミスに従う必要はありません。
本来であれば Bugzilla で指摘してアドオンの更新まわりの UI を刷新してもらうのが正しいやり方ですが、Proton になっても手付かずのままなので、すぐに改善されることは期待できません。

@githubonlydigdig さんの案を採用して、以下のようにしたいと思いますが、いかがでしょうか。
> 下段の英語原文が仮にこんな感じであった方が単純で良いですね｡
> Reset All Add-ons-update-settings to "default"

```
addon-updates-reset-updates-to-automatic = すべてのアドオンの更新設定を既定にリセット
addon-updates-reset-updates-to-manual = すべてのアドオンの更新設定を既定にリセット
```

これを変更すると、「 [既定] ってどこの設定だ？」という疑問が湧いてくるので、以下の各アドオンの詳細パネルの設定も変更したいです。
```
addon-detail-updates-label = 自動更新の許可 → このアドオンの自動更新
addon-detail-updates-radio-default = 既定
addon-detail-updates-radio-on = オン → 許可する
addon-detail-updates-radio-off = オフ → 許可しない
addon-detail-update-check-label = 更新の確認 → 今すぐ確認
```

**Comment by marsf** [comment]
@EarlgreyPicard 
> 元のテキストから大きく変えてしまうと、ユーザーに翻訳の修正ではなく機能自体の変更と誤認させてしまう恐れがあるかとおもいますので、変えるならこの程度かなと思います。

上に書いた通り、不適切なものをそのままにしておくほうが問題が大きいと思います。実際の機能に対して、より適切なローカライズを行った、と思っていただければよいです。

**Comment by githubonlydigdig** [comment]
@marsf 様の案､分かりやすいと思います｡
ガイドライン､柔軟ですね｡

上段は､こんな感じはいかがでしょうか?
追いすぎであれば却下ください｡

上段 アドオンを自動的に更新
↓
上段 アドオンの更新設定(既定)､チェック有は自動更新(A)
下段 すべてのアドオンの更新設定を既定にリセット(R)

**Comment by EarlgreyPicard** [comment]
> このような UI の設計ミスに従う必要はありません。
> 本来であれば Bugzilla で指摘してアドオンの更新まわりの UI を刷新してもらうのが正しいやり方ですが、Proton になっても手付かずのままなので、すぐに改善されることは期待できません。

>これを変更すると、「 [既定] ってどこの設定だ？」という疑問が湧いてくるので、以下の各アドオンの詳細パネルの設定も変更したいです。

なるほど、範囲も拡大して思い切った変更になりそうですね。
良くなる方向であれば異存ありません。お任せしたいと思います。

**Comment by githubonlydigdig** [comment]
現時点の手直し案を画像にしてみました｡
現行画面より少しは直感的になるか､現行仕様を知らない以前の私のような人にも感想をもらいたい所ですね｡
もしそんなお手間あれば､画像お使いください｡
![無題](https://user-images.githubusercontent.com/78333856/129279392-20427ef1-5d7e-4696-a749-f55272e036d2.png)

**Comment by marsf** [comment]
@githubonlydigdig 
> 上段 アドオンを自動的に更新
> ↓
> 上段 アドオンの更新設定(既定)､チェック有は自動更新(A)
> 下段 すべてのアドオンの更新設定を既定にリセット(R)

メニュー項目として説明的すぎます。上段が「既定」動作のオン・オフであることは分かるようにしたいので、上段を以下のようにします。
```
addon-updates-update-addons-automatically = アドオンを自動的に更新 (既定の設定)
```

もはや「既定」の意味が損なわれてますが気にしないことにします。
これで各項目の関係と動作がユーザーに理解できるでしょうか。

**Comment by githubonlydigdig** [comment]
レ が外れた状態で見ると､手動である､又は自動更新を許可しない状態である
という事が現行より直感しにくくなるのではと心配します｡

レ アドオンを自動的に更新 (既定の設定)(A)
__すべてのアドオンの更新設定を既定にリセット(R)
.
__アドオンを自動的に更新 (既定の設定)(A)
__すべてのアドオンの更新設定を既定にリセット(R)

**Comment by githubonlydigdig** [comment]
上段の別案がひらめきました｡
これも説明的すぎますでしょうか?

レ 既定の更新設定(チェック有は自動)(A)
__すべてのアドオンの更新設定を既定にリセット(R)
.
__既定の更新設定(チェック有は自動)(A)
__すべてのアドオンの更新設定を既定にリセット(R)

**Comment by marsf** [comment]
@githubonlydigdig 
> レ が外れた状態で見ると､手動である､又は自動更新を許可しない状態である
> という事が現行より直感しにくくなるのではと心配します｡

内部の動作から言えば、上段のチェックなしは「自動更新を許可しない状態」ではありません。各アドオンの自動更新の設定で、既定・許可する・許可しないのうちの「既定」を自動更新にするか、手動更新にするか、の設定です。
初期状態ではチェックありです。

通常のチェックボックスの設定扱いで、もう一つの案も考えていました。
`addon-updates-update-addons-automatically = アドオンを既定で自動更新する`

ご提案について、

> レ 既定の更新設定(チェック有は自動)(A)

説明としては間違っていませんが、こういった表現はどこにも使っていないはずです (ルールではなく、使っていないのです)。
説明的すぎると書いたのは、製品内の表現として「〜の設定」は、クリックすると別の設定ウィンドウやポップアップが開くものに使われていることと、動作の主目的 (〜は自動) を括弧書きにすることはあり得ないからです。
正しい UI であれば、このような説明をせずにチェックの有無で意味が分からなければなりません。もしくは、設定の説明部分に書かれるべき内容です。

**Comment by githubonlydigdig** [comment]
意見具申が出過ぎたようなので、こへんで黙ります。

**Comment by marsf** [comment]
その提案や視点はとてもありがたいです。お気軽にコメントください。

**Comment by marsf** [comment]
特にコメントが無ければ、明日コミットしたいと思います。
上段は直感しにくいとのことでしたので、もう一つの案で。
```
addon-updates-update-addons-automatically = アドオンを自動的に更新
　→ アドオンを既定で自動更新する
addon-updates-reset-updates-to-automatic = すべてのアドオンを自動で更新
　→ すべてのアドオンの更新設定を既定にリセット
addon-updates-reset-updates-to-manual = すべてのアドオンを手動で更新
　→ すべてのアドオンの更新設定を既定にリセット
```

```
addon-detail-updates-label = 自動更新の許可
　→ このアドオンの自動更新
addon-detail-updates-radio-default = 既定
addon-detail-updates-radio-on = オン
　→ 許可する
addon-detail-updates-radio-off = オフ
　→ 許可しない
addon-detail-update-check-label = 更新の確認
　→ 今すぐ確認
```
今週中であれば、次の 91.x ESR にも反映されます。

**Comment by githubonlydigdig** [comment]
@marsf 様､
私は異存ございません｡
難しいUXの翻訳手直し提案､藪蛇になってしまったかも､と少し心痛次第でした｡
でも､建設的な議論ができ､私にとっては有意義な機会になりました｡
お忙しいところ粘り強く相対いただき御礼申し上げます｡
今後もFirefoxの発展､そしてローカライズ皆様のご活躍を祈念しております｡

**Comment by marsf** [comment]
https://hg.mozilla.org/l10n-central/ja/rev/26a1faf130f150f398e0903cbf79836a071792b0
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/d34b0569277d11a0f6453fe059d0ee71f2280d78

**Comment by marsf** [comment]
ご意見、ご提案等、ありがとうございました。
