### ISSUE TITLE
区域 ID -> ディストリビューション ID (about:support ページ )

### ISSUE THREAD

**Issue by dskmori** [mozilla-japan/gecko-l10n#264]
https://github.com/mozilla-japan/gecko-l10n/blob/b891411a23b0529a630037426a5a14e89f3ee330/ja/toolkit/toolkit/about/aboutSupport.ftl#L40

Linux ディストリビューション名が表示されるフィールドのようなので、_区域 ID_ ではなく、カタカナ語を使って _ディストリビューション ID_ とするのはいかがでしょうか。

c.f. https://support.mozilla.org/ja/kb/use-troubleshooting-information-page-fix-firefox#w_apurikeshiyonji-ben-qing-bao

**Comment by marsf** [comment]
ご指摘ありがとうございます。
「ディストリビューション ID」にしました。

**Comment by marsf** [comment]
https://hg.mozilla.org/l10n-central/ja/rev/ebcb22f3e8a56c17e9cc670c31975e30b31eaf68
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/ffaf46e44435527299f22e707533511d71a785c9
