### ISSUE TITLE
Firefox ESRダウンロードページで32bit版と64bit版の取り違え訳

### ISSUE THREAD

**Issue by Guest126** [mozilla-japan/gecko-l10n#265]
https://www.mozilla.org/ja/firefox/enterprise/

![Screenshot 2021-08-21 at 22-10-14 業務用としての ESR とRapid Release の Firefox](https://user-images.githubusercontent.com/63546117/130322947-200e61c3-023f-4007-b46a-2897519b654a.png)

英語では右端が"Windows 32-bit"のところ日本語では「Windows 64 ビット」と誤訳されているために、Windows 64 ビットのダウンロードリンクが2つ表示されています。64 ビット版をダウンロードしたつもりで32 ビット版をインストールしてしまいかねないので速やかに修正した方が良いかと思ったのですが、SUMO でも MDN でも mozilla.jp でもないためか、翻訳方法が分かりませんでした。

**Comment by marsf** [comment]
ご報告ありがとうございます。
mozilla.org サイトのローカライズは、以前は Pontoon でローカライズできていたのですが、日本語は翻訳率が低いままだったため、今年の 4 月以降ベンダーに委託されています。
https://discourse.mozilla.org/t/involving-mozilla-copywriters-and-translation-vendors-in-mozilla-org-localization/77978

Bugzilla にバグとして報告しました。
[Bug 1726916 - [ja] Japanese download page of Firefox for Enterprise has incorrect title for Windows 32bit](https://bugzilla.mozilla.org/show_bug.cgi?id=1726916)

**Comment by marsf** [comment]
修正されたので close します。

**Comment by Guest126** [comment]
そういうことだったのですね。
Bugzilla への Issue 登録ありがとうざいました。
修正確認しました。

**Comment by Guest126** [comment]
備忘録

サイト修正差分
https://github.com/mozilla-l10n/www-l10n/commit/53900310a5677322c927b4b3a218786e80f24dbd

marsf さんに教えていただいた情報は https://github.com/mozilla-japan/translation/wiki に追記しました。

wiki 修正差分
https://github.com/mozilla-japan/translation/wiki/Home/_compare/13b8b99d426a624b04f1988a057503a483a7736d...5ecbd0cf47813ce3d2b0a083be162f9411c86b24

// 自分が mozilla-japan/gecko-l10n と mozilla-japan/translation を間違えて投稿していたことに後から気付きました。
