### ISSUE TITLE
Firefox ｢音声の再生をブロック｣について

### ISSUE THREAD

**Issue by githubonlydigdig** [mozilla-japan/gecko-l10n#268]
Firefox 
about:preferences#privacy
許可設定
自動再生
｢音声の再生をブロック｣について

これは｢自動ミュート｣のように錯覚してしまうのですが､
原文も｢音声の｣なのでしょうか?
実際は､音声のあるメディアの再生をデフォルトブロック
するようです｡
https://support.mozilla.org/ja/kb/block-autoplay
の冒頭文

WEB会議でちょっと戸惑ったものでして｡
![スクリーンショット 2021-08-25 08-52-39](https://user-images.githubusercontent.com/78333856/130706286-0497ab71-eef1-4eba-b0e0-59b409897b6d.png)

**Comment by Cai0407** [comment]
https://transvision.mozfr.org/?recherche=%E9%9F%B3%E5%A3%B0%E3%81%AE%E5%86%8D%E7%94%9F%E3%82%92%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF&repo=gecko_strings&sourcelocale=ja&locale=en-US&search_type=strings_entities
英語版の UI でも「Block Audio」となっており、音声のみ再生せず動画は再生するように読めます。

サポート記事の原文はこちらです。
https://support.mozilla.org/en-US/kb/block-autoplay

> Firefox blocks all media with sound from playing automatically, by default.

「media with sound」の自動再生自体をブロックする旨になっていますね。

> The default Block Audio setting will prevent autoplay for all media with sound. 

こちらは「all media with sound」の自動再生をブロックする（音声付きメディアの再生そのものを行わない）のか「all media」の「with sound」での自動再生をブロックする（音声無しで動画のみ再生する）のかどちらとも解釈できるように思えます。

**Comment by githubonlydigdig** [comment]
ご見解ありがとうございます｡

実際の挙動をストリーミング映画で見ると
｢音声の再生をブロック｣は「media with sound」の自動再生自体をブロックしますが､
サポート記事の翻訳では､
｢既定 は 音声の再生をブロック の設定で、すべてのメディアで音声の自動再生を行いません。｣ になっています｡ 
https://support.mozilla.org/ja/kb/block-autoplay

本当は①原文UI自体の補正が好ましいと思いますが､
②できれば､サポート記事の翻訳修正
③賛同得られれば､UI翻訳も補正､案｢音声のあるメディアの再生をブロック｣

を提案いたします｡

**Comment by marsf** [comment]
自動再生の機能は、Mozilla Blog の説明が分かりやすいです。
[Stop video autoplay with Firefox](https://blog.mozilla.org/en/products/firefox/stop-video-autoplay/)
> You have three ways to experience videos your Firefox browser:
> 1) Allow audio and video → Free for all. Videos play on.
> 2) Block audio → Silent movie style. Videos play, but are muted.
> 3) Block audio and video → Freeze frame. Videos are stopped until you press the play button.

既定値の [Block audio] は、要するに自動ミュートです。

**Comment by marsf** [comment]
設定のほうを改善するのであれば、自動再生の設定であることが自明なので原文のとおり「〜の再生」を除くのはいかがでしょうか。
```
permissions-capabilities-autoplay-allow =
    .label = 音声と動画を許可
permissions-capabilities-autoplay-block =
    .label = 音声のみをブロック
permissions-capabilities-autoplay-blockall =
    .label = 音声と動画をブロック
```

それ以前に、プルダウンメニューの語尾が切れてるので短くしないといけないのもあります。ここの列幅、調整できないんですね。
![firefox91-autoplay-settings](https://user-images.githubusercontent.com/2100406/130778881-b92b01d4-0097-4c2b-844c-4f7feca55d3c.png)

**Comment by githubonlydigdig** [comment]
「Block Audio」は自動ミュートに思えないんですよ｡
また私の齟齬のようで自信は無くなってきましたが以下､

例えば現在Gyao配信中のジパング
https://gyao.yahoo.co.jp/episode/%E3%82%B8%E3%83%91%E3%83%B3%E3%82%B0%20BroadBand%20Edition%E3%80%80%E7%AC%AC1%E8%A9%B1%20%E3%81%BF%E3%82%89%E3%81%84%E5%87%BA%E6%B8%AF/5f97b74e-7b27-4509-b5b9-6327d12cd3b0
①Firefoxの挙動､音声ある映像ごとブロックされる
②Chromiumの挙動､音声と映像の両方自動再生される
両者新品のプロファイルで設定デフォルト､拡張機能なし

①は､サポート記事の冒頭にある､音声のあるメディアの再生をブロック
に見えるのですが｡
https://support.mozilla.org/ja/kb/block-autoplay

**Comment by marsf** [comment]
すみません、自動再生のブロックは Firefox 69 で導入されましたが、Firefox 78 で動作が変更されていたようです。
[Bug 1509933 - Use transient user activation as the default way to detect if the action is an user-input for `click-to-play`](https://bugzilla.mozilla.org/show_bug.cgi?id=1509933)

Mozilla Wiki の説明の方が詳しいようです。
[Media/block-autoplay](https://wiki.mozilla.org/Media/block-autoplay)

MDN の説明は、おそらく一部古いままです。
[Autoplay guide for media and Web Audio APIs](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide#browser_configuration_options)

> 既定値の [Block audio] は、要するに自動ミュートです。

これも間違いでした。現在の動作は、

- Block Audio: 音の鳴るメディアをブロックするが、音の鳴らないメディアはブロックしない。つまり、音量 0 または初めからミュートされている動画は自動再生される。 参照: [Autoplay availability](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide#autoplay_availability)
- Block Audio and Video: 音声の有無にかかわらず、すべてブロックする

**Comment by marsf** [comment]
というわけで、再提案です。
```
permissions-capabilities-autoplay-allow =
    .label = 音声と動画の再生を許可　→　音声と動画を許可
permissions-capabilities-autoplay-block =
    .label = 音声の再生をブロック　→　音声をブロック
permissions-capabilities-autoplay-blockall =
    .label = 音声と動画の再生をブロック　→　音声と動画をブロック
```

**Comment by githubonlydigdig** [comment]
androidのfirefoxは「音声のみブロック」で正に自動ミュートします。
デスクトップ版で「音声をブロック」だとやはり自動ミュートを連想します。

**Comment by marsf** [comment]
確認ですが、おっしゃっている「自動ミュート」とは、音量 0 でない動画がミュートで自動再生される (Firefox が強制ミュートにして再生している) という意味でしょうか？
それとも、自動再生しないという意味でしょうか？

このデスクトップ版の設定は、後者の「自動再生しない」です。

ちなみに Android 版は "[Block Audio only](https://pontoon.mozilla.org/ja/firefox-for-android/all-resources/?string=208679)" で、デスクトップ版の機能とは異なるようです。
- [Does blocking autoplay work differently on Android? | Mozilla Wiki](https://wiki.mozilla.org/Media/block-autoplay#Does_blocking_autoplay_work_differently_on_Android.3F)
- https://github.com/mozilla-mobile/fenix/search?q=AUTOPLAY_AUDIBLE

**Comment by marsf** [comment]
「音声ありをブロック」ではどうでしょうか。

**Comment by marsf** [comment]
ページ情報ウィンドウは見逃してました。別です。

https://github.com/mozilla-japan/gecko-l10n/blob/4b1280f56baba9ac5d227d9683fbdf1d22e8c951/ja/browser/chrome/browser/sitePermissions.properties#L30-L32

**Comment by marsf** [comment]
追加で変更しました。ありがとうございました。
https://hg.mozilla.org/l10n-central/ja/rev/f5c6cc39da94561f6a75407844c09b87622a3361
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/dd249fec38dc14296c321bb5d0cb865e96a8d252

**Comment by Guest126** [comment]
事後ですが事例共有です。

[ABEMA](https://abema.tv/)では「音声ありをブロック」にしている場合、音声がミュートの状態で動画の自動再生が行われるようです（Firefox 94.0.2 on Windows 10で確認）。つまり、当初の「音声の再生をブロック」という文言と一致する挙動になります。なお、ABEMAはFirefoxを推奨環境外としており、どこまで意図した挙動なのかは分かりませんが、このあたりは実装依存なのかもしれません。

その他、Googleの[Shaka Player Demo](https://shaka-player-demo.appspot.com/demo)やNetlifyの[hls.js demo](https://hls-js.netlify.app/demo/)では確かに「音声ありをブロック」という文言と一致する挙動になります。

ご参考までに。

**Comment by githubonlydigdig** [comment]
サイトのトップページに音声**なし**映像を置くサイトも散見されます｡
事例もろもろ
https://sankoudesign.com/category/movie/
音の無いそういうサイトでは「音声ありをブロック」では想定どおり自動再生されます（文言と一致する挙動）
この機能は音あるサイトにアクセスして突然の音でビックリしないための機能なのでしょうね｡
