### ISSUE TITLE
devtools での minimize の訳を修正

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/gecko-l10n#27]
Minimize = 最小化が好みです。圧縮でも間違ってません。

https://github.com/mozilla-japan/gecko-l10n/blob/master/ja/browser/chrome/browser/devtools/debugger.dtd#L46
<!ENTITY debuggerUI.autoPrettyPrint "自動的にソースを小さく整形">

Auto Prettify Minimized source なので、小さく整形では無く、「最小化されたソースを自動的に整形表示」ではないでしょうか (Preffify = 読みやすく展開 = Minimize の逆の処理)

https://github.com/mozilla-japan/gecko-l10n/blob/master/ja/browser/chrome/browser/devtools/debugger.dtd#L101
<!ENTITY debuggerUI.autoBlackBox "圧縮されたソースを自動的にブラックボックス化する">

最小化でも圧縮でも、こちらと上記の minimize 訳語は揃える感じで

**Comment by marsf** [comment]
ja.filters の ja.Minimize "最小化" / ja-JP-mac.Minimize "しまう" とかぶってます。
「圧縮された」に変更します。
