### ISSUE TITLE
Firefoxブックマーク画面､キーワード｢を｣→｢で｣

### ISSUE THREAD

**Issue by githubonlydigdig** [mozilla-japan/gecko-l10n#272]
一字ですが､キーワード｢を｣→｢で｣にした方が自然だと思い､掲上させていただきます｡

![キーワード｢を｣→｢で｣](https://user-images.githubusercontent.com/78333856/133167518-0379f451-e41c-4364-8066-4fadfbe6e948.png)

**Comment by Cai0407** [comment]
browser/browser/editBookmarkOverlay.ftl:bookmark-overlay-keyword-caption-label-2
`Use a single keyword to open bookmarks directly from the address bar`

英語版はこうなっています。これはチェックボックス型の選択肢ではなく説明文ですので、

`キーワードはアドレスバーから直接ブックマークを開くのに使用されます`

といった形のほうが自然ではないでしょうか。

同じ理由で、一つ上のタグの方も

browser/browser/editBookmarkOverlay.ftl:bookmark-overlay-tags-caption-label
`タグはブックマークの管理とアドレスバーからの検索に使用されます`

こんな感じで。

**Comment by githubonlydigdig** [comment]
賛成です｡
原文的にも日本語訳的にも､現行より自然な感じです｡
一字でしたが､お手数お掛けし､申し訳ありません｡

**Comment by marsf** [comment]
ご提案ありがとうございます。
```
bookmark-overlay-tags-caption-label = Use tags to organize and search for bookmarks from the address bar
bookmark-overlay-keyword-caption-label-2 = Use a single keyword to open bookmarks directly from the address bar
```
それぞれ、以下のようにします。
```
bookmark-overlay-tags-caption-label = タグはブックマークの整理とアドレスバーからの検索に使用します
bookmark-overlay-keyword-caption-label-2 = キーワードはアドレスバーから直接ブックマークを開くのに使用します
```

**Comment by marsf** [comment]
https://hg.mozilla.org/l10n-central/ja/rev/88c1a6598718f8f2465820aad484e94bab3bcec7
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/ac899d7a9d18c59e984a9a4346338658c00f6d9b

**Comment by githubonlydigdig** [comment]
仕様を知っている人には気にならない一文でしたが､初めて読むと｢を｣が2つあって意味が直感できない､と言われた次第です｡
些細な点でしたが､対応いただきありがとうございます｡
随所の日本語表記では他のブラウザより分かりやすいFirefox､私もそれを応援させていただき嬉しいです｡
