### ISSUE TITLE
Firefox ｢アカウントの管理｣画面上の｢プロファイル｣との表記について

### ISSUE THREAD

**Issue by githubonlydigdig** [mozilla-japan/gecko-l10n#274]
Firefox｢設定｣ー｢同期｣ー｢アカウントの管理｣画面に
｢プロファイル｣とい項目名があるのは､イザという時に混乱の元だと感じます｡
日本人語感で人格に近い意味“プロフィール”として､｢プロファイル｣が使われているとは感じます｡

一方､Firefoxのヘルプにおいては､｢プロファイル｣と言えば､
自分のローカルディスク内の“設定データベース”としての｢プロファイル｣一辺倒

Firefox内において､｢プロファイル｣という単語の意味が2つ内在してしまっていると言えるかも知れません｡

｢アカウントの管理｣画面上の｢プロファイル｣との表記は､“プロフィール”としておいた方が､少なくとも日本人ユーザーにとって混乱を抑制する小さな工夫になると思います｡
一般的なユーザーは｢プロファイル｣と言われれば､アカウントの方を連想してしまうだろうと思うからです｡
![スクリーンショット 2021-09-22 07-44-42](https://user-images.githubusercontent.com/78333856/134262371-541a3500-c275-4e65-8fe5-a68bc70001a3.png)

**Comment by marsf** [comment]
Firefox アカウントの「プロファイル」は

> “設定データベース”としての｢プロファイル｣

であり、いわゆる人物紹介や略歴として使われていません。
混乱するような場面はあるでしょうか？

ちなみに、「プロフィール」はフランス語からきた読み方です。

**Comment by githubonlydigdig** [comment]
アカウントの｢プロファイル｣が自己紹介を目的としたものではない事は私は理解しています｡

例えば､このヘルプ､
https://support.mozilla.org/ja/kb/profile-manager-create-and-remove-firefox-profiles
冒頭にこんな説明があります｡

> Firefox は、ブックマークやパスワード、ユーザー設定項目といった個人情報を、プロファイル と呼ばれるファイル一式に保存し、Firefox のプログラムファイルとは別の場所に保管します。複数のプロファイルを作成して、それぞれに個別のユーザー情報を記憶させることもできます。プロファイルの作成、削除、そして名称変更は、Firefox プロファイルマネージャーから行います。

一般ユーザーはこれを読んで､**アカウントの**プロファイルと錯誤するのではないか?
との発想です｡
両者の違いは､ブラウザに熟知している人にとっては概念の違いは明白ですが､
一般ユーザーにとっては､別物であることがわからないものです｡

ならばあえて､アカウントの方は｢プロフィール｣として表現を差別化しておいた方が良いのでは､
と感じている次第です｡

**Comment by marsf** [comment]
区別のため仮に、PC に保存されるプロファイルを「ユーザープロファイル」、ウェブ上の Firefox アカウントのプロファイルを「アカウントプロファイル」とします。

> 一般ユーザーはこれを読んで､アカウントのプロファイルと錯誤するのではないか?

申し訳ありません。なぜ一般ユーザーが、アカウントプロファイルと錯誤する (アカウントのほうを連想してしまう) のかが理解できません。
問題の発端は、SUMO のヘルプ記事とアカウントプロファイルの名称のどちらでしょうか？

ユーザープロファイルは、ファイル一式、特別なフォルダーに保存されると明記され、そのフォルダーも容易に開くことができます。
アカウントプロファイルにあるのは、名前・写真と Firefox アカウントのメールアドレスとパスワードだけで、一画面に収まる内容です。パスワード以外にユーザープロファイルの設定と同じ項目はありません。
これらの区別がつかないとすれば、設定情報をどちらも「プロファイル」と呼んでいることが原因ではないと思いますがいかがでしょうか？

**Comment by githubonlydigdig** [comment]
私が感じる理想は､PC に保存される｢プロファイル｣はもっと別の表現が良いと常々思っていました｡
でもそれは現実的な提案ではありません｡
しからば､ウェブ上の Firefox アカウントの｢プロファイル｣を変更するのはどうかしら?と感じた次第です｡

> 申し訳ありません。なぜ一般ユーザーが、アカウントプロファイルと錯誤する (アカウントのほうを連想してしまう) のかが理解できません。

につきまして､

> 両者の違いは､ブラウザに熟知している人にとっては概念の違いは明白ですが､
> 一般ユーザーにとっては､別物であることがわからないものです｡

の感覚に共感いただけないようであれば､この提案は私の老婆心なのかもしれません｡

ご思案いただいてしまいました｡
クローズしてください｡

**Comment by marsf** [comment]
> 両者の違いは､ブラウザに熟知している人にとっては概念の違いは明白ですが､
> 一般ユーザーにとっては､別物であることがわからないものです｡

両者の「プロファイル」という単語は、先にも書きましたように、**同じ概念**で使われています。

「別物」が単語の意味・使い方のことでないならば、「ユーザープロファイルとアカウントプロファイルは設定の対象が異なる別物です」という言い方しかできません。それぞれ、「Firefox アプリケーションのプロファイル」「Firefox アカウントのプロファイル」と区別できます。

そもそもの "profile" の訳語を「プロファイル」から「プロフィール」にしたい、ということであれば、Mozilla の訳語で使用している「プロファイル」は日本人が一般に使う「プロフィール」とは別物なので、違うものを意味することになってしまうのではないか、という回答になります。


> 私が感じる理想は､PC に保存される｢プロファイル｣はもっと別の表現が良いと常々思っていました｡

英語の "profile" を別の表現にしたいということであれば、ローカライズの範疇を超えるので Bugzilla で提案してください。
それとも別の訳語にしたいのであれば、20 年近く使用されている訳語を変更するに足る提案 (ユーザーを説得できる提案) をしなければならないと思います。

**Comment by marsf** [comment]
ちなみに、アプリケーションの "profile" は「プロフィール」ではないのか、ウェブサービス上の名称は「プロフィール」にしてはどうか、という意見は、これまでに何度か聞いたことがあります。
そのたびに、おおよそ上記を理由として、そのまま「プロファイル」が使われています。

間違いがあれば、どなたかコメントください。

**Comment by githubonlydigdig** [comment]
> 「ユーザープロファイルとアカウントプロファイルは設定の対象が異なる別物です」という言い方しかできません。それぞれ、「Firefox アプリケーションのプロファイル」「Firefox アカウントのプロファイル」と区別できます。

ここが一般ユーザーには直感できないし､わかりやすいヘルプも見当たらない｡
ならば...と思った提案でしたが､取り下げます｡

お時間をいただいてしまい申し訳ありませんでした｡
