### ISSUE TITLE
Firefox 設定画面｢文字サイズのみ変更｣について

### ISSUE THREAD

**Issue by githubonlydigdig** [mozilla-japan/gecko-l10n#285]
Firefox の日本語利用､いつもお世話になっています｡

設定画面｢文字サイズのみ変更｣について

｢ズームは文字サイズのみに適用｣にした方が直感的だと感じます｡

“変更” は前文の､既定のズーム設定への“変更”を連想します｡
ここは英文どおり､“ズーム”の方がしっくりきます｡
共感あればご検討願います｡
![zoom](https://user-images.githubusercontent.com/78333856/138652698-f745bb50-42cd-420e-a5c5-ac672e43f889.png)

**Comment by marsf** [comment]
> “変更” は前文の､既定のズーム設定への“変更”を連想します｡ 

これは、連想されている通り、既定のズーム設定に対する変更でもあります。

**Comment by githubonlydigdig** [comment]
私は違和感を感じますが､修正見送りであればCloseしてください｡
