### ISSUE TITLE
Firefox 設定画面｢Firefox ホーム (既定) ｣について

### ISSUE THREAD

**Issue by githubonlydigdig** [mozilla-japan/gecko-l10n#286]
Firefox の日本語利用､いつもお世話になっています｡

設定画面｢Firefox ホーム (既定) ｣について
表記ブレのような印象を持ちます｡
｢Firefox Home (既定) ｣の方が良いのではと感じます｡
共感あればご検討願います｡
![スクリーンショット](https://user-images.githubusercontent.com/78333856/139559923-2e7273aa-17a2-4b59-ba4d-0b82649ed7df.png)

**Comment by marsf** [comment]
ここは「Firefox Home」ですね。

https://github.com/mozilla-japan/gecko-l10n/blob/3e2f88d672e0bfad794232e2811e198f5511835b/ja/browser/browser/preferences/preferences.ftl#L576```

```
home-mode-choice-default =
    .label = Firefox ホーム (@@Default@@)
```

**Comment by githubonlydigdig** [comment]
固有名詞的に「Firefox Home」で表記ブレ感がなくなります｡

**Comment by marsf** [comment]
https://hg.mozilla.org/l10n-central/ja/rev/d8a655e634be841342f302aefaf323edee144aae
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/87a13f63c7507a0bbce8c4b6ef426e7f15e4179d
