### ISSUE TITLE
Android Firefox 設定画面｢アプリ内でリンクを開く ｣について

### ISSUE THREAD

**Issue by githubonlydigdig** [mozilla-japan/gecko-l10n#287]
Firefox の日本語利用､いつもお世話になっています｡
Android 版について 

①設定画面｢アプリ内でリンクを開く｣について
｢内の｣を削除して､
｢アプリでリンクを開く｣の方が良いのではと感じます｡

②｢強化されたトラッキング防止｣はデスクトップ版と表現を合わせて､
｢強化型トラッキング防止機能｣の方が良いのではと感じます｡

共感あればご検討願います｡
![1](https://user-images.githubusercontent.com/78333856/140025686-733941b7-d87e-4a8f-b464-364ed37139c8.png)

**Comment by dskmori** [comment]
> ①設定画面｢アプリ内でリンクを開く｣について ｢内の｣を削除して､ ｢アプリでリンクを開く｣の方が良いのではと感じます｡

Open links in apps: https://pontoon.mozilla.org/ja/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?string=206864
 
> ②｢強化されたトラッキング防止｣はデスクトップ版と表現を合わせて､ ｢強化型トラッキング防止機能｣の方が良いのではと感じます｡

Enhanced Tracking Protection: https://pontoon.mozilla.org/ja/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?search=%E5%BC%B7%E5%8C%96&string=201342

**Comment by marsf** [comment]
それぞれ Pontoon で修正しました。
「強化された」が使われているのは Firefox for Android のみで、Firefox for iOS, Focus for Android / iOS にはありませんでした。

ありがとうございました。
