### ISSUE TITLE
Firefox 履歴削除画面｢サイトの設定｣について

### ISSUE THREAD

**Issue by githubonlydigdig** [mozilla-japan/gecko-l10n#288]
Firefox の日本語利用､いつもお世話になっています｡

履歴削除画面｢サイトの設定｣について
何を指しているのか不明確です｡

｢許可｣を追加して
｢サイトの許可設定｣の方が良いのではと感じます｡

共感あればご検討願います｡
![2](https://user-images.githubusercontent.com/78333856/140280767-db03220e-4a78-4fed-bea3-55e5fe55e9bb.png)

**Comment by marsf** [comment]
これは、サイトの許可設定だけでなく、その他のサイトに関連するデータを含みます。

最近の履歴を消去する
https://support.mozilla.org/ja/kb/delete-browsing-search-download-history-firefox

**Comment by githubonlydigdig** [comment]
Android版では｢サイトの許可設定｣となっており､分かりやすいと思い提案しました｡
Closeしてください｡

**Comment by marsf** [comment]
Android 版 Firefox とは異なります。
