### ISSUE TITLE
Firefox 94.0 Linux版の「履歴の消去設定」画面でボタンのレイアウトが乱れて見切れています

### ISSUE THREAD

**Issue by EarlgreyPicard** [mozilla-japan/gecko-l10n#289]
MozillaZine.jpフォーラムの[投稿](https://forums.mozillazine.jp/viewtopic.php?f=29&p=69947#p69929)で気がついたのですが、表題の通りとなっております。
Linux版とWindoiws版の同じ画面の画像を添付いたしますのでご確認ください。

![履歴の消去設定画面](https://user-images.githubusercontent.com/4388176/140638070-d63735f3-6d0e-4257-86e0-9ea0318792a9.jpg)

**Comment by marsf** [comment]
メニューの [履歴] > [最近の履歴を消去] ではなく、
[設定] > [プライバシーとセキュリティ] > [最近の履歴を消去...] のほうのダイアログですね。
ローカライズのリソースは同じものを参照していますが、ダイアログの構造が一部違うようです。
* 履歴のダイアログ
https://searchfox.org/mozilla-central/source/browser/base/content/sanitize.xhtml
* 設定のダイアログ
https://searchfox.org/mozilla-central/source/browser/components/preferences/dialogs/sanitize.xhtml

右側がはみ出している設定のほうでは、`vbox` に `flex=1` の指定がありません。
```
<vbox>
  <checkbox data-l10n-id="item-offline-apps"
            preference="privacy.clearOnShutdown.offlineApps"/>
</vbox>
```
bugzilla で修正してもらうバグです。

**Comment by marsf** [comment]
Windows でも、システムフォントを幅広のものに変更すると同じようにはみ出るはずです。

**Comment by marsf** [comment]
ローカライズでダイアログのサイズを変更することもできます。
https://github.com/mozilla-japan/gecko-l10n/blob/3e2f88d672e0bfad794232e2811e198f5511835b/ja.filters#L232-L236

https://github.com/mozilla-japan/gecko-l10n/blob/d67e27261bbeaed6b3972f6b1999957e672558ad/ja/browser/browser/sanitize.ftl#L5-L9

**Comment by EarlgreyPicard** [comment]
> ```
> <vbox>
>   <checkbox data-l10n-id="item-offline-apps"
>             preference="privacy.clearOnShutdown.offlineApps"/>
> </vbox>
> ```
> 
> bugzilla で修正してもらうバグです。

ご指摘ありがとうございます。
「ウェブサイトのオフライン作業用データ」が突き抜けてしまっているのが元凶のようですね。
bugzilla.mozilla.org へ報告してみます。

**Comment by EarlgreyPicard** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1739888 を起票しました。
Windows でメイリオとかでも起きそうですが、フォント変更はレジストリをいじるかユーティリティが必要で再現手順としてふさわしくないので、当初のUbuntu日本語環境としてみました。

**Comment by marsf** [comment]
Firefox 96.0 Beta で修正されたようなので close します。
ありがとうございました。
