### ISSUE TITLE
 image-size treecol has wrong Japanese in Page Info - Media

### ISSUE THREAD

**Issue by makotokato** [mozilla-japan/gecko-l10n#29]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1215909

**Comment by marsf** [comment]
42.0 以降で修正しました。
https://github.com/mozilla-japan/gecko-l10n/commit/1ff935dcb9181986a5c26159913d9ef43a8a205f
https://github.com/mozilla-japan/gecko-l10n/commit/e4473e9e397b5e8d881a4570e8ccf851a3ef5888
