### ISSUE TITLE
Firefoxデスクトップ版 同期の「開いたタブ」

### ISSUE THREAD

**Issue by githubonlydigdig** [mozilla-japan/gecko-l10n#293]
Firefox の日本語利用､いつもお世話になっています｡

Firefoxデスクトップ版 同期の「開いたタブ」について､

「開いたタブ」は「履歴」との区別が直感できないので､
ヘルプ記事の説明に準じて「開いているタブ」のような過去進行形が良いのではと思います｡
https://support.mozilla.org/ja/kb/how-do-i-choose-what-types-information-sync-firefox

![同期設定](https://user-images.githubusercontent.com/78333856/144134143-cf585b05-08d8-4c4b-ad77-50041a03a606.png)

**Comment by githubonlydigdig** [comment]
本件､表記ブレの観点を追加しておきます｡
![無題](https://user-images.githubusercontent.com/78333856/146158162-c56b836f-e080-4b4d-8876-ee368f9ea08c.png)

**Comment by githubonlydigdig** [comment]
放置案件につき､不歓迎と忖度のうえCloseします｡

**Comment by makotokato** [comment]
@marsf @hATrayflood @dynamis 

Firefox 内のローカライズとFirefox Account (https://pontoon.mozilla.org/ja/firefox-accounts/LC_MESSAGES/client.po/?string=201140) のローカライズが違うという話みたいですが、Firefox L10N としてどっちが正しいのですかね？

- クレジットカード vs クレジットカード情報
- 個人設定 vs 設定
- 開いたタブ vs 開いているタブ

**Comment by marsf** [comment]
@githubonlydigdig
お待たせしてすみません。同期項目の関連で翻訳の揺らぎが多く、修正箇所を調べているところです。

**Comment by marsf** [comment]
@makotokato 
問題は、訳語の違いもありますし、「開いたタブ」は「過去に開いたタブ」も含まれてしまうのではないかという懸念、の両方です。

> クレジットカード vs クレジットカード情報

→ 「クレジットカード情報」
フォームに入力する情報なので「情報」をつけます。

> 個人設定 vs 設定

→「個人設定」
たしか、Sync が実装された当初は "Personal Settings" だったと思います。機能的には同期内容が変更されているはずですが、「設定」では何の設定か分からないのでそのまま「個人設定」にしています。

> 開いたタブ vs 開いているタブ

→ 「開いているタブ」
現在開いているタブを同期するので現在形の「開いているタブ」のほうが適切です。
これは、["Open tabs" の訳語の揺らぎ](https://transvision.mozfr.org/?recherche=open+tabs&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings) が大きく、整理する必要があります。「タブを開く」とも区別しなければなりません。

それぞれ、Firefox、Firefox アカウント、Pontoon の他の製品で統一する必要があります。

**Comment by marsf** [comment]
@makotokato 
それから、「履歴」にもいろいろあるので「ページの表示履歴」としたいところですが、他の履歴 (検索履歴、フォームの入力履歴など) も含まれるのでしょうか？

**Comment by makotokato** [comment]
私の認識は、https://support.mozilla.org/en-US/kb/how-do-i-choose-what-information-sync-firefox に書いてあるようにplacesのhistory (表示履歴) を同期してるだけだったと思います。

**Comment by marsf** [comment]
Pontoon 側のモバイル製品と Firefox アカウントはすべて統一しました。
- 開いているタブ
- クレジットカード情報
- 表示履歴

**Comment by githubonlydigdig** [comment]
先般の自己Closeは失礼お詫びし､ご対応に御礼申し上げます｡

**Comment by marsf** [comment]
browser の「開いたタブ」以外の修正箇所は、[preferences.ftl の sync-currently-syncing-*](https://hg.mozilla.org/l10n-central/ja/file/ee52857c0724fed5f86424f25776c94fee3413ce/browser/browser/preferences/preferences.ftl#l817) のみでした。

**Comment by marsf** [comment]
まとめて修正しました。
https://hg.mozilla.org/l10n-central/ja/rev/af524692c7751d51bb72d947451f3c42727634ac
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/6beb1db191e1b7f8fd1b1281f349934592f1d5f0

**Comment by vegam57** [comment]
機械翻訳的な違和感はないFirefoxは､それだけでアプリとしての質感を感じます｡
皆様のお陰です｡
ありがとうございました｡
