### ISSUE TITLE
[拡張機能のショートカットキーの管理] の [ショートカットキーを入力してください] が見切れている

### ISSUE THREAD

**Issue by hokonch** [mozilla-japan/gecko-l10n#294]
Firefox v95.0
原文は`Type a shortcut` です。
スクリーンショットは Windows 10 ですが、手元の Linux 環境では「ショートカットキーを入力し」までしか正しく表示されません。
ここは「を入力」で体言止めして問題ないかと思います。
`shortcut` の訳語は「ショートカット」と「ショートカットキー」で割れているようですが、統一するかも含めておまかせします。

https://github.com/mozilla-japan/gecko-l10n/blob/1f7cacf61b5c63507c31757e9ae6b9d02d852fc6/ja/toolkit/toolkit/about/aboutAddons.ftl#L197-L198
![Screenshot](https://user-images.githubusercontent.com/54430032/145697783-43c20062-03de-435e-8e06-7ce92c311181.png)

**Comment by marsf** [comment]
ご報告ありがとうございます。
「ショートカットキーを入力」にしました。
96.0 で修正されます。
