### ISSUE TITLE
ダウンロード周りの「フォルダーに表示 / Finder に表示」

### ISSUE THREAD

**Issue by Cai0407** [mozilla-japan/gecko-l10n#296]
https://transvision.mozfr.org/?recherche=%E3%83%95%E3%82%A9%E3%83%AB%E3%83%80%E3%83%BC%E3%81%AB%E8%A1%A8%E7%A4%BA&repo=gecko_strings&sourcelocale=ja&locale=en-US&search_type=strings
browser/browser/downloads.ftl の
downloads-cmd-show-button-2.tooltiptext
downloads-cmd-show-description-2.value
downloads-cmd-show-menuitem-2.label
downloads-cmd-show-panel-2.aria-label

> { PLATFORM() ->
        [macos] Finder に表示
       *[other] フォルダーに表示
    }

ですが、ぱっと見で違和感を感じます。
原文は

> { PLATFORM() ->
      [macos] Show in Finder
     *[other] Show in Folder
  }

なので「～に表示」でもいいのですが、実際の挙動を考えると

> { PLATFORM() ->
      [macos] Finder で表示
     *[other] フォルダーを表示

としたほうがわかりやすいのではないかと。
other は Win、Linux での汎用性重視で「フォルダー**を**表示」としてみましたが、OS 決め打ちをさらに細分化することが OK なら

> { PLATFORM() ->
      [macos] Finder で表示
     *[win] エクスプローラーで表示
      [linux] ファイラーで表示

みたいな感じでどうでしょう？

**Comment by marsf** [comment]
以前は ["Open Containing Folder" (保存フォルダーを開く)](https://transvision.mozfr.org/?recherche=%E4%BF%9D%E5%AD%98%E3%83%95%E3%82%A9%E3%83%AB%E3%83%80%E3%83%BC&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings) だったものが、なぜか macos に合わせて変更されてしまいました。
動作は全く同じはずです。

[/browser/browser/downloads.ftl](https://hg.mozilla.org/l10n/gecko-strings/file/461c6dec65a903b925f41a6cfdc1bc2f1b097b86/browser/browser/downloads.ftl#l32)
```
# This message is only displayed on Windows and Linux devices
downloads-cmd-show-menuitem =
  .label = Open Containing Folder
  .accesskey = F

# This message is only displayed on macOS devices
downloads-cmd-show-menuitem-mac =
  .label = Show In Finder
  .accesskey = F

downloads-cmd-show-menuitem-2 =
  .label = { PLATFORM() ->
      [macos] Show in Finder
     *[other] Show in Folder
  }
  .accesskey = F
```

変更するなら元の翻訳に戻したほうが良いと思います。

**Comment by Cai0407** [comment]
> 以前は ["Open Containing Folder" (保存フォルダーを開く)](https://transvision.mozfr.org/?recherche=%E4%BF%9D%E5%AD%98%E3%83%95%E3%82%A9%E3%83%AB%E3%83%80%E3%83%BC&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings) だったものが、なぜか macos に合わせて変更されてしまいました。 動作は全く同じはずです。

https://hg.mozilla.org/l10n/gecko-strings/rev/9da5551cee9796a3b70e649815aceaedf15e115a
ですね。
commit log も定型だし、変更の意図がわかりませんね。

> 変更するなら、Windows/Linux を元の翻訳に戻したほうが良いと思います。

同意です。

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/pull/297 指摘ありがとうございます。「保存フォルダーを開く」に戻しました。

gecko-stringsはbugzillaのリンクがなくなってしまったので、もうmozilla-centralで変更内容見てます。
https://hg.mozilla.org/mozilla-central/rev/5243c0c312339bb42709453c8b27afbfeef56795

**Comment by marsf** [comment]
余談ですが、Bugzilla では、[macOS を "Show in Finder" にしておくという話だけ](https://bugzilla.mozilla.org/show_bug.cgi?id=1729447#c5)で、Windows/Linux を mac のスタイルに合わせることについて何の議論もされていません。 standardizing の根拠が (標準もガイドラインも) 何もない。

**Comment by marsf** [comment]
https://hg.mozilla.org/l10n-central/ja/rev/d93bf6d833af99823b5f63d90699acef54aa7d0d
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/0e97b62d4eea1215450ab136bd97d77e5fb90cff
