### ISSUE TITLE
Firefox Mozilla Crash Reporter の画面

### ISSUE THREAD

**Issue by githubonlydigdig** [mozilla-japan/gecko-l10n#299]
Firefox 95.0.1（日本語）にてクラッシュに遭遇しました｡
レポート送信画面が英文で表示されましたので､ご報告しておきます｡
![スクリーンショット](https://user-images.githubusercontent.com/78333856/148171503-124128da-f23c-4c36-8458-f258c223a36c.png)

もしクラッシュ時でも日本語で表示できるような仕組みならば､
以下､提案です｡

Mozilla クラッシュレポーター

ごめんなさい
Firefox はクラッシュしました｡Firefox を再起動していただけたら､タブとウィンドウの復旧を試みます｡

この問題の分析と修正をする手助けとして､あなたはクラッシュレポートを私達に送信できます｡
□修正に期するためMozilla にこのクラッシュを伝える
詳細...
コメントを追加(コメントは公開されます)

私が見ていたページのアドレスを含める

Firefox を終了    Firefox を再起動

**Comment by dskmori** [comment]
https://hg.mozilla.org/l10n-central/ja/file/default/toolkit/crashreporter/crashreporter.ini
https://hg.mozilla.org/l10n-central/ja/file/tip/browser/crashreporter/crashreporter-override.ini

ここら辺を見る限り、ローカライズ自体は済んでそうですね。

**Comment by githubonlydigdig** [comment]
ご確認いただき､ありがとうございます｡
クラッシュ時につき､日本語データを読み込めなかったのかもですね｡
クラッシュの状況次第､といったところと思っておきます｡

**Comment by marsf** [comment]
クラッシュレポーターのローカライズは変更されていません。
手動でクラッシュレポーターを開く方法があったと思うのですが、見つけられないでいます。

**Comment by hATrayflood** [comment]
![image](https://user-images.githubusercontent.com/2013010/148677948-6962d74c-a316-4d15-8bcf-581b9bc2be25.png)

windowsは普通に日本語化されてますね。手動でクラッシュさせる方法はこちら。
https://www.clear-code.com/blog/2017/12/15.html

最初の画像はlinuxか何かですかね。この画面のローカライズはcrashreporter.iniで、通常のローカライズとは仕組みが違うため、プラットフォームによってはうまくいかないかもしれません。
https://packages.ubuntu.com/impish/amd64/firefox/filelist
https://packages.ubuntu.com/impish/amd64/firefox-locale-ja/filelist

**Comment by githubonlydigdig** [comment]
最初の画像は､そのとおりlinuxです｡
仕組みの違いに依るもののようですね｡
ボタンの左右配置も違っているようです｡
お調べいただきありがとうございました｡

**Comment by hATrayflood** [comment]
linuxディストリビュータのものではなく、mozillaがビルドしたものなら日本語になってます。
http://archive.mozilla.org/pub/firefox/releases/95.0.2/linux-x86_64/ja/

**Comment by githubonlydigdig** [comment]
linuxディストリビュータのものをmozilla標準仕様のままで同梱する事を
最近mozillaが積極的に働きかけているようですね｡
そういう違いが減る動向になればいいなと思います｡

**Comment by githubonlydigdig** [comment]
皆様､調査お手数おかけしました｡
クローズします｡
