### ISSUE TITLE
誤解を誘発しかねないボタンラベル②「アカウントを削除」

### ISSUE THREAD

**Issue by githubonlydigdig** [mozilla-japan/gecko-l10n#301]
Firefox の日本語利用､いつもお世話になっています｡

ボタンラベル「アカウントを削除」について､
2箇所で使われているのを見て､
②については､少し工夫したほうが良いのではと思いました｡

①Firefoxアカウント上の赤いボタン
②Firefox同期セクション上のボタン･･･これは「この端末から」を追加して「この端末からアカウントを削除」が望ましい｡
（このボタンはFirefoxアカウント自体がクラウド上から削除されるわけではなく､誤解を誘発しかねないラベルだと思います）

![①](https://user-images.githubusercontent.com/78333856/150617049-ef60affe-24a4-48b1-8e5d-fe32e5042f8d.png)

![②](https://user-images.githubusercontent.com/78333856/150617061-4e0d6f12-e036-4c78-bbf9-3e396977bd2c.png)

**Comment by marsf** [comment]
Firefox の同期設定のボタンは、機能的には disconnect です。
最初はボタンラベルが「切断」だったはずですが、いつからか表現が変わりました。

**Comment by githubonlydigdig** [comment]
>最初はボタンラベルが「切断」だったはずですが、いつからか表現が変わりました。（Firefox アカウントへのログインが統合されてから？）

「切断」は別の場所では?･･･③
![③](https://user-images.githubusercontent.com/78333856/152438041-bde65d00-47a2-44e7-bdad-07ebdb795e27.png)

**Comment by marsf** [comment]
元は「セットアップをキャンセル」でした。
[Bug 1444162 - Change button copy in reconnect state](https://bugzilla.mozilla.org/show_bug.cgi?id=1444162)

Firefox 60.0 で [/browser/chrome/browser/preferences/sync.dtd](https://github.com/mozilla-japan/gecko-l10n/commit/3884b4f6b3f9d84995bea80b44cb679dd4bf5219#diff-d6134c828a30e57afcb2cc7f76c3b1fb3efa1c7be93e3d95c6368579f5658624)　に追加され、そのすぐ後に [/browser/browser/preferences/preferences.ftl](https://github.com/mozilla-japan/gecko-l10n/commit/220a3128a447e66a24f8409cd4286848e6d4d2c9#diff-7488ca7c367c5ef91ce1b2dc3f77f110b487d9301336323c1c1504143fbac6af) に移行しました。

[Bug 1445694 - Migrate the "Sync" section of Preferences to the new Localization API](https://bugzilla.mozilla.org/show_bug.cgi?id=1445694)

Firefox 81.0 で、データが削除できる確認メッセージが追加されました。
[Bug 1657463 - Allow users to delete their data when signing out.](https://bugzilla.mozilla.org/show_bug.cgi?id=1657463)

同期設定の「アカウントを削除」ボタンをクリックして最終的に呼び出される関数は [gSyncPane.unlinkFirefoxAccount()](https://searchfox.org/mozilla-central/source/browser/components/preferences/sync.js#543) → [gSync.disconnect()](https://searchfox.org/mozilla-central/source/browser/base/content/browser-sync.js#1674) です。

機能的には、Firefox アプリケーションと Sync を disconnect します。同時にFirefox アカウントからのログアウトも確認して実行します。

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/pull/321/commits/4f9dc2eba0021aeba65d3c7b94edd9a72091b892 はい、それでよいと思います。修正しました。

**Comment by marsf** [comment]
ありがとうございます。
Firefox 102.0 で修正されます。
