### ISSUE TITLE
不安を煽りかねない「不正に改変された可能性があります」

### ISSUE THREAD

**Issue by githubonlydigdig** [mozilla-japan/gecko-l10n#304]
Firefox の日本語利用､いつもお世話になっています｡

Firefox93から､HTTPSページ上のダウンロードリンクが実はhttpであった場合､
ダウンロードをブロックする仕様が追加されました｡
https://blog.mozilla.org/security/2021/10/05/firefox-93-protects-against-insecure-downloads/

このメッセージ「不正に改変された可能性があります」について､
「された」は不安を煽りすぎだと感じます｡まだダウンロードはしていない段階でのメッセージなのに､不正にダウンロードされた既成事実な感じです｡
ダウンロード元から抗議されかねないのでは?と心配にもなります｡
ついては､「不正に改変**される**可能性があります」と未来形にしたほうが良いのではと思いました｡

![スクリーンショット 2022-02-02 06-35-07](https://user-images.githubusercontent.com/78333856/152059966-cad64ee8-34f6-4f0f-8a43-60618d329b3c.png)

**Comment by marsf** [comment]
この警告メッセージは、ダウンロード開始前ではなく、対象のデータがある程度ダウンロードされた後に表示されているはずです。
つまり、ダウンロードした（壊れているか改変されている）データをそのまま保存して処理を完了するかどうかを尋ねています。

また、ダウンロードを https で提供していないのに「ダウンロード元から抗議」されるとしたら筋違いな話です。ブラウザーは、ユーザーが読み込んだデータに対して注意を喚起しているのであって、その提供されたデータの完全性や真正性は保証しません。これらは暗号化プロトコルや証明書によって、ある程度保証されます。

ダウンロード前に警告するなら、「ダウンロードしようとしているファイルは https で提供されていませんが続行しますか？」のようなメッセージが表示されるようになると思います。

以上を踏まえて、改善できそうなところがあればご提案ください。

**Comment by githubonlydigdig** [comment]
私の提案は単に1文字です｡
「不正に改変された可能性があります」
↓
「不正に改変され**る**可能性があります」

あなたのようにFirefoxに詳しい方ではなく､
警告メッセージを見る一般利用者に､不安を煽りかねないケースをこの1文字の変更である程度抑制できるのでは?
という提案です｡

明らかな誤植の修正ではない提案は､応対が面倒なのはお察しします｡
でも以下､具体的に反論させていただきます｡
ご気分を害される可能性ありますので､予めお詫びします｡

>この警告メッセージは、ダウンロード開始前ではなく、対象のデータがある程度ダウンロードされた後に表示されているはずです。

いいえ､ダウンロードファイル0バイト時点で表示されます｡

>つまり、ダウンロードした（壊れているか改変されている）データをそのまま保存して処理を完了するかどうかを尋ねています。

いいえ､ダウンロードファイル0バイト時点で表示されます｡

>また、ダウンロードを https で提供していないのに「ダウンロード元から抗議」されるとしたら筋違いな話です。

あたかも既に壊れているな感じに対して「ダウンロード元から抗議」される可能性を心配するのです｡

>ブラウザーは、ユーザーが読み込んだデータに対して注意を喚起しているのであって、その提供されたデータの完全性や真正性は保証しません。これらは暗号化プロトコルや証明書によって、ある程度保証されます。

だからと言って､あたかも既に壊れているな感じな表現は避けておく方が良いのではと思うのです｡

>ダウンロード前に警告するなら、「ダウンロードしようとしているファイルは https で提供されていませんが続行しますか？」のようなメッセージが表示されるようになると思います。

英語原文考案者がそこまで考慮したかは確証できないはずです｡

>以上を踏まえて、改善できそうなところがあればご提案ください。

この壁を越えてみろな感じは残念です｡
失礼とあらば､取るに足らない意見としてCloseしていただいて構いません｡

**Comment by marsf** [comment]
申し訳ありません、以下の部分については誤りでした。
> つまり、ダウンロードした（壊れているか改変されている）データをそのまま保存して処理を完了するかどうかを尋ねています。

ご理解いただけるかどうかはともかく、具体的な動作は以下のようになっています。

1. ユーザーがリンクをクリックする
2. ダウンロード処理が開始され、要求ヘッダーがサーバーに送信される 
その際、https ではないので "[Upgrade-Insecure-Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade-Insecure-Requests)" ヘッダーが送信される。
3. サーバーの応答ヘッダーを受信する 
サーバーが上記ヘッダーの要求に応じられず http のままなので、Firefox がダウンロードをブロックするかどうかのダイアログを表示してユーザーに尋ねる。 (これがご指摘のメッセージです)

この後にデータ本体がダウンロードされますが、予めリンク先のデータをダウンロードする (読み込んでおく) プリフェッチまでは調べてません。

> 「不正に改変され**る**可能性があります」

というわけで、**実際の動作と照らし合わせて**、このように修正したほうがよいということに賛成します。

　

> 警告メッセージを見る一般利用者に､不安を煽りかねないケースをこの1文字の変更である程度抑制できるのでは?

警告を抑制する意図が理解できません。ユーザーはこの段階で安全にキャンセル (削除) できますし、ダウンロードリンク掲載元が信頼できるなら、ダウンロードを続行することもできます。
仮にダウンロードした後であっても、まず (可能であれば) システムのセキュリティソフトによる検査が行われ、Firefox が勝手にそのファイルを解釈実行することはありません。
ただし、リンク先が改竄されていた場合、ファイル提供元サーバーに残る接続ログ (通信ヘッダー、通信したユーザーの IP アドレス記録) については取り消すことができません。

> あたかも既に壊れているな感じに対して「ダウンロード元から抗議」される可能性を心配するのです｡

繰り返しになりますが、ダウンロード元からの抗議は筋違いです。
例えば、ページに悪意のあるスクリプトを仕込まれ、ユーザーの onclick でリンク先を書き換えるなどされて、リンク先が改竄されていることに気づかずユーザーを危険にさらしている可能性もあります。
過去に実際にありましたが、あくまで可能性として。

**Comment by marsf** [comment]
https://hg.mozilla.org/l10n-central/ja/rev/f7fc53733c30e982f752b622e6b697c289414611
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/8d010963667bc73188996732844078a6d26d0839
