### ISSUE TITLE
アドレスバーの不自然な日本語「検索語句を入力を入力します」

### ISSUE THREAD

**Issue by r-40021** [mozilla-japan/gecko-l10n#306]
Firefox Developer Edition のアドレスバーで検索エンジンをブックマーク、タブ、履歴のいずれかにした場合に表示される文言が「検索語句を入力を入力します」と不自然です。

![image](https://user-images.githubusercontent.com/75155258/153619130-2bb26e35-c7cc-409a-b7a0-d91b30faa061.png)

**Comment by marsf** [comment]
https://github.com/mozilla-japan/gecko-l10n/commit/75d28eeeef2f1c88191bad5be81f67ed3a66bc34#diff-6ecdb122487780cac3aa1d2d7fd3c492a8f4de7967eb0e59ae0f696ae22073e5R352-R369

**Comment by hATrayflood** [comment]
ありがとうございます。修正しました。https://github.com/mozilla-japan/gecko-l10n/pull/310/commits/04d50a6d3cbbe298b67e82594496ee79c97d8ea8
