### ISSUE TITLE
ハンドシェイク vs ハンドシェーク

### ISSUE THREAD

**Issue by Cai0407** [mozilla-japan/gecko-l10n#307]
どちらかに統一すべきです。
Google 検索では 778,000 vs 440,000 と「ハンドシェイク」のほうが優勢な模様。

https://transvision.mozfr.org/?recherche=%E3%83%8F%E3%83%B3%E3%83%89%E3%82%B7%E3%82%A7%E3%82%A4%E3%82%AF&repo=gecko_strings&sourcelocale=ja&locale=en-US&search_type=strings
/ja/netwerk/necko.properties
line 14-15:
12=%1$S との TLS ハンドシェイクを実行しています...
13=%1$S の TLS ハンドシェイクが完了しました... 

https://transvision.mozfr.org/?recherche=%E3%83%8F%E3%83%B3%E3%83%89%E3%82%B7%E3%82%A7%E3%83%BC%E3%82%AF&repo=gecko_strings&sourcelocale=ja&locale=en-US&search_type=strings
/ja/chrome/messenger/imapMsgs.properties
line 148
imapTlsError			=上書きできない TLS エラーが発生しました。ハンドシェークエラーか、TLS バージョンまたはサーバー %S が使用する証明書の互換性がない可能性があります。

**Comment by marsf** [comment]
ご指摘ありがとうございます。
「ハンドシェイク」に修正しました。

https://hg.mozilla.org/l10n-central/ja/rev/69302fb1b3f128167f50e9ed414b26e510f60d68
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/67721dc16367e316033f0dedff8b942393d05d40
