### ISSUE TITLE
違和感のある表現「電気代を増やさせる」

### ISSUE THREAD

**Issue by hokonch** [mozilla-japan/gecko-l10n#309]
> `Cryptominers use your system’s computing power to mine digital money. Cryptomining scripts drain your battery, slow down your computer, and can increase your energy bill. <a data-l10n-name="learn-more-link">Learn more</a>` (https://hg.mozilla.org/l10n/gecko-strings/file/default/browser/browser/protections.ftl)
https://github.com/mozilla-japan/gecko-l10n/blob/f1bb25b8d3182fca5a8bb24103424bd7a3f8d70e/ja/browser/browser/protections.ftl#L56

> `Cryptominers use your system’s computing power to mine digital money. Cryptomining scripts drain your battery, slow down your computer, and can increase your energy bill.` (https://hg.mozilla.org/l10n/gecko-strings/file/default/browser/browser/protectionsPanel.ftl)
https://github.com/mozilla-japan/gecko-l10n/blob/f1bb25b8d3182fca5a8bb24103424bd7a3f8d70e/ja/browser/browser/protectionsPanel.ftl#L78

「電気代を増やさせる」という表現が日本語として不自然に聞こえます。検索してもFirefoxの例しか見当たりません。
また `your battery` の訳があなたのバッテリー/端末のバッテリー で割れていますが、後者の方が自然だと思います。

暗号通貨マイニングスクリプトは端末のバッテリーを消費し、コンピューターを遅くさせ、電気代を高くする可能性があります。

**Comment by hATrayflood** [comment]
ありがとうございます。変更しました。https://github.com/mozilla-japan/gecko-l10n/pull/310/commits/c14ef44761d08c0df6217873196291f8d796cdde

**Comment by hokonch** [comment]
2022-03-08 の v98.0 で修正。
