### ISSUE TITLE
Android 版 Firefox のプライベートブラウジング時のトラッキング保護オン/オフ説明の訳語

### ISSUE THREAD

**Issue by dskmori** [mozilla-japan/gecko-l10n#31]
https://github.com/mozilla-japan/gecko-l10n/blob/master/ja/mobile/android/base/android_strings.dtd#L201
現状は、**プライベートブラウジングが有効になりました** となっていますが、**プライベートブラウジングで有効になります** など、チェックボックスをオン/オフにした際にトラッキング保護の挙動が切り替わることを説明する言い回しに変更をした方がいいと思います。
[原文] (http://hg.mozilla.org/releases/mozilla-aurora/file/default/mobile/android/base/locales/en-US/android_strings.dtd#l221) も **Enabled in Private Browsing** なので、プライベートブラウジング自体が有効/無効になるとは言っていないと思います。

**Comment by kechol** [comment]
@dskmori こちらご指摘ありがとうございました！誤訳ですね。 f131c06 にて修正させて頂きました。
