### ISSUE TITLE
コンテキストメニューの翻訳の改善

### ISSUE THREAD

**Issue by surapunoyousei** [mozilla-japan/gecko-l10n#319]
Pref の後ろに隠されている機能なのでこの翻訳の提案はよくないものかもしれません。

`about:config` サイトで、`browser.search.separatePrivateDefault.ui.enabled` を`true`に切り替え、プライベートウインドウでの検索エンジンをほかのものに切り替えます。

何らかのテキストを選択し、コンテキストメニューを表示すると、「プライベートウインドウで `検索エンジン` を検索」と表示されます。

代替案として、「プライベートウインドウの `検索エンジン` で検索」のほうが良いかもしれません。変な指摘申し訳ありません。

![image](https://user-images.githubusercontent.com/73892113/170521366-8baf8824-90c4-491f-a57c-4d50c5942578.png)

**Comment by marsf** [comment]
ご報告ありがとうございます。誤訳ですね。

`contextMenuPrivateSearchOtherEngine = Search with %S in a Private Window`
https://github.com/mozilla-japan/gecko-l10n/blob/4ba77cfa48e7b292af15479349158ab711dcdaa0/ja/browser/chrome/browser/browser.properties#L20-L24

**Comment by surapunoyousei** [comment]
お役に立てていれば幸いです。

毎回の Firefox のアップデートに対応するためのローカライズ、本当にお疲れ様です！

また何かありましたら、再度報告致します。

**Comment by surapunoyousei** [comment]
お疲れ様です。訂正感謝します。
