### ISSUE TITLE
誤訳: 従来の JPEG ファイルにロスレス変形等のサポートが追加された画像ファイル形式

### ISSUE THREAD

**Issue by accanfx** [mozilla-japan/gecko-l10n#328]
**Translation**
https://github.com/mozilla-japan/gecko-l10n/blob/3f38ccfdde1400a1a47d6f9ebb081fb30daf3928/ja/toolkit/toolkit/featuregates/features.ftl#L21

**Original**
https://hg.mozilla.org/mozilla-central/file/tip/toolkit/locales/en-US/toolkit/featuregates/features.ftl#l21
> experimental-features-media-jxl-description = With this feature enabled, { -brand-short-name } supports the JPEG XL (JXL) format. This is an enhanced image file format that supports lossless transition from traditional JPEG files. See <a data-l10n-name="bugzilla">bug 1539075</a> for more details.

**My translation**
従来の JPEG ファイルからロスレスで移行できる改良された画像ファイル形式

**Comment by marsf** [comment]
ご報告ありがとうございます。Firefox 104.0 で修正されます。

https://github.com/mozilla-japan/gecko-l10n/pull/330/commits/f2a413dd858e2c4c37e56f527032fc6c80829f23

**Comment by marsf** [comment]
fixed close.
