### ISSUE TITLE
Fx44 以降における証明書エラー画面の UI 変更

### ISSUE THREAD

**Issue by hashedhyphen** [mozilla-japan/gecko-l10n#33]
現在リリースされている Fx33 と beta リリースの Fx44 では、証明書エラー画面の UI が大きく異なっていることに気付きました（上が Fx33、下が Fx44 以降）。

![fx2](https://cloud.githubusercontent.com/assets/13907611/12198936/8ea53d58-b657-11e5-903c-d090f43e92a6.png)

![fx](https://cloud.githubusercontent.com/assets/13907611/12198941/93b8799a-b657-11e5-9f86-81c52bdb041c.png)

ここで、新しい UI において未翻訳部分が出てしまっているのですが、どうやら [browser/chrome/overrides/appstrings.properties](https://github.com/mozilla-japan/gecko-l10n/blob/l10n-mozilla-44.0/ja/browser/chrome/overrides/appstrings.properties) が本家 mozilla-beta の [browser/locales/en-US/chrome/overrides/appstrings.properties](http://mxr.mozilla.org/mozilla-beta/source/browser/locales/en-US/chrome/overrides/appstrings.properties) とに違いが生じているようです。

残念ながら Mercurial との連携には明るくないのですが、まず何から始めればよいか教えていただけると助かります…

**Comment by marsf** [comment]
44.0 beta のローカライズは現時点でまだ完了してません。m(_ _)m
この週末には hATrayflood さんが作業してくれているはず。

Mercurial のリポジトリにコミットするには権限が必要です。
ローカライズに参加していただけるのであれば、この github 上のリポジトリにプルリクエストを送ってください。
もしくは、部分的な翻訳で一番簡単な方法がよければ、該当部分の翻訳をこの issue に直接コメントしてくださってもかまいません。こちらで取り込みます。

**Comment by hashedhyphen** [comment]
お返事ありがとうございます！
