### ISSUE TITLE
Firefox for Androidの「アプリでリンクを開く」について

### ISSUE THREAD

**Issue by Guest126** [mozilla-japan/gecko-l10n#333]
#287 に連なる話です。

### Firefox for Android

https://pontoon.mozilla.org/ja/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?string=242752

原文 "You can set %1$s to automatically open links in apps."
訳文「アプリ内のリンクを %1$sで自動的に開くように設定できます。」

正しくは「リンクをアプリで自動的に開くよう %1$s を設定できます。」といった訳になるのではないかと思います。"%1$s"にはブラウザ自身のアプリ名が入ります（アプリ名を入れる必要があるのかは疑問です）。

![Screenshot_1_Firefox_Nightly_105.0a1](https://user-images.githubusercontent.com/63546117/184493499-c911767e-2ca8-4b0e-b4d9-e0f34cb999ea.png)

### Focus for Android

https://pontoon.mozilla.org/ja/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?string=233377

原文 "Open links in apps"
訳文「アプリ内のリンクを開く」

正しくは「リンクをアプリで開く」だと思います。

![Screenshot_2_Firefox Focus_103.2.0](https://user-images.githubusercontent.com/63546117/184493841-87b1f58a-f6bd-48ef-a1c4-14418a696cc8.png)

###  訳文の統一性

「リンクをアプリで開く」(Open links in apps)「アプリで開く」(Open in apps)という言い回しですが、Firefoxそれ自身もアプリのひとつですから、この表記は混乱を招きます。英語では"apps"と複数形になっていることで暗に他のアプリを指していると察せるのかもしれませんが、日本語では「外部アプリ」「他のアプリ」「対応アプリ」などと言葉を補った方が良いと思います。

これは原文の時点でそうなのですが、同じFirefoxの中で「アプリ」「外部アプリ」「他のアプリ」という言い回しが混在しており、それぞれ同じものを指すのか違うのか非常に分かりにくいです。日本語訳だけでも統一して欲しいと思います。

**Comment by Guest126** [comment]
###  本件に関係しそうな文字列

#### 「アプリで開く」(Open in app)
https://pontoon.mozilla.org/ja/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?string=205441

→メニューから実行すると、対応アプリで現在のURLを開く

#### 「リンクをアプリで開く」(Open links in apps)
https://pontoon.mozilla.org/ja/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?string=206864
https://pontoon.mozilla.org/ja/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?string=233377

→設定メニューから有効にすると、自動的に対応アプリでリンクを開く

#### 「リンクを外部アプリで開く」(Open link in external app)
https://pontoon.mozilla.org/ja/firefox-for-android/mozilla-mobile/android-components/components/feature/contextmenu/src/main/res/values/strings.xml/?string=207327

→コンテキストメニューから実行すると、対応アプリでリンクを開く

#### 「他のアプリで開く…」(Open in…)
https://pontoon.mozilla.org/ja/firefox-for-android/mozilla-mobile/android-components/components/feature/app-links/src/main/res/values/strings.xml/?string=228295
https://pontoon.mozilla.org/ja/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?string=223919

→メニューから実行すると、対応アプリまたは他のブラウザアプリを選択して現在のURLを開く（focusでのみ確認、fenixでの呼び出し方法不明）

#### 「アプリで開く場合、その行動はプライベートにはなりません。」(Open in app? Your activity may no longer be private.)
https://pontoon.mozilla.org/ja/firefox-for-android/mozilla-mobile/android-components/components/feature/app-links/src/main/res/values/strings.xml/?string=199702

→カスタムURLスキームなどのリンクを踏んだ際のメッセージ

#### 「リンクを他のアプリで開く」(Open link in another app)
https://pontoon.mozilla.org/ja/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?string=223899

→呼び出し方法不明、[%1$s を離れてこのリンクを %2$s で開くことができます。](https://pontoon.mozilla.org/ja/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?string=223874)というメッセージのプロンプトのタイトル

### 余談

PontoonではXMLファイルを跨いだ全文検索ができないのでしょうか？ 仕方なく https://github.com/mozilla-l10n/android-l10n から全翻訳リソースをダウンロードしてgrepしてPontoonと照らし合わせているのですが、日本語リソースだけを対象に検索する良い方法があれば教えてください。

**Comment by marsf** [comment]
ご指摘ありがとうございます。
すべて、「外部アプリで開く」という表現にしました。
今日の締め切りに間に合えば、次のリリース版で修正されているはずです。

> PontoonではXMLファイルを跨いだ全文検索ができないのでしょうか？

Pontoon では、プロジェクトを跨いだ検索はできないようです。同じプロジェクトで複数の XML ファイルが使われている場合はプロジェクト全体から検索できます。

横断的に検索したい場合は、Transvision をご利用ください。
https://transvision.mozfr.org/?recherche=open+link&repo=android_l10n&sourcelocale=en-US&locale=ja&search_type=strings

**Comment by Guest126** [comment]
> すべて、「外部アプリで開く」という表現にしました。
> 今日の締め切りに間に合えば、次のリリース版で修正されているはずです。

対応ありがとうございます。

https://pontoon.mozilla.org/ja/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?string=223919

これだけ抜けていたので追加お願いします。

> 同じプロジェクトで複数の XML ファイルが使われている場合はプロジェクト全体から検索できます。

もう一度探したところ確かにできました！ パンくずリストから"All Resources"を選択すれば良かったのですね。

![Pontoon Screen Shot](https://user-images.githubusercontent.com/63546117/184564054-aefe2d49-1483-4764-88dc-78e780490529.png)

教えていただきありがとうございます。

**Comment by marsf** [comment]
> https://pontoon.mozilla.org/ja/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?string=223919
> 
> これだけ抜けていたので追加お願いします。

修正しました。

**Comment by Guest126** [comment]
ありがとうございます。すべて確認しました。
