### ISSUE TITLE
ドミネータ vs ドミネーター

### ISSUE THREAD

**Issue by makotokato** [mozilla-japan/gecko-l10n#336]
Related to https://github.com/mozilla-japan/gecko-l10n/issues/55

確かFirefoxの翻訳は長音で終わると思うんですが、"ドミネータ" は "ドミネーター" か "ドミネータ" のどちらが適切でしょうか？ (ドミネーターよりも適切な単語でもいいんですが)

devtoolsの翻訳なので、プライオリティは低いですが。

https://github.com/mozilla-japan/gecko-l10n/blame/4dce28b3c7c8b9c2e89eb6c94e09d7af7debbbba/ja/devtools/client/memory.properties#L123,L127

**Comment by marsf** [comment]
dominat-or なので「ドミネーター」ですね。
/devtools/client/memory.properties に [7 か所](https://transvision.mozfr.org/?recherche=dominator&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings)あります。

**Comment by makotokato** [comment]
CFG (Control Flow Graph) の文脈だと "支配" とか "支配ノード" という言葉が使われますが (Dominator Tree = 支配木)、イマイチピンと来ないんですよね

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/pull/341 修正しました。

**Comment by marsf** [comment]
fixed.
