### ISSUE TITLE
Permissionの訳語

### ISSUE THREAD

**Issue by hokonch** [mozilla-japan/gecko-l10n#337]
拡張機能やウェブサイトのPermissionについて、
現在Firefoxでは基本的に「許可設定」と[訳されていることが多い](https://transvision.mozfr.org/?recherche=permission&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings)のですが、「権限」でなるべく統一したほうがいいのではないかと思いました。

- Androidユーザーには「権限」は馴染みがある訳語で、同一のセキュリティ概念だと理解しやすい（ほかTwitterアプリなど）
- Chromeと用語統一されていると、拡張機能の翻訳等で迷わずに済む。
- よくある謳い文句のNo Permissionsなどの翻訳を念頭に 「許可設定なしで動作」「権限なしで動作」を比較すると、<br>前者は「特別な設定作業なくout-of-boxで動作する」といった意味にも聞こえる。
- Firefoxの文脈でも「権限」と訳されていることが散見（例：少数のFirefox文字列、TreeStyleTab、[SUMOの解説記事](https://support.mozilla.org/ja/kb/permission-request-messages-firefox-extensions)）

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/pull/342 変更しました。
初期の翻訳をそのまま今まで踏襲してきたに過ぎないので、これを機に他に合わせるのに賛成です。

**Comment by marsf** [comment]
[ja/browser/browser/pageInfo.ftl](https://github.com/mozilla-japan/gecko-l10n/pull/342/commits/20e50ada66ccf6d4e81ff2fa580448d03662859d#diff-b955696e8ea69bd29b328f71d23cd648d8aa585332f5ef35fc8f4b6943313a01)

ユーザー設定とアドオンの権限を混同しています。
区別すべきではありませんか。

**Comment by hokonch** [comment]
参考までに
Chrome では[サイトの設定 (Site settings)] → [権限 (Permissions)] という UI なのに対し
Firefox では Site settings なしで、[権限 (Permissions)] となってますね。 

Firefox としては2つのPermissionsを言葉の上では区別しないわけですが、
Chromeのようにサイトの設定というところを見出しにした方が分かりやすい可能性があるという話かなと思います。

**Comment by marsf** [comment]
言葉の上での区別ではなく、概念 (動作対象) が違うという話をしています。
サイト別設定は Firefox のユーザー環境設定であり、ユーザーがウェブサイトに「許可する設定」です。だから、「標準設定を使用する」というオプションがあります。
hokonch さんのおっしゃる権限は、ユーザーがアドオンに許可する「動作」で、個々の動作の変更はできません。

**Comment by marsf** [comment]
「サイト別設定」の権限は、あくまでもユーザー側にあり、サイト側に委ねるものではありません。

ここで改善したほうがよいのはアドオンの権限のことですよね。

**Comment by hokonch** [comment]
いまいちmarsfさんの主張を理解できたか自信がないのですが、どちらに権限という言葉を使っても自分は特に違和感はありません。
例えば、ただのhello worldプログラムを、
ユーザー「権限」という標準設定で実行するか、あるいは管理者「権限」で実行するかは、
プログラムの動作には関係なくユーザー側に委ねられるものですが、「権限」と表現しますよね。

とはいえ、権限と訳して分かりやすくなると思うのはアドオンの方で、
他は「同じ単語なのだから同じように訳すのが良いのでは？」というくらいの弱い理由しか持ち合わせていないので
アドオン関連の訳語だけの変更にすることにも特に反対はしません。

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/pull/342 サイト設定関連の変更を戻しました。

個人的には、拡張機能に対してであれサイトに対してであれ、ユーザーがある動作を許可するか拒否するかであって、そこに大きな違いはないと思います。
が、いざ「サイト権限」とすると、サイト側がある機能を使いたいと要求する場合と、ユーザー側がこの動作はやめてくれという場合が混ざっていて、それをまとめて「権限」とするのはやはり違和感ありますね。

**Comment by marsf** [comment]
> 例えば、ただのhello worldプログラムを、 ユーザー「権限」という標準設定で実行するか、あるいは管理者「権限」で実行するかは、 プログラムの動作には関係なくユーザー側に委ねられるものですが、「権限」と表現しますよね。

これは単純に実行権限を持っているだけであって、「ユーザー側 (使用者、人)」と「ユーザーアカウント (所有者、物)」を区別すれば、使用者が、管理者権限で実行するのか、所有者権限で実行するのかの違いです。OS や管理者アカウントから権限を委ねられているわけではありません。

> サイト側がある機能を使いたいと要求する場合と、ユーザー側がこの動作はやめてくれという場合が混ざっていて、それをまとめて「権限」とするのはやはり違和感ありますね。

[サイト別設定](https://support.mozilla.org/ja/kb/firefox-page-info-window)では、サイトがある機能を使いたいと要求しても、そのコントロール権限は常に使用者にあります。だから、サイトに使わせる機能を使用者が個別に設定できるようになっています。

一方でアドオンの場合、使用者が許可しているのはアドオンの所有している機能です。使うかどうかをアドオンが決定しますから、権限をアドオンに持たせる必要があります。

ということで区別できるでしょうか。

**Comment by hATrayflood** [comment]
今夜マージしようと思います。何かあればコメントください @hokonch @marsf

**Comment by hATrayflood** [comment]
マージしました。サイト別設定に関してさらに改善が必要なら、別issue立てましょう。
