### ISSUE TITLE
[v106] Colorways のローカライズ改善アイデアの募集

### ISSUE THREAD

**Issue by hokonch** [mozilla-japan/gecko-l10n#339]
https://github.com/mozilla-japan/gecko-l10n/blob/0e0754fefeb4a7be7f050e4ec8a40a903d188e22/ja/browser/browser/colorways.ftl#L5-L30
> すごく強引にやりました。。
>
> 文才ない自分にはどうにもならないので、改版募集しようと思います。

_Originally posted by @hATrayflood in https://github.com/mozilla-japan/gecko-l10n/pull/331#discussion_r945116708_

> colorways.ftl について、これで ok という意味ではないので忘れないうちに issue を立ててください。改善が必要です。
よろしくお願いします。

_Originally posted by @marsf in https://github.com/mozilla-japan/gecko-l10n/pull/331#discussion_r945407277_

----
ここから議論は一ヶ月以上放置されていましたが、
[Firefox Beta v106.0b1-candidates ビルド](https://download-installer.cdn.mozilla.net/pub/firefox/candidates/106.0b1-candidates/build1/)も出たことですし、
Mozilla の方のデザインはまず固まり、かつこのままだとリリース版に仮訳で突っ込みそうということで、Issue 立てます。

こういうキャッチコピーは、どういう方針で訳すのか決めるのがまず重要ですから
 `colorways.ftl`だけでなく、[現時点における Colorways 関連の文字列・英日対照（Transvision）](https://transvision.mozfr.org/?recherche=colorway&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings_entities)全体を見ながら
他のファイルも訳し直すことも考慮に入れつつ、アイデアを募るといいのではないかと思います。

**Comment by hokonch** [comment]
結構目立つところに表示されるということで、
リリース版ユーザーの人もイメージが掴めるようスクリーンショットです。

### インストール・アップグレード後の初回起動 (about:welcome)
![Colorways_Welcome](https://user-images.githubusercontent.com/113707818/191110587-cf6c3b87-322e-4da6-9b4a-94ce30147340.png)
### Firefox View (v106 の新機能)
![Colorways_FirefoxView](https://user-images.githubusercontent.com/113707818/191110572-d1982a07-7fcf-48e2-962d-74b194dbfec8.png)
### テーマ管理ページ (about:addons)
![Colorways_Themes](https://user-images.githubusercontent.com/113707818/191110582-9f77d5dd-3d1c-4f6e-9ae8-b546fab5d06e.png)
### Colorways の選択画面 (about:addons)
![Colorways_Themes_select](https://user-images.githubusercontent.com/113707818/191110586-79a97d47-285f-4c93-9d1c-792f4b573656.png)

**Comment by hokonch** [comment]
[Mozilla L10N ブログ](https://blog.mozilla.org/l10n/2022/07/29/l10n-report-july-2022-edition/) などに載せられている
Firefox View — Localization Note を転載します。
 なおブログには、Firefox View 版のl10nガイドラインも載っています。
[転載元 (Google Docs)](https://docs.google.com/document/d/e/2PACX-1vSW7tlZEHCM56m7oeq_OsPsI0IsVMxi0-xb6lRp8YgD_Wn7B19DmblpGpF35ZipvmazBQuc3Kd-JdjR/pub)

# Colorways: Localization Guidance

*Last update: August 17, 2022*

## Background

Starting with [Firefox version](https://support.mozilla.org/en-US/kb/find-what-version-firefox-you-are-using) 94, users can personalize their browsing experience with colorways.

Colorways change the look of the browser interface. Colorways are different from traditional themes — they color different parts of the user interface (the main chrome, menus/search dropdown, homepage background, and sidebar). And, they’re created in-house, usually in partnership with an industry color specialist. Each colorway has its own individual color characteristics. Their purpose is to give users a way to personalize their browser experience so it feels more unique to them.

1.  A colorway collection is a group of colorways that launch at the same time. It includes:Multiple colorways for users to select
2.  Multiple intensity variations on how the colorway effects the look and feel of the browser
3.  Limited time functionality. Colorways expire after a specified date.

### Vision

This feature is something users will want to engage with every time new colorways are introduced. They are not anticipated to replace themes, rather, to provide an alternative experience that’s exclusive to Firefox and generate excitement within the browser on a regular basis.

There is a possibility that as colorways adoption grows, we may grow the complexity of colorways options as well to include designer names, audio, or motion.

### Brand

The larger product strategy is to position Firefox as the personal browser. Colorways supports this strategy by empowering people to control their experience, right down to how the browser looks. Colorways are also enabled for a limited period of time, themed and created in collaboration with notable design experts, adding to their exclusivity. Because a colorway inspired Firefox reflects their personal preferences and passions, Firefox feels a little more like them with premier experiences like colorways.

Colorways fits alongside Firefox View and Firefox Suggest as part of a family of features that push the product into more personal and innovative territory.

### About the name: Colorways

‘Colorways’ was selected for several reasons:

- It’s an evocative metaphor that nods to function (this is something that impacts how your browser looks)
- It is connected to sneaker culture — the idea that a basic shoe can be personalized and unique when you change colors, leading to collectability and personal statements

The name should be used in sentence case: **colorway or colorways**, except when at the beginning of a sentence.

## Localization Guidance

**“Colorway” should be localized.** Note: If the English term works in a particular locale, that localization community might choose to use it and not localize the name.

In addition to the above context, please keep these things in mind when choosing a name in your language:

Consider how people say, write, and read the name by trying options in a sentence.

<table>
<tr>
<td>

Vibrant new \_\_\_\_\_\_\_ from Firefox. Available for a limited time. (plural)

Set a new \_\_\_\_\_\_\_\_ to make Firefox feel a little more like you. (singular)

Looking for your colorways? You can find them in “My \_\_\_\_\_\_\_ .” (plural)

Have you seen the new \_\_\_\_\_\_\_ collection in Firefox? They’re inspired by autumn colors in nature. (plural)

Play with the intensity of your \_\_\_\_\_\_\_\_ to find a look that’s as unique as you. (singular)

</td>
</tr>
</table>

| Term                            | Example                           | Localization Guidance                                                                                              |
|---------------------------------|-----------------------------------|--------------------------------------------------------------------------------------------------------------------|
| Names of individual colorways   | Foto, Cheers                      | DO localize\*<br>(Individual locales may choose<br>to NOT localize if an acceptable<br>translation isn’t possible) |
| Colorway variations / intensity | Soft, balanced, bold              | DO localize                                                                                                        |
| Colorway collection names       | Life in color, Independent voices | DO localize                                                                                                        |

### Independent Voices Names and Descriptions

If your language uses grammatical genders, ideally try to use an inclusive form, e.g. translate “dreamer” as “female and male dreamers”, or “dreamers” if that’s genderless.

The colorway name might be also used as an adjective. In these cases, it’s possible to rephrase the sentence, e.g. switching from “You are a Dreamer. You…” to “Dreamer: You…”.

**Comment by hokonch** [comment]
## 問題点
### l10n の方針について

1. Mozilla のメッセージをなるべくそのまま日本語にするか
2. Mozilla が打ち出している色を薄めるか。

現在の訳は後者の2の方針になっているように見えます。
`colorways.ftl`の翻訳などは原文とはほとんど一致しない作文ですし。
基本的にl10nは前者であるべきでしょうが、
個人的にもそうしたところで「日本の文化や色彩感覚的にあまりピンとこないのでは？」という感想はあるので、
l10n コミュニティがそういう路線で行くことに決めるならば後者もありかと思います。
この方針が明らかになってないと、「改版募集」に応えようにも応えられないのでまず定めるべきかなと。

### 現翻訳自体の問題について
方針2でいくとしても、現翻訳にはいくつか問題があります。
なお、方針1で行くなら、ほとんど訳し直しになるので、ここはどうでもよくなります。

1. **誤字**
https://github.com/mozilla-japan/gecko-l10n/blob/0e0754fefeb4a7be7f050e4ec8a40a903d188e22/ja/browser/browser/colorways.ftl#L21
s/こままでは/このままでは/

2.  **Intensity の誤訳**
いま「彩度」と訳されてますが、GIMPとかで彩度をいじってみたら全然違う色になることからわかるように誤訳でしょう。
どっちかといえば輝度ですね。専門用語的に訳すのではなく「強さ」とか「明るさ」とかのほうがいいと思いますが。

3. **macOS/Linux における表示崩れ**
文字列「インディペンデント・ボイス」の両端がイラストと重なって見えづらくなっています。

<img src="https://user-images.githubusercontent.com/113707818/191124083-9e35982e-1726-440d-85c9-7fd9e92eeb16.png" width="332px" alt="IndependentVoices_currentTranslation">

なお、方針2ではなくMozillaのメッセージをなるべく守る方針1のつもりでやってますが、
この箇所の自分の私訳はこんな感じです。

<img src="https://user-images.githubusercontent.com/113707818/191124946-be737cdb-dc89-4ff9-b803-595d7ed9d715.png" width="332px" alt="IndependentVoices_myTranslation">

4. **作文にしても単語のイメージとマッチしない**
アクティビストの説明が、「さあ、新天地へ向かおう！」になってますが、
活動家と聞いて新天地をイメージする人はいないのではないでしょうか。
また、エクスプレショニストやイノベーターの説明も同じくズレていると思います。

5.  **カタカナに頼りすぎ？**
これは、もしかしたら Mozilla の日本語l10n慣例に反するかもしれませんが
個人的には訳しにくいからといってそのままカタカナにしても、余計わかりにくくなるだけだと思います。
Expressionist→エクスプレショニスト、Bold→ボールド、など

**Comment by marsf** [comment]
ご提案ありがとうございます。m(_ _)m

予めお断りしておきますが、/browser 以下は browser リーダーの @hATrayflood さんの最終判断に依ります。現状の翻訳はたたき台としても改善しなければならないと思っていますので、どなたでも声を上げて進めてくださって結構です。

l10n の方針については、マーケティング的なこともあり、1. にすべきと思います。
> 1. Mozilla のメッセージをなるべくそのまま日本語にするか
> 2. Mozilla が打ち出している色を薄めるか。

加えて、日本語としての文化的な面にも関わらざるを得ない内容ですから、もし表現を変えたいのであれば、このキャンペーンの目的に沿って馴染みやすい訳文になると良いと思います。

> The larger product strategy is to position Firefox as the personal browser. Colorways supports this strategy by empowering people to control their experience, right down to how the browser looks.

**Comment by hokonch** [comment]
colorway 絡みのファイルだと、`/toolkit/toolkit/about/aboutAddons.ftl` だけは@marsf さんがリーダーのものに当たりますね。

### 気になるもの
#### @hATrayflood さん訳との表記ブレ1件
https://github.com/mozilla-japan/gecko-l10n/blob/8055c8bb332f6ed974ca60049859e1f9fa862997/ja/browser/browser/colorwaycloset.ftl#L7
https://github.com/mozilla-japan/gecko-l10n/blob/8055c8bb332f6ed974ca60049859e1f9fa862997/ja/toolkit/toolkit/about/aboutAddons.ftl#L302

#### colorway or colorways どう訳す？

現翻訳：「カラーテーマ」。
私の提案：日本語でも Colorway を用いる。ただしCは大文字・単数形に固定する。説明文の中では「テーマコレクション Colorway」のように補足を加える。

「カラーテーマ」は意味が明瞭という大きな利点があるとはいえ、Mozilla のブランド化の意図は伝わらず、ただのカラフルなテーマに聞こえるため。
適当な日本語に置き換えることは難しく、l10nガイダンスにもl10nしない選択も可能とあるのでそのまま。また「カラーウェイ」よりは「Colorway」のほうが意味が理解しやすい。

Cを大文字に固定：そもそもcolorwayという単語が存在しない日本語では固有名詞的に訳すのが妥当。
単数形に固定：日本語に単複の区別はないのでどちらかに統一したい。複数形も多様性のニュアンスが出て良いかもしれないが、そうすると「Colorways を変更(原文：Change Colorway)」には少しだけ違和感。どちらでもいいけど。

**Comment by hokonch** [comment]
colorway関連全体を自分訳で置き換えた、私家版 langpack 置いておきます。
[langpack-ja-custom@firefox.mozilla.org.zip](https://github.com/mozilla-japan/gecko-l10n/files/9611620/langpack-ja-custom%40firefox.mozilla.org.zip)

[AMOからダウンロードした](https://addons.mozilla.org/ja/firefox/addon/japanese-language-pack-1/versions/)言語パックを開いて、colorway関連の文字列と`ja`を手で書き換えてzipしただけで、正式な方法じゃないかもしれませんが
1. Firefox Developer Edition または Nightly (、あるいはBetaを改造)
2. 拡張子をxpiに変更
3. `extensions.langpacks.signatures.required` を `false`
4. intl.locale.requested に`ja-custom`

で試せるはず。
参考：[未署名のアドオンを使いたい場合 (上級ユーザー向け)](https://support.mozilla.org/ja/kb/add-on-signing-in-firefox#w_wei-shu-ming-noadoonwoshi-itaichang-he-shang-ji-yuzaxiang-ke)

ついでに、マズい誤訳も1件見つけたので前のコメントに追記

**Comment by hokonch** [comment]
モバイル版でも壁紙で類似の企画がなされていたようですね。
訳を統一するのが良いと思われる文字列をまとめておきます。

| browser                                                                              | toolkit                                                                           | Android / iOS                          |
|--------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------|----------------------------------------|
| colorway または colorways                                                            | colorway または  colorways                                                        |                                        |
| Independent Voices                                                                   |                                                                                   | The new Independent Voices collection. |
|                                                                                      |                                                                                   |                                        |
| Vibrant new colorways. Available for a limited time.                                 | Vibrant new colorways from { -brand-product-name }. Available for a limited time. | Limited Edition                        |
| Expires { DATETIME($expiryDate, month: "long", day: "numeric") }                     | Expires { DATETIME($expiryDate, month: "long", day: "numeric") }                  |                                        |
| Add a splash of color                                                                |                                                                                   | Try a splash of color                  |
| Choose the shade that speaks to you with colorways. Only in { -brand-product-name }. |                                                                                   | Choose a wallpaper that speaks to you. |

現時点で訳が別れているのは

| @hATrayflood 担当分                                                              | @marsf 担当分                                                     |
|----------------------------------------------------------------------------------|-------------------------------------------------------------------|
| インディペンデント・ボイス                                                       | 新しい Independent Voices コレクションです。                      |
| { DATETIME($expiryDate, month: "long", day: "numeric") } まで                    | 有効期限 { DATETIME($expiryDate, month: "long", day: "numeric") } |
| カラーテーマで自分に合う色合いを選びましょう。{ -brand-product-name } だけです。 | あなたに語りかける壁紙を選んでください。                          |

**Comment by hokonch** [comment]
各colorway名の説明について

> 各テーマの印象をなんとなく説明しているにすぎず、ユーザーに読んでもらわないと困る内容でもないように思うのですが、どうでしょうか。

_Originally posted by @hATrayflood in https://github.com/mozilla-japan/gecko-l10n/pull/331#discussion_r944373177_

自分の勝手訳（頻繁に編集してます）では

・読み手に自信や意欲を与え (inspire) ようとする文章であること
・多数派に左右されない自立した（independent）意思や態度を表明し (voices)、周囲の人間を変えていく(change culture) 、といったテーマを意識すること。
・colorway名 (Playmaker、Expressionist…) は日本語にしづらいので、そのままにする代わりに説明の方に単語の意味を組み込むこと。

この3点を意識しています。

**Comment by hATrayflood** [comment]
ご提案ありがとうございます。pullreqになってなかったので、こちらでpullreqにしました。
pullreq: https://github.com/mozilla-japan/gecko-l10n/pull/343
まずは、変更内容がこれで間違いないか確認をお願いしたいです。

基本的にはご提案いただいた変更案を採用したいと思います。

colorwayやPlaymakerなどをカタカナにするしないについてですが、以下に該当するものはカタカナにせず英語のままとしています。
- 一般によく知られた固有名詞
- 「Mozilla」や「Firefox」のようなブランドや商標

colorwayについては、browser/branding/official/brand.ftl に入ってなかったのでブランドではないと思ったのですが、ご指摘のドキュメントにある通りブランド化の意向があるので、英語に戻す方向でよいと思います。
Playmakerなどのcolorway名については固有名詞ではなく、検索すればすぐ出てくる単語 (Expressionistはちょっと怪しいですが) ではあるものの、日本語にしづらい単語ということもあってカタカナにしてました。
無理にカタカナにせず、Playmakerなどの英語に戻すのもアリだと思います。
@hokonch

**Comment by hokonch** [comment]
> まずは、変更内容がこれで間違いないか確認をお願いしたいです。
@marsf さん担当分の`/toolkit/toolkit/about/aboutAddons.ftl` はいいとして、
- `/browser/browser/appExtensionFields.ftl`
- `browser/browser/featureCallout.ftl`

が抜けています。
> ブランドではないと思ったのですが、ご指摘のドキュメントにある通りブランド化の意向があるので

Mozilla としても一般名詞なのか固有名詞なのかどっちつかずで不統一の風に見えますね (センテンスケースと言いつつSUMOで守ってなかったり)。Colorwayに相当する単語が日本語にない以上はどちらかに寄せる必要があって、自分はブランド方面に大きく寄せました。

**Comment by hATrayflood** [comment]
ありがとうございます。更新しました。https://github.com/mozilla-japan/gecko-l10n/pull/343

> Mozilla としても一般名詞なのか固有名詞なのかどっちつかずで不統一の風に見えますね (センテンスケースと言いつつSUMOで守ってなかったり)。Colorwayに相当する単語が日本語にない以上はどちらかに寄せる必要があって、自分はブランド方面に大きく寄せました。

browser/browser/branding/brandings.ftl にもブランドと定義される語句があるんですが、ここにもやはりないですね。
以前はこれらの語句も一部は各ファイルに直接書かれてたことがあった気がします。ブランドかどうか見分けるのはちょっと大変ですね。

**Comment by hATrayflood** [comment]
今夜マージしようと思います。何かあればコメントください @hokonch @marsf

**Comment by hokonch** [comment]
@marsf 特にこの文字列は重点的にレビューしていただきたいです。PRの訳かmarsfさんの訳かどちらかに合わせる必要があると思います。
自分としては「カラーテーマ」よりは、ブランド色強めに“Colorway”に。
その路線で“Vibrant new colorways. Available for a limited time.” も自訳の方にすることを推しますが
それ以外はとくにどちらでもいいかなというくらい

| browser                                                                              | toolkit                                                                           | Android / iOS                          |
|--------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------|----------------------------------------|
| colorway または colorways                                                            | colorway または  colorways                                                        |                                        |
| Independent Voices                                                                   |                                                                                   | The new Independent Voices collection. |
|                                                                                      |                                                                                   |                                        |
| Vibrant new colorways. Available for a limited time.                                 | Vibrant new colorways from { -brand-product-name }. Available for a limited time. |                                        |
| Expires { DATETIME($expiryDate, month: "long", day: "numeric") }                     | Expires { DATETIME($expiryDate, month: "long", day: "numeric") }                  |                                        |
| Add a splash of color                                                                |                                                                                   | Try a splash of color                  |
| Choose the shade that speaks to you with colorways. Only in { -brand-product-name }. |                                                                                   | Choose a wallpaper that speaks to you. |


| https://github.com/mozilla-japan/gecko-l10n/pull/343                                                              | @marsf 担当分                                                     |
|----------------------------------------------------------------------------------|-------------------------------------------------------------------|
| Colorway                                                       | カラーテーマ                      |
| 揺るぎない声                                                      | 新しい Independent Voices コレクションです。                      |
| 鮮やかで刺激的なテーマコレクション Colorway の新作が期間限定で登場。                                                      | { -brand-product-name } の新しいカラーテーマが期間限定で利用できます。                     |
| { DATETIME($expiryDate, month: "long", day: "numeric") } まで                    | 有効期限 { DATETIME($expiryDate, month: "long", day: "numeric") } |
| { -brand-product-name } だけの Colorway であなたに響く色を選びましょう。 | あなたに語りかける壁紙を選んでください。                          |

**Comment by marsf** [comment]
"Colorway" の用語については toolkit も一緒に統一してほしいです。そもそも browser に合わせてるので。
Toolkit の `Vibrant new colorways ...` と `Expires ...` も同じ。

Firefox for Android / iOS の `Choose a wallpaper that speaks to you.` は原文も仕組みもデスクトップ版とは違うものです。

**Comment by hokonch** [comment]
> Firefox for Android / iOS の `Choose a wallpaper that speaks to you. `は原文も仕組みもデスクトップ版とは違うものです。

そこは文章なのでまあどうでもいいところではありますが、
`Independent Voices` の方は合わせたほうがいいんじゃないですか

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/pull/343/commits/d38487843893ce2de0969686ed3734686272ebfc toolkit更新しました。
`新しい Independent Voices コレクションです。` と `あなたに語りかける壁紙を選んでください。` が見つからなかったのですが、どこにありましたでしょうか？ @hokonch

**Comment by hokonch** [comment]
わかりにくい書き方ですみません。その２つはFirefox for Android/iOSの文字列です。
モバイル版Firefoxではテーマ機能はないのでColorwayという形ではブランド化されていないのですが
Independent Voicesという共通した名前の限定コレクションを用意して、壁紙機能でデスクトップ版との連動企画が行われています。

**Comment by hATrayflood** [comment]
ああ、なるほど。ということは、このリポジトリにはないってことですね。マージします。

**Comment by hokonch** [comment]
@hATrayflood @marsf 
まだ修正可能なのか良く分かりませんが、念の為こちらでも通知しておきます
https://github.com/mozilla-japan/gecko-l10n/pull/343#pullrequestreview-1135309015
