### ISSUE TITLE
良い or よい

### ISSUE THREAD

**Issue by hokonch** [mozilla-japan/gecko-l10n#340]
記者ハンドブック等がどうなってるかは知りませんが、表記ブレがあるようなのでとりあえず
「よりよい」でgrepして気づきました。
- [よい (Transvision)](https://transvision.mozfr.org/?recherche=%E3%82%88%E3%81%84&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings)
- [良い (Transvision)](https://transvision.mozfr.org/?recherche=%E8%89%AF%E3%81%84&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings)

**Comment by hATrayflood** [comment]
ひらがなが続くと読みづらい場合もあるため、あえて漢字にしていることがあります。
が、すべての箇所がそのような規則で統一されてるか？については見直しが必要かもしれません。
そういった配慮はいったん忘れてどちらかに統一するという選択肢もアリです。

もし修正が必要なら、間に合えば106、遅くとも107で入れたいと思います。

**Comment by hokonch** [comment]
紛失中なので記者ハンドブックは確認せず、ただ自分の感覚として述べれば
口語で、「いい」と発音するのはひらがな／「よい」とはっきり発音するのは漢字、のように自分は使い分けている気がします。その文脈で「よりよい」は漢字かなと。

**Comment by marsf** [comment]
記者ハンドブック第 13 版では、3 種類の記載があります。

よい
　＝（好い）→良い〔一般用語〕
　　　頭が良い、感じが良い、気分が良い...
　＝善い〔特別用語。徳性〕
　　　気性が善い、行儀が善い、善い行い...
　＝よい〔補助用言、接尾語など〕
　　　∼してよい、住みよい、それでよい、もうよい

日本語だけでなく、原文の英語とも照らし合わせる必要があります。

**Comment by dynamis** [comment]
mar さんが引用してくださってるとおり、少なくとも昔は補助用言、接尾語などはひらがな表記、better を表す一般用語は漢字という使い分けが l10n や mozilla.jp 表記ルールでした (読みやすさ視点での切替というのは基本していなかった)。

従ってそのルールに違反している箇所があるなら修正だがそうでなければ表記揺れには該当しないものであり wontfix になると思います。

**Comment by marsf** [comment]
[browser-116.0](https://github.com/mozilla-japan/gecko-l10n/commit/e578d8d62075b9ab53a72f64428de8fa60243043) で、以下の表現を修正済みです。

- よりよい健全なインターネット
- よりよいユーザー体験
→ より良い

いま残っているのは、以下の 3 件のみ。
- 再読み込みするとよいでしょう。
- 報告するのもよいですが
- 報告するのもよいでしょう。

他に無ければ修正済みということで close しましょう。
