### ISSUE TITLE
Phone の訳語

### ISSUE THREAD

**Issue by hokonch** [mozilla-japan/gecko-l10n#345]
「携帯電話 / 携帯端末」と訳されているようですが（[Transvision](https://transvision.mozfr.org/?recherche=Phone&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings&entire_words=entire_words)）、
今となってはかなり死語に近くなっていますし、「スマホ」でいいのではないかと思います。

**Comment by hATrayflood** [comment]
公式ではない略語は使わない、というのと「スマホ」自体が略語してもおかしいので、もし変えるなら「スマートフォン」ではないかと思います。

**Comment by hokonch** [comment]
> 「スマホ」自体が略語してもおかしい

「スマフォ」であるべきという意味でしょうか？
そうは言っても今では広辞苑も「スマホ」で立項するくらいには定着した表記ですが。

「スマートフォン」だとUI翻訳では長すぎて、表示崩れの一因になってしまうことを危惧します。
原文もsmartphone の略語としてphoneを使っているとも解釈できませんか？

**Comment by marsf** [comment]
現状、「phone or tablet」の場合は「携帯電話やタブレット」、「phone」単独の場合は「携帯端末」に翻訳されているようです。
「携帯端末」は携帯電話とタブレットを含む総称です。

以下、Transvision から:
/browser/browser/aboutPrivateBrowsing.ftl
	about-private-browsing-focus-promo-header-b
> Take private browsing to your phone
> あなたの携帯端末にプライベートブラウジングを

/browser/browser/featureCallout.ftl
	callout-firefox-view-tab-pickup-subtitle
> Quickly grab open tabs from your phone and open them here for maximum flow.
> 携帯端末から開いたタブを素早く取り出して、最大限ここに開くことができます。

/browser/browser/firefoxView.ftl
	firefoxview-mobile-confirmation-description 
> Now you can grab your { -brand-product-name } tabs from your tablet or phone.
> 携帯電話やタブレットから { -brand-product-name } のタブを取り出せるようになりました。

/browser/browser/firefoxView.ftl
	firefoxview-mobile-promo-header 
> Grab tabs from your phone or tablet
> 携帯電話やタブレットからタブを取り出す

/browser/browser/firefoxView.ftl
	firefoxview-tabpickup-adddevice-header 
> Sync { -brand-product-name } on your phone or tablet
> 携帯電話やタブレットの { -brand-product-name } と同期

/browser/browser/firefoxView.ftl
	firefoxview-tabpickup-step-signin-description 
> To grab your phone tabs here, first sign in or create an account.
> ここから携帯端末のタブを取り出すには、最初にログインするかアカウントを作成します。

/browser/browser/newtab/onboarding.ftl
	mr2022-onboarding-mobile-download-title 
> Hop from laptop to phone and back again
> ノート PC から**携帯電話**に戻す

/browser/browser/preferences/fxaPairDevice.ftl
	fxa-qrcode-pair-title 
> Sync { -brand-product-name } on your phone or tablet
> 携帯電話やタブレットの { -brand-product-name } と同期

/devtools/client/aboutdebugging.ftl
	about-debugging-browser-version-too-old-fennec 
> This version of Firefox cannot debug Firefox for Android (68). We recommend installing Firefox for Android Nightly on your phone for testing. <a>More details</a>
> このバージョンの Firefox は Android 版 Firefox (68) をデバッグできません。**携帯電話**でのテストには Android 版 Firefox Nightly のインストールをお勧めします。<a>詳細</a>

/devtools/client/toolbox.properties
	toolbox.androidElementPicker.mac.tooltip 
> Pick an element from the Android phone (%1$S or %2$S)
> Android 端末から要素を選択 (%1$S または %2$S)

　

例外は onboarding.ftl と aboutdebugging.ftl だけですね (太字にしました)。まず、この 2 か所を「携帯端末」にそろえたほうが良いと思います。

携帯電話でのテストには～
→ 携帯端末でのテストには～

その上で、「携帯電話」を「スマートフォン」に変える感じでしょうか。
firefoxView.ftl (4か所)、fxaPairDevice.ftl (1か所)

**Comment by marsf** [comment]
> 例外は onboarding.ftl と aboutdebugging.ftl だけですね (太字にしました)。まず、この 2 か所を「携帯端末」にそろえたほうが良いと思います。

修正済み。

> firefoxView.ftl (4か所)、fxaPairDevice.ftl (1か所)

「スマートフォン」に置き換える。

**Comment by marsf** [comment]
close.
