### ISSUE TITLE
`about:welcome` と `about:firefoxview` のl10n改善

### ISSUE THREAD

**Issue by hokonch** [mozilla-japan/gecko-l10n#346]
誤訳もありますし、Betaユーザーの不評も1件見つかったので
今の訳の気になるところをコメントしていきます。

**Comment by hokonch** [comment]
https://github.com/mozilla-japan/gecko-l10n/pull/331#pullrequestreview-1131135709
https://github.com/mozilla-japan/gecko-l10n/pull/335#pullrequestreview-1130145567
https://github.com/mozilla-japan/gecko-l10n/pull/335#pullrequestreview-1130884932

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/pull/348 ありがとうございます。更新しました。
携帯端末 → スマホについては、#345 で話題に上がっているので、そちらで対応したいと思います。

**Comment by hATrayflood** [comment]
今夜マージしようと思います。何かあればコメントください @hokonch @marsf

**Comment by hATrayflood** [comment]
マージしました。ご提案ありがとうございました。

**Comment by hokonch** [comment]
@hATrayflood 
一件追加です。
https://github.com/mozilla-japan/gecko-l10n/pull/331#discussion_r990750264

**Comment by hokonch** [comment]
https://github.com/mozilla-japan/gecko-l10n/pull/349#discussion_r990751320
