### ISSUE TITLE
`webextPerms.learnMore2` の訳はミスリーディング？

### ISSUE THREAD

**Issue by hokonch** [mozilla-japan/gecko-l10n#352]
https://github.com/mozilla-japan/gecko-l10n/blob/c8c39e9951f1165513cf90ad2e1c2227d62f745e/ja/browser/chrome/browser/browser.properties#L77

根本的にはFirefox本体の問題ですが、不評ツイートがあり、l10nで多少は改善できるところだと思われるので、一応登録しておきます。
https://twitter.com/pleist/status/1578377044840235010

ツイートの内容は
- アドオンインストール前の権限警告パネルで、権限を必要とする具体的なサイトが省略される。
- 「詳細」を押すと、省略が解除されると期待するがそうはならず、[SUMO](https://support.mozilla.org/kb/permission-request-messages-firefox-extensions)に飛ぶ

と整理できるでしょう。実際Chromeはツイート主の期待通りの動作になっています。
Chromeは原文は`Show Details`、Firefoxは `Learn more`で、英語版ならこのような誤解は生じないと思われるのですが
日本語版だと、どちらも`詳細`となっていて区別ができません。

![Screenshot-chrome1](https://user-images.githubusercontent.com/113707818/194759807-2b481709-48dc-4b76-906f-9f3207117e8f.png)
![Screenshot-chrome2](https://user-images.githubusercontent.com/113707818/194759809-4be689e6-b2da-4697-b14c-3732eecf6286.png)
![Screenshot-firefox](https://user-images.githubusercontent.com/113707818/194762901-6e98d5c2-4f00-43bb-9202-199f63480b3b.png)

**Comment by hATrayflood** [comment]
となると「ヘルプを表示」でしょうか。

**Comment by marsf** [comment]
Thunderbird では「詳細情報」としています。
https://transvision.mozfr.org/?recherche=webextPerms.learnMore&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=entities

**Comment by marsf** [comment]
close.
