### ISSUE TITLE
雑多な小ミス修正・小改善案

### ISSUE THREAD

**Issue by hokonch** [mozilla-japan/gecko-l10n#353]
1. https://github.com/mozilla-japan/gecko-l10n/blob/a59f942e4497e3110b6b55837c1bef3be708e45a/ja/browser/browser/featureCallout.ftl#L14
「掴」は常用漢字外だったため
`タブをつかんで端末の壁を飛び越える`
--- 
2. https://github.com/mozilla-japan/gecko-l10n/blob/a59f942e4497e3110b6b55837c1bef3be708e45a/ja/browser/browser/firefoxView.ftl#L25
2文字削るとテストしたWindows10環境では1行に収まるため
`携帯端末のタブをここで取り出すには、まずはログインするかアカウントを作成しましょう。 `
---
3. https://github.com/mozilla-japan/gecko-l10n/blob/a59f942e4497e3110b6b55837c1bef3be708e45a/ja/browser/browser/firefoxView.ftl#L29
`Learn how`という原文が3, 4の2箇所に分かれていることに改訳提案したときは気づいていなかった。訳を統一すべきだが見直したところ、元の「仕組み」も「使い方」もしっくりこなかったため、より単純に2文字で
`詳細`
---
4. https://github.com/mozilla-japan/gecko-l10n/blob/a59f942e4497e3110b6b55837c1bef3be708e45a/ja/browser/browser/firefoxView.ftl#L33
3 を参照。
`詳細`
---
5. https://github.com/mozilla-japan/gecko-l10n/blob/a59f942e4497e3110b6b55837c1bef3be708e45a/ja/browser/browser/newtab/asrouter.ftl#L166
Accessibleはそのまま「アクセシブル」の方が訳語として定着、また形容詞が連続しすぎていて不自然、6と訳を合わせて
`オープンでアクセシブルな、すべての人にとってのより良いインターネット `
---
6. https://github.com/mozilla-japan/gecko-l10n/blob/a59f942e4497e3110b6b55837c1bef3be708e45a/ja/browser/browser/newtab/onboarding.ftl#L385
「すべての人にとってより良いインターネット」は自分にとって不自然に聞こえる。少なくとも間に「の」が必要
`すべての人にとってのより良いインターネット`
---
7. https://github.com/mozilla-japan/gecko-l10n/blob/a59f942e4497e3110b6b55837c1bef3be708e45a/ja/browser/browser/preferences/fxaPairDevice.ftl#L10
半角空白を3箇所抜けている。
`3. <b>メニュー</b> (<img data-l10n-name="ios-menu-icon"/> または <img data-l10n-name="android-menu-icon"/>) を開いて、<img data-l10n-name="settings-icon"/> <b>設定</b> をタップし、<b>Sync を有効化</b> を選択します `
---
8. https://github.com/mozilla-japan/gecko-l10n/blob/a59f942e4497e3110b6b55837c1bef3be708e45a/ja/browser/browser/preferences/fxaPairDevice.ftl#L18
「を」が抜けている。半角空白が２箇所抜けている。
`2. <strong>メニュー</strong> (iOS では <img data-l10n-name="ios-menu-icon"/>、Android では <img data-l10n-name="android-menu-icon"/>) を開いて、<strong>ログインして同期</strong> をタップします `
---
9. https://github.com/mozilla-japan/gecko-l10n/blob/a59f942e4497e3110b6b55837c1bef3be708e45a/ja/browser/browser/preferences/moreFromMozilla.ftl#L20
6を参照
`すべての人にとってのより良いインターネット`

**Comment by hATrayflood** [comment]
修正しました https://github.com/mozilla-japan/gecko-l10n/pull/356/commits/1d01587b95ee5a71fa101af1632e38fa64bafc27
