### ISSUE TITLE
about:Telemetry の「延長記録」

### ISSUE THREAD

**Issue by dskmori** [mozilla-japan/gecko-l10n#36]
` gecko-l10n/ja/toolkit/chrome/global/aboutTelemetry.dtd`
L19 - L25 あたり。

> ```
> <!ENTITY aboutTelemetry.extendedRecordingEnabled "
>   Telemetry の延長記録は<span>有効</span>です。
> ">
> 
> <!ENTITY aboutTelemetry.extendedRecordingDisabled "
>   Telemetry の延長記録は<span>無効</span>です。
> ">
> ```

_延長_ではなく、**拡張** または **追加** あたりの訳語が適当なのでは？

**Comment by marsf** [comment]
ご提案ありがとうございます。

https://hg.mozilla.org/mozilla-central/file/e705022687ad/toolkit/components/telemetry/TelemetrySession.jsm
ソースコードを "Telemetry.canRecordExtended" で検索すると、このフラグで Telemetry に追加される項目がいくつか引っかかりました。主に、メモリまわりのものが多いようです。
「Telemetry の記録拡張」でどうでしょうか？

**Comment by dskmori** [comment]
記録拡張でも、拡張記録でも、おまかせします。

**Comment by marsf** [comment]
45.0 beta で修正しました。
「延長記録」→「記録拡張」
