### ISSUE TITLE
comm-l10n/ja updates

### ISSUE THREAD

**Issue by marsf** [mozilla-japan/gecko-l10n#360]
Japanese l10n resources (ja / ja-JP-mac) has been converted from same source.  I'll make patches to update [comm-l10n](https://hg.mozilla.org/projects/comm-l10n/file/tip)/ja, ja-JP-mac and drop them here.

Targeted top folders of the patch are:
  /calendar
  /chat
  /mail
  /suite

**Comment by marsf** [comment]
@jfx2006
Hi, I've made the first patches for comm-l10n/ja, ja-JP-mac repo.
Please tell me, if there is something wrong.

[comm-l10n-ja_diff20221203.zip](https://github.com/mozilla-japan/gecko-l10n/files/10145936/comm-l10n-ja_diff20221203.zip)

from:
108.0+: sync mail, suite with en-US rev9328:a30fe40439de (2022-11-28)  (https://github.com/mozilla-japan/gecko-l10n/pull/364)

**Comment by jfx2006** [comment]
Thanks!
Pushed: https://hg.mozilla.org/projects/comm-l10n/rev/4e416ee82adda8dac605f4857d32f361d42d346a

There was no commit header in those diff files, so I rebuilt it from what is in Git. If you're able to include it next time, it will help with attribution.

**Comment by marsf** [comment]
> There was no commit header in those diff files, so I rebuilt it from what is in Git. If you're able to include it next time, it will help with attribution.

Our converted resources (sources of the patch) are not on any repository.  Can you please tell me any format reference or a template of commit header?

**Comment by jfx2006** [comment]
Something like this should be sufficient.
```
# HG changeset patch
# User Masahiko Imanaka <chimantaea_mirabilis@yahoo.co.jp>
# Date Fri Dec 02 22:41:44 2022 +0900
108.0+: sync mail, suite with en-US rev9328:a30fe40439de (2022-11-28)

```

The "108.0+: " is the commit message, in this case I used the one from the referenced pull request. There is a single blank line after the commit message before the beginning of the diff.

**Comment by marsf** [comment]
Thank you!
I'll add the header next time.

**Comment by marsf** [comment]
@jfx2006
Hi, this is for [109.0 patch](https://github.com/mozilla-japan/gecko-l10n/pull/371) of comm-l10n/ja, ja-JP-mac.

[comm-l10n-ja_diff20230107.zip](https://github.com/mozilla-japan/gecko-l10n/files/10366431/comm-l10n-ja_diff20230107.zip)

* Added the header.
* Unified ja and ja-JP-mac diffs.
* Includes another fixes.

Thanks.

**Comment by marsf** [comment]
@jfx2006 Hi, this is for 110.0 patch of comm-l10n/ja, ja-JP-mac. It includes all current updates.

[comm-l10n-ja_diff20230204.zip](https://github.com/mozilla-japan/gecko-l10n/files/10608424/comm-l10n-ja_diff20230204.zip)

Thanks.

**Comment by jfx2006** [comment]
> @jfx2006 Hi, this is for 110.0 patch of comm-l10n/ja, ja-JP-mac. It includes all current updates.
> 
> [comm-l10n-ja_diff20230204.zip](https://github.com/mozilla-japan/gecko-l10n/files/10608424/comm-l10n-ja_diff20230204.zip)
> 
> Thanks.

Applied. Thanks!

**Comment by marsf** [comment]
@jfx2006 Hi, this is for 111.0 patch of comm-l10n/ja, ja-JP-mac.
Thanks.

[comm-l10n-ja_diff20230305.zip](https://github.com/mozilla-japan/gecko-l10n/files/10890691/comm-l10n-ja_diff20230305.zip)

**Comment by marsf** [comment]
@jfx2006 Hi, this is for 112.0 patch of comm-l10n/ja, ja-JP-mac.
This patch includes previous 111.0, because it has a conflict and not applied yet.
[comm-l10n-ja_diff20230327.zip](https://github.com/mozilla-japan/gecko-l10n/files/11074363/comm-l10n-ja_diff20230327.zip)

Thanks.

**Comment by jfx2006** [comment]
Applied.
I do apologize for missing the previous update, I was out on PTO due to a family emergency and missed the notification in my inbox when I returned.

> @jfx2006 Hi, this is for 112.0 patch of comm-l10n/ja, ja-JP-mac. This patch includes previous 111.0, because it has a conflict and not applied yet. [comm-l10n-ja_diff20230327.zip](https://github.com/mozilla-japan/gecko-l10n/files/11074363/comm-l10n-ja_diff20230327.zip)
> 
> Thanks.

**Comment by jfx2006** [comment]
[Dan Darnell](https://github.com/dandarnell) is my co-worker and will be subscribing to this issue as well so he will get future notifications to prevent updates getting missed in the future.

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 113.0 patch of comm-l10n/ja, ja-JP-mac.
[comm-l10n-ja_diff20230430.zip](https://github.com/mozilla-japan/gecko-l10n/files/11365355/comm-l10n-ja_diff20230430.zip)

It includes 2 patches. Please apply them in this order.
1. comm-l10n-ja_diff20230413_cai.diff
2. comm-l10n-ja_diff20230430.diff

Thanks.

**Comment by jfx2006** [comment]
I had some difficulty importing due to migrations that ran on the aboutDialog.{dtd.ftl} files on 2023-04-27. This is how I resolved it:
- imported patch 1 dated 2023-04-13 on top of the last commit in the monorepo prior to the string migrations {a}
- rebased {a} onto the repo head {b}
- imported patch 2 dated 2023-04-30 onto the same repo head {c} 
- rebased {c} onto {b}

The end result is that the patches are both applied, and it appears that everything merged correctly.

These are my resulting sha256 checksums;
```
a47440ca2ac9c7d056d9f5b20afa79cbdea576493aaddc8bca3f1e00fd58daa7  ./ja/mail/messenger/aboutDialog.ftl
b25b8d6f6bb98e3a473e623d3576386f9800f0d206546d6c779d3358be815057  ./ja/mail/chrome/messenger/aboutDialog.dtd
a47440ca2ac9c7d056d9f5b20afa79cbdea576493aaddc8bca3f1e00fd58daa7  ./ja-JP-mac/mail/messenger/aboutDialog.ftl
b25b8d6f6bb98e3a473e623d3576386f9800f0d206546d6c779d3358be815057  ./ja-JP-mac/mail/chrome/messenger/aboutDialog.dtd
```

Please let me know if corrections are needed.

**Comment by marsf** [comment]
OK, no probrem. Thank you so much.

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 114.0 patch of comm-l10n/ja, ja-JP-mac.

[comm-l10n-ja_diff20230529.zip](https://github.com/mozilla-japan/gecko-l10n/files/11588339/comm-l10n-ja_diff20230529.zip)

Thanks.

**Comment by jfx2006** [comment]
> [comm-l10n-ja_diff20230529.zip](https://github.com/mozilla-japan/gecko-l10n/files/11588339/comm-l10n-ja_diff20230529.zip)

Done. https://hg.mozilla.org/projects/comm-l10n/rev/2ea56853c61417d29bb840e21ac0a1a01fb9c228

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 115.0 patch of comm-l10n/ja, ja-JP-mac.

[comm-l10n-ja_diff20230621.zip](https://github.com/mozilla-japan/gecko-l10n/files/11816817/comm-l10n-ja_diff20230621.zip)

Thanks.

**Comment by jfx2006** [comment]
done https://hg.mozilla.org/projects/comm-l10n/rev/028d57326e97121c4ba4b960c99a880b4a2764fd

Thank you for your efforts!

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 116.0 patch of comm-l10n/ja, ja-JP-mac.

[comm-l10n-ja_diff20230731.zip](https://github.com/mozilla-japan/gecko-l10n/files/12213805/comm-l10n-ja_diff20230731.zip)

It includes 2 patches. They are not conflicted.
Thanks.

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 117.0 patch of comm-l10n/ja, ja-JP-mac.
Sorry for very late apply.

[comm-l10n-ja_diff20230824.zip](https://github.com/mozilla-japan/gecko-l10n/files/12427490/comm-l10n-ja_diff20230824.zip)

Thanks.

**Comment by jfx2006** [comment]
Applied:
https://hg.mozilla.org/projects/comm-l10n/rev/45bb2d0b2650be885d3b27f2ecc8d312abb64d7b

Thank you!

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 118.0 patch of comm-l10n/ja, ja-JP-mac.

[comm-l10n-ja_diff20230917.zip](https://github.com/mozilla-japan/gecko-l10n/files/12642828/comm-l10n-ja_diff20230917.zip)

Thanks.

**Comment by jfx2006** [comment]
> @jfx2006 @dandarnell Hi, this is for 118.0 patch of comm-l10n/ja, ja-JP-mac.
> 
> [comm-l10n-ja_diff20230917.zip](https://github.com/mozilla-japan/gecko-l10n/files/12642828/comm-l10n-ja_diff20230917.zip)
> 
> Thanks.

Applied. Thanks!
https://hg.mozilla.org/projects/comm-l10n/rev/0945e1d96ecaa791f6901a9155aca2ec85a916b1

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 119.0 patch of comm-l10n/ja, ja-JP-mac.

[comm-l10n-ja_diff20231012.zip](https://github.com/mozilla-japan/gecko-l10n/files/12880485/comm-l10n-ja_diff20231012.zip)


Thanks.

**Comment by jfx2006** [comment]
> @jfx2006 @dandarnell Hi, this is for 119.0 patch of comm-l10n/ja, ja-JP-mac.
> 
> [comm-l10n-ja_diff20231012.zip](https://github.com/mozilla-japan/gecko-l10n/files/12880485/comm-l10n-ja_diff20231012.zip)
> 
> Thanks.

Thank you as always!

https://hg.mozilla.org/projects/comm-l10n/rev/6435d776d33a94d2c96481500406dcd52baf2865

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 120.0 patch of comm-l10n/ja, ja-JP-mac.

[comm-l10n-ja_diff20231103.zip](https://github.com/mozilla-japan/gecko-l10n/files/13246263/comm-l10n-ja_diff20231103.zip)

Thanks.

**Comment by jfx2006** [comment]
> @jfx2006 @dandarnell Hi, this is for 120.0 patch of comm-l10n/ja, ja-JP-mac.
> 
> [comm-l10n-ja_diff20231103.zip](https://github.com/mozilla-japan/gecko-l10n/files/13246263/comm-l10n-ja_diff20231103.zip)
> 
> Thanks.

Applied: https://hg.mozilla.org/projects/comm-l10n/rev/0abff7c2212cbfdfc0005c124023934e81b00a7f

**Comment by jfx2006** [comment]
applied: https://hg.mozilla.org/projects/comm-l10n/rev/4a3960a7642d697b16e3ad064c5cca5d8a701376

thank you again!

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 122.0 patch of comm-l10n/ja, ja-JP-mac.

[comm-l10n-ja_diff20240106.zip](https://github.com/mozilla-japan/gecko-l10n/files/13850066/comm-l10n-ja_diff20240106.zip)

Thanks, and a happy new year!

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 123.0 patch of comm-l10n/ja, ja-JP-mac.

[comm-l10n-ja_diff20240208.zip](https://github.com/mozilla-japan/gecko-l10n/files/14209311/comm-l10n-ja_diff20240208.zip)

Thanks.

**Comment by jfx2006** [comment]
Applied. Thank you as always.
https://hg.mozilla.org/projects/comm-l10n/rev/31ff0d568c050adc562e1c9603b690247a16f70c

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 124.0 patch of comm-l10n/ja, ja-JP-mac.

[comm-l10n-ja_diff20240305.zip](https://github.com/mozilla-japan/gecko-l10n/files/14494138/comm-l10n-ja_diff20240305.zip)

Thanks.

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 125.0 patch of comm-l10n/ja, ja-JP-mac.
It was actually skipped for beta releases, however please apply this update.

[comm-l10n-ja_diff20240415.zip](https://github.com/mozilla-japan/gecko-l10n/files/14976807/comm-l10n-ja_diff20240415.zip)

Thanks.

**Comment by jfx2006** [comment]
Applied. Thank you!

https://hg.mozilla.org/projects/comm-l10n/rev/bd4d0ee94745e2a701aafd8d46c8f17ce811aa34

> @jfx2006 @dandarnell Hi, this is for 125.0 patch of comm-l10n/ja, ja-JP-mac. It was actually skipped for beta releases, however please apply this update.
> 
> [comm-l10n-ja_diff20240415.zip](https://github.com/mozilla-japan/gecko-l10n/files/14976807/comm-l10n-ja_diff20240415.zip)
> 
> Thanks.

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 126.0 patch of comm-l10n/ja, ja-JP-mac.

[comm-l10n-ja_diff20240506.zip](https://github.com/mozilla-japan/gecko-l10n/files/15215114/comm-l10n-ja_diff20240506.zip)

Thanks.

**Comment by jfx2006** [comment]
Applied. Thank you!
https://hg.mozilla.org/projects/comm-l10n/rev/ade2df424239d89a39b9309cf25ba8ab9a240f55

> @jfx2006 @dandarnell Hi, this is for 126.0 patch of comm-l10n/ja, ja-JP-mac.
> 
> [comm-l10n-ja_diff20240506.zip](https://github.com/mozilla-japan/gecko-l10n/files/15215114/comm-l10n-ja_diff20240506.zip)
> 
> Thanks.

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 127.0 patch of comm-l10n/ja, ja-JP-mac.

[comm-l10n-ja_diff20240602.zip](https://github.com/user-attachments/files/15524753/comm-l10n-ja_diff20240602.zip)

Thanks.

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Can I ask about the l10n source repo of Thunderbird?

The l10n source repository of Firefox has moved from [gecko-strings](https://hg.mozilla.org/l10n/gecko-strings/pushloghtml) to [firefox-l10n](https://github.com/mozilla-l10n/firefox-l10n) at version 128.0.
For Thunderbird, comm-l10n/en-US is still the l10n source that we can use it now. And, there is [thunderbird-l10n-source](https://github.com/thunderbird/thunderbird-l10n-source) github repo, same as Firefox. Can I switch the source l10n from hg/comm-l10n/en-US to github/thunderbird-l10n-source?

Thanks.

**Comment by jfx2006** [comment]
@marsf 

The Thunderbird strings are being moved over the next couple of weeks.

Currently, Pontoon is still using comm-l10n/en-US as its source. It would be best if you continued to use comm-l10n/en-US for now.

Next week I plan to change the source strings to [https://github.com/thunderbird/thunderbird-l10n-source](thunderbird-l10n-source). 

There will be a [https://github.com/thunderbird/thunderbird-l10n](thunderbird-l10n) repository where all languages will reside. It's my understanding that you will submit Pull Requests for Firefox Japanese translations to [firefox-l10n](https://github.com/mozilla-l10n/firefox-l10n). You will be able to do the same for Thunderbird.

I'm planning on July 1 for the cutover day.

Happy to answer any questions.

Thanks again for your efforts.

**Comment by marsf** [comment]
@jfx2006 
OK, thank you for your explanation. I'll use comm-l10n/en-US for current working version 128.0.

If you have time, please commit the 127.0 patch above.

**Comment by jfx2006** [comment]
> @jfx2006 OK, thank you for your explanation. I'll use comm-l10n/en-US for current working version 128.0.
> 
> ~If you have time, please commit the 127.0 patch above.~ It has been already applied. Thanks.

dc4871d6669020ca7908a86ad3038891be77c18b

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, this is for 128.0 patch of comm-l10n/ja, ja-JP-mac.

[comm-l10n-ja_diff20240626.zip](https://github.com/user-attachments/files/15974116/comm-l10n-ja_diff20240626.zip)

Thanks.

**Comment by jfx2006** [comment]
https://hg.mozilla.org/projects/comm-l10n/rev/3f242bb8031c3266990cb5ca9a7ff5f7f7fccad7

> @jfx2006 @dandarnell Hi, this is for 128.0 patch of comm-l10n/ja, ja-JP-mac.
> 
> [comm-l10n-ja_diff20240626.zip](https://github.com/user-attachments/files/15974116/comm-l10n-ja_diff20240626.zip)
> 
> Thanks.

**Comment by jfx2006** [comment]
An update:

I am a bit behind schedule unfortunately. I will let you know when you can start using the Git repositories.

> @marsf
> 
> The Thunderbird strings are being moved over the next couple of weeks.
> 
> Currently, Pontoon is still using comm-l10n/en-US as its source. It would be best if you continued to use comm-l10n/en-US for now.
> 
> Next week I plan to change the source strings to [https://github.com/thunderbird/thunderbird-l10n-source](thunderbird-l10n-source).
> 
> There will be a [https://github.com/thunderbird/thunderbird-l10n](thunderbird-l10n) repository where all languages will reside. It's my understanding that you will submit Pull Requests for Firefox Japanese translations to [firefox-l10n](https://github.com/mozilla-l10n/firefox-l10n). You will be able to do the same for Thunderbird.
> 
> I'm planning on July 1 for the cutover day.
> 
> Happy to answer any questions.
> 
> Thanks again for your efforts.

**Comment by jfx2006** [comment]
@marsf 

Pontoon is now using the [thunderbird-l10n-source](https://github.com/thunderbird/thunderbird-l10n-source) repository for its source strings.

[thunderbird-l10n](https://github.com/thunderbird/thunderbird-l10n) is *not* used yet. Please continue to use [comm-l10n](https://hg.mozilla.org/projects/comm-l10n).

**Comment by marsf** [comment]
@jfx2006 OK. Thanks for the info.

I have a question. How will going to be about /suite directory? Is it discontinued or moved?

**Comment by jfx2006** [comment]
I've not heard from the Seamonkey developers what their plans are. For now it's going to keep using the current repositories.

**Comment by marsf** [comment]
@jfx2006 @dandarnell
Hi, they are for 129.0 patch of comm-l10n/ja, ja-JP-mac.

1. [comm-l10n-ja_diff20240717-1.zip](https://github.com/user-attachments/files/16319207/comm-l10n-ja_diff20240717-1.zip) (a fix of preference label)
2. [comm-l10n-ja_diff20240717-2.zip](https://github.com/user-attachments/files/16319208/comm-l10n-ja_diff20240717-2.zip)

Can you please apply patch-1 to 128.0 esr, too?
Thanks.

**Comment by jfx2006** [comment]
Applied:
>     1. [comm-l10n-ja_diff20240717-1.zip](https://github.com/user-attachments/files/16319207/comm-l10n-ja_diff20240717-1.zip) (a fix of preference label)

https://hg.mozilla.org/projects/comm-l10n/rev/308762005d1dd9c13ae2c8edf92d24227cb1aa2d

> 
>     2. [comm-l10n-ja_diff20240717-2.zip](https://github.com/user-attachments/files/16319208/comm-l10n-ja_diff20240717-2.zip)

https://hg.mozilla.org/projects/comm-l10n/rev/308762005d1dd9c13ae2c8edf92d24227cb1aa2d
> 
> 
> Can you please apply patch-1 to 128.0 esr, too? Thanks.

The next release of 128esr should pick the change up.

**Comment by jfx2006** [comment]
@marsf 
[thunderbird-l10n](https://github.com/thunderbird/thunderbird-l10n) is now active. You may submit future updates as pull requests.

**Comment by marsf** [comment]
@jfx2006 
Thank you for your hard work!
This issue should be closed.
