### ISSUE TITLE
署名日

### ISSUE THREAD

**Issue by Cai0407** [mozilla-japan/gecko-l10n#391]
/ja/mail/messenger/openpgp/msgReadStatus.ftl

```
openpgp-uncertain-sig-with-date = 不確実なデジタル署名です - 署名日: { $date }
openpgp-invalid-sig-with-date = デジタル署名が正しくありません - 署名日: { $date }
openpgp-good-sig-with-date = 正しく署名されています - 署名日: { $date }
```
OpenPGP の署名の検証結果の表示ですが、英語でも "Signed on { $date }" となっているものの実際には
`# $date (String) - Date with time the signature was made in a short format.`
と注釈があるように OpenPGP 署名の「日」ではなく「日時」(年月日時分) が表示されます。

GnuPG では「○○ に施された署名」とローカライズされており、Enigmail の頃は「署名日時: ○○」としていました。

**Comment by marsf** [comment]
「署名日時」でよいと思います。

**Comment by marsf** [comment]
ありがとうございます。
