### ISSUE TITLE
L10n ガイドラインのカッコ前後の半角空白の入れ方について

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/gecko-l10n#400]
[l10n ガイドライン](https://github.com/mozilla-japan/translation/wiki/L10N-Guideline)にて

`Firefox は Mozilla プロジェクト(mozilla.org) による次世代ウェブブラウザです！`

を良い例として例示されていた。

> - 英数字と日本語との間には半角空白を入れることを原則とする。
> - 記号と日本語の間については文脈や記号に合わせて空白の有無を決める。

という前提を踏まえて「Mozilla プロジェクト」の訳語であるという連続性から「(mozilla.org)」の前には半角空白無し、後ろはアリという表記ルール。

実際初期の L10n はそのようにされていたが今はそうなっていないし、今後も半角カッコの前後両方空白ありで良いだろうと MDN meetup 60th + L10n meetup で議論をした。

**Comment by dynamis** [comment]
ガイドラインの記載を更新した
https://github.com/mozilla-japan/translation/wiki/L10N-Guideline/_compare/ec61c0305d34bee318c8e9d71c7fdd337df7bed9...1925fbd91dacc07ff80f5cb7a887e8b02bfd895d

**Comment by hokonch** [comment]
(旧)/(現行)だけだとわかりにくいので
このIssueへの参照をガイドラインに追加するか
`・(追加): 半角括弧と日本語の間に関しては半角スペースを入れる`
といったルールを追加するか
その両方かがあったほうが良いと思います。

**Comment by dynamis** [comment]
> (旧)/(現行)だけだとわかりにくいので

次のように丁寧な説明付きに更新しました:

> * 英数字と日本語との間には半角空白を入れることを原則とする。
> * 記号と日本語の間については文脈や記号に合わせて空白の有無を決める。
>   * 例えば "(" の前は半角空白だが後は詰める、")" や ":" の前は詰めるが後は半角空白
>   * 当初は 「日本語(english)」であったり「名称(略称)」のような場合は例外的に "(" の前の半角空白をなしとして詰めていたが、用法によらず "(" の前が日本語である場合には半角空白をいれる事に[変更された](https://github.com/mozilla-japan/gecko-l10n/issues/400)
> ...
> 
> 表記の例:
> * 悪い例: Firefox　は Mozillaプロジェクト（mozilla.org）による次世代Ｗｅｂブラウザです!
>   * 英字日本語の間のスペースがあったりなかったりする。"(" の前や ")" の後に半角空白がない
> * 良い例 (当初): Firefox は Mozilla プロジェクト(mozilla.org) による次世代ウェブブラウザです！
>   * Mozilla プロジェクトの別表現が mozilla.org であることを指す連続性から "(" の前を詰めていた
> * 良い例 (現行): Firefox は Mozilla プロジェクト (mozilla.org) による次世代ウェブブラウザです！
>   * "(" の前には原則通り半角空白をいれる

ついでに github で markdown の箇条書きが綺麗に出力されるように全体的に修正したコミット:
https://github.com/mozilla-japan/translation/wiki/L10N-Guideline/_compare/1925fbd91dacc07ff80f5cb7a887e8b02bfd895d...5fb16a07f52cab942d90c5ae08226384bee1d419
