### ISSUE TITLE
Thunderbird 120.0b3 にて多数の日本語未適用箇所がある

### ISSUE THREAD

**Issue by EarlgreyPicard** [mozilla-japan/gecko-l10n#412]
Thunderbird 120.0b2では問題なかったのですが、120.0b3で多数の箇所で日本語未適用となっております。
MozillaZine.jpフォーラムにその旨の投稿がありました。
[thunderbird120のベータ版3日本語版で、不完全な日本語化状態](https://forums.mozillazine.jp/viewtopic.php?f=3&t=22327)
本体側で変更があったのかビルドで問題が発生したのかはわかりませんが、念のため連絡させていただきました。

**Comment by Cai0407** [comment]
120.0b3 ではベータ版のブランディングが追加され、言語ファイルにもそれ関係のファイルが追加されています。
https://bugzilla.mozilla.org/show_bug.cgi?id=1845794

日本語版 (ja, ja-JP-mac) でもそれらの追加を含むリソースの更新が行われていますが
https://hg.mozilla.org/projects/comm-l10n/rev/0abff7c2212cbfdfc0005c124023934e81b00a7f
残念ながら 120.0b3 には間に合っていません。
この辺の影響でしょうか？

**Comment by EarlgreyPicard** [comment]
影響は広範囲に渡っていますが、brand.dtd でのブランド名定義
[comm-l10n: comparison ja/mail/branding/tb_beta/brand.dtd](https://hg.mozilla.org/projects/comm-l10n/comparison/0abff7c2212cbfdfc0005c124023934e81b00a7f/ja/mail/branding/tb_beta/brand.dtd)
が無いために、ブランド名を使っている ftl がエラーとなって未適用となってる、使っていない ftl は問題なしということなのでしょうか。

**Comment by Cai0407** [comment]
ja, ja-JP-mac におけるベータ版のブランディング関係のファイルの更新が反映された 120.0b4 がリリースされましたが、確認した限り問題なく日本語が適用されています。
