### ISSUE TITLE
「開発者ツール」「ネットワーク」タブにおけるタイミング系カラムについて

### ISSUE THREAD

**Issue by igrep** [mozilla-japan/gecko-l10n#427]
個人的な感覚の問題や、翻訳の問題を超えた問題も含んでいるのですが、掲題のカラムを初めて表示させたとき、いずれのカラムも何を表しているのかよく分かりませんでした。

![image](https://github.com/mozilla-japan/gecko-l10n/assets/227057/a5ecacef-0bf3-4dc4-89e9-d71313a1477b)

### (1) 「開始時刻」・「終了時刻」について

日本語で「時刻」というと「13時21分」とか「午前9時ちょうど」とか、時計の上で指し示されるもののイメージが強いため、最初に見たとき「時刻なのに単位がミリ秒？」と首を捻りました。
https://github.com/mozilla-japan/gecko-l10n/blob/e3ee3c321786886d6df8c9eca39d4a46fc61a013/ja/devtools/client/netmonitor.properties#L653-L673 の辺りのコメントを読んでようやく納得しました。
「対象のウェブページを表示する最初のリクエストが始まってから、対象のリクエストが始まるまで（あるいは終わるまで）の経過時間」なんですね。

個人的には「**開始時間**」「**終了時間**」の方がしっくりきます。ただ、それでも「対象のウェブページを表示する最初のリクエストが始まってから～」の時間であることが一目で分かるとは思えないため（これ以外のカラムにも言えることですが）、ツールチップを出すなど、何かしら詳しい情報への導線があるとありがたいと感じました。

参考: https://www.shinko-keirin.co.jp/keirinkan/sansu/WebHelp/02/page2_02.html 

### (2) 「応答時間」について

[前節でも触れた英語の解説](https://github.com/mozilla-japan/gecko-l10n/blob/e3ee3c321786886d6df8c9eca39d4a46fc61a013/ja/devtools/client/netmonitor.properties#L653-L673)「最初のリクエストが始まってから、ダウンロードが始まるまで」の時間だそうです。ここでは「応答」が「ダウンロードが始まる」ことに相当するそうですので、「**応答開始時間**」の方がより明確かと思います。とすると、先程の「開始時刻」も併せて「**要求開始時間**」にすることで、対応関係が分かりやすくなるのではないでしょうか。

### (3) 「間隔」について

何から何への間隔なのかが分からず、戸惑いました。文脈的にあり得ないですが、何かしらのポーリングをしていてその実行間隔なのかな、とも思えました。「間隔」という言葉は、どちらかというと空白の部分（通信していない部分）を指しているように聞こえるので。

[件の英語の解説](https://github.com/mozilla-japan/gecko-l10n/blob/e3ee3c321786886d6df8c9eca39d4a46fc61a013/ja/devtools/client/netmonitor.properties#L653-L673)を読むに、対象のリソースに対するリクエストの開始から終了までの時間だそうです。
「間隔 = 終了時刻 - 開始時刻」という式が成立するようです。

 @hmatrjp さんの提案なんですが「**所要時間**」というのはいかがでしょうか？

### (4) 「遅延」について

こちらについては現状対案も思いつかないのでひとまずこのままで良いと思います。
「遅延 = 終了時刻 - 応答時間」という関係があるみたいですね。

そもそも何故この5つを対象にしたのか、など根本的な問題も気になってしまいましたが、ひとまず翻訳活動として対応できそうな案として列挙いたしました。ご検討よろしくお願いします。

**Comment by marsf** [comment]
https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/request_details/#network-monitor-request-details-timings-tab

それぞれの関係は、各ファイルの詳細 (右サイドバーのグラフ) のタイミングタブを開くと分かります。
単位が書かれているので「時間」「時刻」は省いてもいいように思います。
列の幅が狭いので文字数も少なめにして、ソースのコメントにある通り、以下のようにするのはいかがでしょうか。

> the time from start of 1st request until the **start of this request**.
netmonitor.toolbar.startTime=Start Time

→ 要求開始

> the time from start of 1st request until the **end of this response**.
netmonitor.toolbar.endTime=End Time

→ 応答終了

> the time from start of 1st request until the **beginning of download of this response**.
netmonitor.toolbar.responseTime=Response Time

→ 応答時間
[レスポンスタイム - IT用語辞典 e-Words](https://e-words.jp/w/%E3%83%AC%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%A0.html)

> the time from start of this request until the **end of this response**.
netmonitor.toolbar.duration=Duration

Duration は、タイミングタブの「ブロック〜受信」の合計時間のようです。
→ 往復時間
[RTT ラウンドトリップタイム - IT用語辞典 e-Words](https://e-words.jp/w/RTT.html)
[What is round-trip time? | RTT definition](https://www.cloudflare.com/learning/cdn/glossary/round-trip-time-rtt/)

**Comment by igrep** [comment]
> 単位が書かれているので「時間」「時刻」は省いてもいいように思います。
列の幅が狭いので文字数も少なめにして、ソースのコメントにある通り、以下のようにするのはいかがでしょうか。

確かにそうですね！ 👍

**Comment by marsf** [comment]
修正しました。
ありがとうございました。
