### ISSUE TITLE
l10n-central から firefox-l10n 移行への対応

### ISSUE THREAD

**Issue by marsf** [mozilla-japan/gecko-l10n#436]
本家のリポジトリーが Mercurial の [l10n-central](https://hg.mozilla.org/l10n-central/) から Github の [Firefox-l10n](https://github.com/mozilla-l10n/firefox-l10n) へ移行するそうです。
移行のスケジュールは現時点で未定。(次の ESR 128 あたりが目途？)

日本語以外のロケールは Pontoon のバックエンドとして構成されているため何もする必要がありませんが、日本語 (ja / ja-JP-mac) ロケールの更新は、これまで直接コミットしていたものを Pull Request に変更する必要があります。

また、この機に gecko-l10n 側のワークフローも整理したいと思います。
作業上の不都合も含め、何か気が付いたことがあればコメントください。

**Comment by bcolsson** [comment]
移行のスケジュールはまだ確認中です。
[Firefox-l10n](https://github.com/mozilla-l10n/firefox-l10n)の現在の形成は格ロケールごとにブランチがあるが、
最終的に全てがmainにマージされることがわかりました。

mainで格ロケールのサブフォルダがあるという形成になります。

**Comment by makotokato** [comment]
Mozilla 側の作業手間を考えると、[firefox-l10n](https://github.com/mozilla-l10n/firefox-l10n) にPRを投げるものは、どこかでレビューしたものが必要な気がしますが、その手順を明確にする必要がありますね。いままで通りこのレポジトリへPRを書いてコミットしたものを、別途PRを投げることにするとか

Pontoonへの移行は、Firefox/Thunderbirdが*.propertiesファイルをすべて*.ftlファイルに移行できてないので、今のところでは不可能ですし (https://github.com/mozilla-japan/gecko-l10n/issues/344 で話したことを行ったとしても)

**Comment by bcolsson** [comment]
6月3日に担当者が移行について最終整理にの擦り合わせをするそうです。
問題がなかれば6月４日に移行を行う可能性があります。

**Comment by marsf** [comment]
コメントありがとうございます。

> mainで格ロケールのサブフォルダがあるという形成になります。

結局、[comm-l10n](https://hg.mozilla.org/projects/comm-l10n/) と同じようになるんでしょうか。

現在のワークフローは、

1. l10n-central/ja 側に入った更新を gecko-l10n にフォールバックして直接 commit (フィルターの用語は置き換える)
2. gecko-strings に合わせてローカライズ作業、gecko-l10n に PR
3. PR をレビュー、修正した上で master にマージ
4. gecko-l10n の master ブランチをローカルの [lot スクリプト](https://github.com/mozilla-japan/lot)で ja/ja-JP-mac にコンバート
5. それぞれ l10n-central/ja, ja-JP-mac にコミット (要コミット権限)

という流れです。

今回、上記のステップ 5. が Firefox-l10n への PR になるだけだと思っています。
この PR のレビューは @bcolsson さんか他のスタッフがしてくださる予定。
(comm-l10n のほうは[パッチを作成](https://github.com/mozilla-japan/gecko-l10n/issues/360)して代理で commit してもらっています)

ja と ja-JP-mac の用語表記や翻訳のゆれが起こるおそれがあるため、この gecko-l10n を通さずに PR することは避けたいです。

**Comment by marsf** [comment]
整理したいこと:

- gecko-l10n のディレクトリー構成を root から firefox-l10n と comm-l10n に分けたい
  - lot スクリプトのディレクトリー設定部分をすべて書き換える必要あり
- lot スクリプトをやめて、[lot-conv.py](https://github.com/marsf/lot-conv) に移行したい
  - 全体の一括コンバートは可能。プロダクト指定は未実装 (しなくてもよい？)
  - 構文チェック等は compare-locales に任せる
  - 用語チェックのための lot-proof.py は未完成 (未公開)
    - 現状、wordcheck-deny は実装、テスト済み
    - charcheck とプロダクトごとの allow/deny が必要
    - placeholder-check もできればほしい
 - エラーになった用語を正しい表記になおすための一覧表ページをつくりたい

**Comment by bcolsson** [comment]
> 結局、[comm-l10n](https://hg.mozilla.org/projects/comm-l10n/) と同じようになるんでしょうか。

そうですね。最終的な形は以下になる予定です。
https://github.com/mozilla-l10n/firefox-l10n/tree/cthulhu

**Comment by bcolsson** [comment]
本日、移行の作業が行いました。今後のコミットは[firefox-l10n](https://github.com/mozilla-l10n/firefox-l10n)でお願いします。
基本的に@bcolssonか@flodoloがレビューします。PRのレビューはなるべく速やかに確認するようにしますが、
少し余裕を持って締め切り前の数日前にいただけると大変助かります。
（締め切りギリギリの場合はビルドに間に合わない可能性があります。）

**Comment by marsf** [comment]
@bcolsson 承知しました。よろしくお願いします。

念のため確認ですが、en-US だけは変わらず [gecko-strings](https://hg.mozilla.org/l10n/gecko-strings) ですよね？

**Comment by flodolo** [comment]
gecko-strings will remain updated for a few more weeks, but the source of truth is https://github.com/mozilla-l10n/firefox-l10n-source for en-US

**Comment by marsf** [comment]
@flodolo I had never noticed. OK, thanks.

**Comment by marsf** [comment]
ローカライズ元のソースを hg.mozilla.org から Github に変更して、[ja.gecko.status](https://github.com/mozilla-japan/gecko-l10n/blob/master/ja.gecko.status) もそれに合わせる必要あり。

Firefox:
https://hg.mozilla.org/l10n/gecko-strings/
→ https://github.com/mozilla-l10n/firefox-l10n-source

Thunderbird:
https://hg.mozilla.org/projects/comm-l10n/file/tip/en-US
→ https://github.com/thunderbird/thunderbird-l10n-source


gecko-l10n リポジトリーのディレクトリー構成を firefox-l10n と comm-l10n に分けるとして、ja.gecko.status も同じように分ける考え方もあるが、comm が共通リソースである firefox-l10n 配下の toolkit 等も利用しているので、できれば同じファイルでリビジョンの更新状態を確認したい。

現在の書式:
```
repo | target dir               hg changeset rev:id (pushdate)   by             comment
--------------------------------------------------------------------------------------------------------
geck | dom, netwerk, toolkit    15362:c79daf95cc72 (2024-05-21)  mar            sync dom, toolkit, netwerk
comm | mail, calendar           19552:422a1d805c49 (2024-05-29)  mar            sync mail, chat
```


例えば、Github のコミットログから、commit rev. の先頭12桁と commit date を拾う。
```
commit 2ffa4c0d063a3907d684b7cb4efed9195f1dabfe
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Tue Jun 4 07:19:41 2024 +0200

    Update messages (#45)
```

変更案:
```
repo  | target dir               github rev   (pushdate)    by           comment
----------------------------------------------------------------------------------
fxsrc | browser                  d5cea93f481a (2024-06-04)  mar          sync browser
tbsrc | mail, calendar           ...          ( ...      )
```

**Comment by marsf** [comment]
[thunderbird-l10n-source](https://github.com/thunderbird/thunderbird-l10n-source) のほう、/suite が無い。
長らく更新されてないし、すでに別の法人だから含まないのかも。

trunk は 2.125 らしいが、
https://wiki.mozilla.org/SeaMonkey:Home_Page#Status

SeaMonkey だけ comm-l10n に取り残されてる感じ。
https://hg.mozilla.org/projects/comm-l10n/file/tip/ja/suite

**Comment by flodolo** [comment]
> Thunderbird: [hg.mozilla.org/projects/comm-l10n/file/tip/en-US](https://hg.mozilla.org/projects/comm-l10n/file/tip/en-US) → [thunderbird/thunderbird-l10n-source](https://github.com/thunderbird/thunderbird-l10n-source)

Our team doesn't cover Thunderbird, but this is not correct.

The reference for Thunderbird remains https://hg.mozilla.org/projects/comm-l10n/file/tip/en-US until there is a different communication from their team.

I think `thunderbird-l10n-source` is an ongoing test on their part. The l10n repository might migrate to GitHub at some point, but that doesn't mean that they'll use the same structure as Firefox (one repo for en-US, one repo for all other locales).

**Comment by marsf** [comment]
Wiki のドキュメント関係。

- [ ] [hg.mozilla.org 向け環境設定](https://github.com/mozilla-japan/gecko-l10n/wiki/hg.mozilla.org) は「ローカライズ作業の環境設定」に書き換える。
- [ ] [workflow](https://github.com/mozilla-japan/gecko-l10n/wiki/workflow) も今回の変更に合わせて更新する。

**Comment by marsf** [comment]
> The reference for Thunderbird remains https://hg.mozilla.org/projects/comm-l10n/file/tip/en-US until there is a different communication from their team.

Yes, I understand that. However, the github repo has been used as their primary resource of Pontoon, and comm-l10n.
> They are extracted from the active branches (Daily, Beta, Release, ESRs) by a scheduled [GitHub action](https://github.com/thunderbird/thunderbird-l10n-source/blob/main/.github/workflows/update.yml), which produces pull requests that are reviewed by the **Thunderbird L10n** team before merging.
> 
> From here, messages are exposed to translators in [Pontoon](https://pontoon.mozilla.org/).

I will ask about it to Rob.

**Comment by flodolo** [comment]
> > The reference for Thunderbird remains [hg.mozilla.org/projects/comm-l10n/file/tip/en-US](https://hg.mozilla.org/projects/comm-l10n/file/tip/en-US) until there is a different communication from their team.
> 
> Yes, I understand that. However, the github repo has been used as their primary resource of Pontoon, and comm-l10n.

The source for Thunderbird in Pontoon is https://hg.mozilla.org/users/m_owca.info/thunderbird/, which is generated from `comm-l10n/en-US`. I wasn't even aware of the GitHub repository before reading your message.

**Comment by marsf** [comment]
@bcolsson @flodolo 
Hi, this is the first PR to firefox-l10n.
https://github.com/mozilla-l10n/firefox-l10n/pull/14

At this time, its source is from gecko-strings.
Thanks.

**Comment by marsf** [comment]
Thunderbird も [thunderbird-l10n](https://github.com/thunderbird/thunderbird-l10n) に移行した。 ver.130.0+ の作業から PR で更新する。

/suite はどうなるか不明のまま。

**Comment by flodolo** [comment]
SeaMonkey moved here: https://gitlab.com/seamonkey-project/seamonkey-central-l10n 

As for `firefox-l10n`, as explained in the last pull request, it would be great to open the PR a few days earlier (even a week would work):
* If the PR is opened only a few hours before the deadline, it's impossible to test it in Nightly before the release candidate build. Fixing any issue at that point becomes really complicated. Also, staff availability over the weekend is limited, so we risk missing the deadline.
* The deadline is always relevant for Beta content. For example, the content for Firefox 129 was frozen 3 weeks before that deadline, translating a week before would have still covered 129 completely.

**Comment by marsf** [comment]
> The deadline is always relevant for Beta content. For example, the content for Firefox 129 was frozen 3 weeks before that deadline, translating a week before would have still covered 129 completely.

Thank you very much for the info, and your patients. I can set the deadline a week (or 10 days) earlier for ja l10n.

**Comment by marsf** [comment]
Updated related documents.
Close this issue.
