### ISSUE TITLE
Not Before, Not After

### ISSUE THREAD

**Issue by Cai0407** [mozilla-japan/gecko-l10n#462]
証明書の有効期限の表示に関してです。

[/ja/toolkit/toolkit/about/certviewer.ftl](https://github.com/mozilla-japan/gecko-l10n/blob/master/ja/toolkit/toolkit/about/certviewer.ftl)
> certificate-viewer-not-after = 終了日
certificate-viewer-not-before = 開始日

英語ではそれぞれ Not After, Not Before です。
UI 上では Fri, 07 Mar 2025 23:59:59 GMT のように秒まで含めた表示となっており、「～日」ではなく「～日時」とする方が表示に合うと思います。

Chromium 系では Not After を「有効期限」、Noe Before を「発行日」としています (これはこれで揃ってないですが)。

修正案
- 終了日時 / 開始日時
- 有効期限 / 発行日時
- 失効日時 / 発行日時

**Comment by marsf** [comment]
まず、この項目の見出しは「有効期間」となっていて、その「開始日」と「終了日」を表示しています。あえて変更するなら「発効日 / 失効日」になると思います。
発行日＝発効日だとしても、Chromium 系の「発行」は誤りではないでしょうか。

「開始日時 / 終了日時」には、変更してもしなくてもかまいません。

**Comment by Cai0407** [comment]
> 「開始日時 / 終了日時」には、変更してもしなくてもかまいません。

「開始日時 / 終了日時」への変更でプルリク出しました。
#464
