### ISSUE TITLE
質問: about:preformanceについて

### ISSUE THREAD

**Issue by lv7777** [mozilla-japan/gecko-l10n#48]
about:performanceのページを訳そうと思い、
https://hg.mozilla.org/mozilla-central/file/FIREFOX_AURORA_48_BASE/toolkit/locales/en-US/chrome/global
とか見てて、about:performanceに関係する部分のdtdファイル等が見つからなかったのですがこれってまだ翻訳開始とみなされていないってことですか？

**Comment by marsf** [comment]
現状ではローカライズできないようです。
https://hg.mozilla.org/releases/mozilla-aurora/file/b6738ca644382710da35245e0c2e01479befeb37/toolkit/components/aboutperformance/content/aboutPerformance.js#l576

ちなみに、ロケールのリソースを検索できるサイトがあります。
検索対象 ("search in") を string と entity から選べます。
https://transvision.mozfr.org/

L10nフォーラムもあるので、一般的な質問はこちらを使ってください。
http://forums.firehacks.org/l10n/index.php
