### ISSUE TITLE
コンテナタブの「プライベート」

### ISSUE THREAD

**Issue by vyv03354** [mozilla-japan/gecko-l10n#54]
https://dxr.mozilla.org/l10n-mozilla-aurora/rev/57d382a8324e3bb48b1d0e3df988b698117a844b/ja/browser/chrome/browser/browser.dtd#264
近くに「プライベートウィンドウ」が表示される状況で使われるので、「プライベート」では紛らわしいと思います。英語版もあえて "Private" を避けているのではないでしょうか。

**Comment by marsf** [comment]
対象の文字列は 49.0 で browser.properties に移動しています。
https://dxr.mozilla.org/l10n-mozilla-aurora/source/ja/browser/chrome/browser/browser.properties#728

「個人」にしました。
50.0 で修正。
