### ISSUE TITLE
新しいスタイルガイドを適用する

### ISSUE THREAD

**Issue by marsf** [mozilla-japan/gecko-l10n#55]
[L10n ガイドライン](https://github.com/mozilla-japan/translation/wiki/L10N-Guideline) を更新しました。
周知のとおり、Gecko 51～52 (ESR) で製品のローカライズも更新します。

主に用語の変更で、「Web」→「ウェブ」とカタカナ語の長音付加です。
作業はディレクトリー単位もしくは製品単位で更新する、ということでいかがでしょうか。

追記 (10/31)：
[表記ゆれ撲滅ハッカソン](https://mozilla.doorkeeper.jp/events/52205) の成果をもとに単語単位での作業にしましょう。

- [x] Web → ウェブ by @hATrayflood,  51.0 done.
- 長音付加
  - [x] computer by @blp1526,  51.0 done.
  - [x] browser by @blp1526,  51.0 done.
  - [x] viewer by @tSU-RooT,  51.0 done.
  - [x] inspector by @tSU-RooT,  51.0 done.
  - [x] user by @blp1526,  51.0 done.
  - [x] parameter by @tSU-RooT,  51.0 partially done.
  - [x] header by @tSU-RooT,  51.0 partially done.
  - [x] server by @marsf, 51.0 done.
  - [x] filter by @marsf, 51.0 done.
  - [x] folder by @marsf, 52.0 done.
  - [x] directory by @marsf, 52.0 done.
  - [x] query by @marsf, 52.0 done.
  - [x] installer by @marsf, 52.0 done.
  - [x] manager by @marsf, 51.0 done.
  - [x] container by @marsf, 51.0 done.
  - [x] debugger by @marsf, 52.0 done.
  - [x] pointer by @marsf, 52.0 done.
  - [x] memory by @marsf, 52.0 done.
  - [x] selector by @marsf, 52.0 done.
  - [x] handler by @marsf, 52.0 done.
  - [x] picker by @marsf, 52.0 done.
  - [x] entry by @marsf, 52.0 done.
  - [x] header / footer by @marsf, 52.0 done.
  - [x] encoder / decoder by @marsf, 52.0 done.
  - [x] jitter by @marsf, 52.0 done.
  - [x] parameter by @marsf, 52.0 done.
  - [x] slider by @marsf, 52.0 done.
  - [x] monitor by @marsf, 52.0 done.
  - [x] category by @marsf, 52.0 done.
  - [x] editor by @marsf, 52.0 done.
  - [x] responder by @marsf, 53.0 done.
  - [x] provider by @marsf, 57.0+ done.
  - [x] firewall by @marsf, 57.0+ done.
- 日本語文体
  - (随時追加します)

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/commit/22852aa69e8ec89fbccfcde15420226a11d8516a browserのWeb→ウェブ

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/commit/ec0cf2ea8a15aff9cb82bdb49ef7ede2d280e783 devtoolsのWeb→ウェブ

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/commit/6622d46b1b1c5c44b94de891a75ebffa80c5670e toolkitのWeb→ウェブ

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/commit/abd40be5f5530df9dbffec2727f3d1cf6e0c9e27 domのWeb→ウェブ

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/commit/8c0da9660336efcbc68355f978e6b6cfccb43ccb netwerkのWeb→ウェブ

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/commit/23d1668fdaac9f97afeca33f623a2d898908d178 securityのWeb→ウェブ

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/commit/af4362636ee9021493fdf646bde9ffd5a88601ed editorのWeb→ウェブ

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/commit/1840836c5f337406f1481cf01857f0b255cee15a extensions/ircのWeb→ウェブ

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/commit/cfded5c06a28fbb3b4ffef4fe4ee50871cd20a22 mobileのWeb→ウェブ

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/commit/597d8ad344b61b3677cd8f3853e7c65c236b1c77 suiteのWeb→ウェブ

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/commit/359946e8be8f8f09961450e129cb13dbec335858 calendarのWeb→ウェブ

**Comment by hATrayflood** [comment]
https://github.com/mozilla-japan/gecko-l10n/commit/7428bbdfa752b9ca67a96e2163532233e3ce9dd4 mailのWeb→ウェブ

**Comment by marsf** [comment]
「**Web** → **ウェブ**」について、hg リポジトリの各ディレクトリ単位でコミットしました。

browser:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/9040c575d252
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/252d7ca82199

devtools:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/5a63f9adabe4
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/a8f6decb66d1

toolkit:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/4bc9b2c22a82
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/2470ce313551

dom:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/aa07a12050a9
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/880c9b871fee

netwerk:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/99f17fd04795
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/500a1b20b1b6

security:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/8f7c791d9794
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/06ca71cfa0dd

extensions/irc:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/70830a17927c
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/40a7ebc50a09

mobile:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/b6f6966e4417
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/7f3b0af75eae

suite:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/2e2d149937de
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/7a6571de1761

calendar:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/692042b33cca
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/c62e4bba76a8

mail:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/00ff1bdfed02
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/5f3169fa78e9

**Comment by marsf** [comment]
@blp1526 さんの作業分を単語単位でコミットしました。
ありがとうございます！

**computer** (https://github.com/mozilla-japan/gecko-l10n/commit/13a4a26b7d7e685cac8b820eeb6bbbe78a1c558d):
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/33573b45a8b5
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/c9a65bbb3cf8

**browser** (https://github.com/mozilla-japan/gecko-l10n/commit/12784f6a4e02c6cb0188f8d94e3b04dc412cd4f3):
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/8a7689fa98cf
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/746fe7ec7ad3

**user** (https://github.com/mozilla-japan/gecko-l10n/commit/66abcd142fbfdc3b984c0bba5df99c9b959ac219):
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/83c8160c3fd1
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/a61c090a62fb

**Comment by marsf** [comment]
以下は @tSU-RooT さんの作業分です。
ありがとうございます！

**inspector** (https://github.com/mozilla-japan/gecko-l10n/commit/9a95e67531e019e9adea9498afe7e9a7645ec258):
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/cf4ab655a5bd
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/ec8a54000c5a

**viewer** (https://github.com/mozilla-japan/gecko-l10n/commit/67eb6d8c30cf82b97cbe368498d0754bac1c8006):
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/f24c417129fe
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/ebdf934bb169

**parameter** (https://github.com/mozilla-japan/gecko-l10n/commit/8b96221814822f0b9410368e6d67af62a3923d04):
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/36e68eeb910b
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/cdf5fd6207a2

**header** (https://github.com/mozilla-japan/gecko-l10n/commit/8d207208f454bb728ad5dce69f75df8edbe98722):
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/c1c47e8cc6e9
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/e6181e60dbfa

**Comment by marsf** [comment]
**server**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/969df0aca596
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/6377115647d5

**Comment by marsf** [comment]
**filter**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/987c5045d6be
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/6f4fc954501e

「フィルタリング」はそのまま。

**Comment by marsf** [comment]
**manager** (https://github.com/mozilla-japan/gecko-l10n/commit/7ddeae8cbcaf3c20a279ca669a6b6285d1524b73):
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/1b3c5466b876
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/50bde2293212

**Comment by marsf** [comment]
**container**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/286044a81df7
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/cfc755f6312a

**Comment by vyv03354** [comment]
browserの長音付加は51.0で対応したことになっていますが、実際にはFirefoxの「既定のブラウザ」が未対応です。ファイルで言うと、browser/chrome/browser/preferences/main.dtd と browser/chrome/browser/shellservice.properties 内の文言です。
https://dxr.mozilla.org/l10n-mozilla-aurora/search?q=%E6%97%A2%E5%AE%9A%E3%81%AE%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6&redirect=false

**Comment by vyv03354** [comment]
あと、macOSは今でも長音付加を行っていないようですが、各OSの規約とは無関係に統一するのでしょうか。だとしたらja-JP-macは何のために存在するのでしょうか。

**Comment by marsf** [comment]
@vyv03354:
ご指摘ありがとうございます。
> browserの長音付加は51.0で対応したことになっていますが、実際にはFirefoxの「既定のブラウザ」が未対応です。

[ja.filters の @@DefaultBrowser@@](https://github.com/mozilla-japan/gecko-l10n/blob/master/ja.filters#L25) による変更のみで、lot でコンバートした時に元のファイルのタイムスタンプが更新されておらず、これを hg リポジトリにコミットする時に漏れがあったようです。
[/browser/shellservice.properties](https://github.com/mozilla-japan/gecko-l10n/blob/master/ja/browser/chrome/browser/shellservice.properties)
52.0 beta で対応します。

**Comment by marsf** [comment]
> あと、macOSは今でも長音付加を行っていないようですが、各OSの規約とは無関係に統一するのでしょうか。だとしたらja-JP-macは何のために存在するのでしょうか。

スタイルガイド改訂にあたって、長音表記を特定の OS に合わせることはしていません。
参考にしているマイクロソフトの日本語スタイルガイドに書かれた長音表記も、「平成 3 年 6 月 28 日 内閣告示第 2 号「外来語の表記」」に従ったものです。
長音付加のルールについては、例外をなくしたいという思いもあって、Mozilla の日本語スタイルガイド独自のものです。

ja と ja-JP-mac の違いについては、[ja.filters](https://github.com/mozilla-japan/gecko-l10n/blob/master/ja.filters) を見てください。
長音だけは macOS の規約を外れるかもしれませんが、その他に全く異なる用語がたくさん使われています。
カタカナ表記に長音が付いただけで ja-JP-mac の存在意義が問われることにはならないと思います。

**Comment by marsf** [comment]
> ja.filters の @@DefaultBrowser@@ による変更のみで、lot でコンバートした時に元のファイルのタイムスタンプが更新されておらず、これを hg リポジトリにコミットする時に漏れがあったようです。
/browser/shellservice.properties
52.0 beta で対応します。

https://hg.mozilla.org/releases/l10n/mozilla-beta/ja/rev/341947354a69
https://hg.mozilla.org/releases/l10n/mozilla-beta/ja-JP-mac/rev/1c99dfb48618

**Comment by marsf** [comment]
**folder**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/853c0e3d8eda
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/f226a2ff7634

https://hg.mozilla.org/releases/l10n/mozilla-beta/ja/rev/3ba5611ca18d
https://hg.mozilla.org/releases/l10n/mozilla-beta/ja-JP-mac/rev/c560897213d0

**Comment by marsf** [comment]
**directory**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/ac77484c69e6
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/9c3ad3afd4db

https://hg.mozilla.org/releases/l10n/mozilla-beta/ja/rev/352e2ee8c23a
https://hg.mozilla.org/releases/l10n/mozilla-beta/ja-JP-mac/rev/c8c91d295c2e

**Comment by marsf** [comment]
**query**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/39a09bd2da30
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/d513ff1c130e

https://hg.mozilla.org/releases/l10n/mozilla-beta/ja/rev/68426a287e88
https://hg.mozilla.org/releases/l10n/mozilla-beta/ja-JP-mac/rev/000020ca68c1

**Comment by marsf** [comment]
**installer**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/52a21dd6d257
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/268d0ac8917e

https://hg.mozilla.org/releases/l10n/mozilla-beta/ja/rev/76cfe5db608a
https://hg.mozilla.org/releases/l10n/mozilla-beta/ja-JP-mac/rev/f9b15c37ee20

**Comment by marsf** [comment]
**debugger**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/2165d41c5b2f
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/725dd1c225c5

https://hg.mozilla.org/releases/l10n/mozilla-beta/ja/rev/702d95708291
https://hg.mozilla.org/releases/l10n/mozilla-beta/ja-JP-mac/rev/9977c87506a6

**Comment by marsf** [comment]
**pointer**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/c44fcf56b5f9
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/60e502be1745

https://hg.mozilla.org/releases/l10n/mozilla-beta/ja/rev/c596f800130a
https://hg.mozilla.org/releases/l10n/mozilla-beta/ja-JP-mac/rev/e3b94e022b7d

**Comment by marsf** [comment]
**memory**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/ef6f6c030c44
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/eda5f8edf210

https://hg.mozilla.org/releases/l10n/mozilla-beta/ja/rev/949169909ff1
https://hg.mozilla.org/releases/l10n/mozilla-beta/ja-JP-mac/rev/4c73e0a5d142

**Comment by marsf** [comment]
**selector**, **handler**, **picker**, **entry**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/314fa59788ea
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/3508d2a33cdd

https://hg.mozilla.org/releases/l10n/mozilla-beta/ja/rev/37fa9e52730e
https://hg.mozilla.org/releases/l10n/mozilla-beta/ja-JP-mac/rev/dc7cb51f0c66

**Comment by marsf** [comment]
**header**, **footer**, **encoder**, **decoder**, **jitter**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/e383bbde3767
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/efd14f3dc7c8

https://hg.mozilla.org/releases/l10n/mozilla-beta/ja/rev/f592e68a916a
https://hg.mozilla.org/releases/l10n/mozilla-beta/ja-JP-mac/rev/5044900a26a1

**Comment by marsf** [comment]
**parameter**, **slider**, **monitor**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/780f1adaea05
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/196b39dcddb7

https://hg.mozilla.org/releases/l10n/mozilla-beta/ja/rev/a2cc2e1da532
https://hg.mozilla.org/releases/l10n/mozilla-beta/ja-JP-mac/rev/3bdbfccd785a

**Comment by marsf** [comment]
**category**, **editor**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/2e6d15722b12
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/13814247c9f6

https://hg.mozilla.org/releases/l10n/mozilla-beta/ja/rev/289cc8d9b658
https://hg.mozilla.org/releases/l10n/mozilla-beta/ja-JP-mac/rev/1dc42d8f8c6b

**Comment by marsf** [comment]
とりあえず、52.0 での対応はここまで。

**Comment by marsf** [comment]
**responder**:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/39de95d511a2
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/be2c7ffe4339

**Comment by marsf** [comment]
@chikoski さんが unassigned されちゃってる？ 操作ミスでクリックしてしまったかもしれません。 
何か見つけたらコミットしてくださいね。

**Comment by marsf** [comment]
provider を追加。

**Comment by marsf** [comment]
issue #80 より、firewall を追加。

**Comment by marsf** [comment]
**provider**, **firewall**:
https://hg.mozilla.org/l10n-central/ja/rev/19ac7f7578ed69f4d03fbd3ef45abe135651951c
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/65a1d4e66f4c60b0945f8d627fd040899ae0b25f

**Comment by marsf** [comment]
[L10n ガイドラインを更新](https://github.com/mozilla-japan/translation/wiki/L10N-Guideline#%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A%E8%AA%9E%E3%81%A8%E9%95%B7%E9%9F%B3)したので反映させる。
- -xy にも長音を付ける
  - [ ] proxy

**Comment by marsf** [comment]
作業漏れ。主に aboutRights.dtd/.ftl 関係。
- [バイナリ](https://transvision.mozfr.org/?recherche=%E3%83%90%E3%82%A4%E3%83%8A%E3%83%AA&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings) → バイナリー
  - [ ] binary
- [ライセンサ](https://transvision.mozfr.org/?recherche=%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B5&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings) → ライセンサー
  - [ ] licensors
- [ディストリビュータ](https://transvision.mozfr.org/?recherche=%E3%83%87%E3%82%A3%E3%82%B9%E3%83%88%E3%83%AA%E3%83%93%E3%83%A5%E3%83%BC%E3%82%BF&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings) → ディストリビューター
  - [ ] distributors

**Comment by marsf** [comment]
**proxy:**
https://hg.mozilla.org/l10n-central/ja/rev/759875223a6c
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/6e29e5775b04

**binary, licensors, distributors:**
https://hg.mozilla.org/l10n-central/ja/rev/7f949d814caa
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/6e80f534f12d

**Comment by marsf** [comment]
一通り更新が終わったので閉じます。
適用漏れがあれば再度オープンにしてください。
