### ISSUE TITLE
Thunderbird/SeaMonkey の既定のテキストエンコーディングを UTF-8 に変更する

### ISSUE THREAD

**Issue by marsf** [mozilla-japan/gecko-l10n#63]
Thunderbird 52.0 で変更する予定です。

Thunderbird 29.0 で、en-US の送信メールの既定のテキストエンコーディングが UTF-8 に変更されています。 
 [Bug 941545](https://bugzilla.mozilla.org/show_bug.cgi?id=941545)
 [Please consider if your locale could default to UTF-8 for outgoing email - Google グループ](https://groups.google.com/forum/?hl=ja&fromgroups#!topic/mozilla.dev.l10n/PH7tF9m8vUY)

日本語のメール環境については、もはやサーバー側で問題になることはありません。
今まではメールクライアント、特に携帯端末での対応状況に懸念があって Thunderbird の日本語版では ISO-2022-JP を既定のテキストエンコーディングとして維持していました。

[UTF-8 は本当に安全か？ | もじふぉ](http://forums.firehacks.org/l10n/viewtopic.php?t=1363) (※10年前の投稿)

現在では Unicode への対応状況 (絵文字も含む) も改善され、問題になることはほとんど無いと思われます。

ユーザー側の設定は、オプション > 表示 > 書式タブ > フォントと配色の詳細設定ボタン から変更できます。
または、設定エディタから **mailnews.send_default_charset** と **mailnews.view_default_charset** を直接変更することもできます。

何か問題があればコメントください。

**Comment by masayuki-nakano** [comment]
すでにメジャーなWebメールサービスはUTF-8を利用してると聞きます(Gmailはアカウントあるので確認しましたがUTF-8でした)ので、移行しても問題無いかと思います。

あと、返信の際は相手のエンコーディングと同じものがデフォルトになりますので、影響は自分から開始するスレッドの送信時のみに限定されますので影響は人によっては限定的になります。

**Comment by marsf** [comment]
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/11867217bdd2
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/59cb64a80cd1

**Comment by dynamis** [comment]
この変更は日本語版のリリースノートに追記したいですね。
mozilla.jp website の issues (private) に立てておきます:
https://github.com/mozilla-japan/mozilla.jp/issues/1424

**Comment by marsf** [comment]
周知のため、MozillaZine.jp フォーラムにもトピックを立てています。
[Thunderbird 52.0 で既定のテキストエンコーディングを UTF-8 へ変更](http://forums.mozillazine.jp/viewtopic.php?f=25&t=16490)

もしリリースノートに書ければ、以下も考慮していただけるとありがたいです。 > @dynamis, @kyoshino

偶然的通行人さんのコメント:
> UTF-8 で日本語メールを送受信することに、本質的な障害は何もありません。ここが大前提です。
> しかし、相手の事情等によって、今後も日本語メールを ISO-2022-JP で送信（返信、転送）することが必要なユーザーは、Thunderbird 52.0 に更新後、既定のテキストエンコーディングの設定に注意を払ってください ―― ということになりましょうか。

**Comment by dynamis** [comment]
変更されること自体はリリースノート (今回は @kyoshino さんが用意してくれます) に記載予定ですが、詳しいこととか戻す手順とかはリンクするとか、リリース紹介記事に書くのが精一杯かと思います。

これに関するサポート記事とかが SUMO にあるとそれにリンクできるし (リリースノートよりも) みんなが参照しに来るサポートサイト側で検索して調べられるようになって良いと思うのですが、その辺記事って書く予定があったりしないでしょうか。 MozillaZine のトピックとかの方にリンクした方が良かったりしますかね？

**Comment by kyoshino** [comment]
52 Beta のリリースノートは用意したので (まだサイトに未反映ですが) そこにも記載できますが、確かに SUMO の記事があった方が嬉しいかもですね。ざっと調べたところ [文字エンコーディングに関する設定項目](https://support.mozilla.org/ja/kb/configuration-options-character-encoding) が該当するので、ここに書き足す感じでしょうか。

**Comment by marsf** [comment]
SUMO の「文字エンコーディングに関する設定項目」の記事は、設定へのナビゲーションだけですから、ここに設定の注意書きを書くのは違う気がします。
（加えて、いまは SUMO に記事を書ける状況じゃないです。）

日本語版固有の内容なので、どこかに記事があったほうがいいですね。
とりあえずは、MozillaZine.jp の偶然的通行人さんのトピックがいいと思います。
[【レポート】Thunderbird 52.0b1 を使ってみて気づいた新機能など](http://forums.mozillazine.jp/viewtopic.php?f=3&t=16489)

**Comment by kyoshino** [comment]
リリースノートには以下のような項目を追加しようと思いますが、どうでしょうか。

> **重要:** 日本語版で、既定の文字エンコーディングを ISO-2022-JP から Unicode (UTF-8) へ変更しました。現在では各種メールクライアントにおいて Unicode 対応が改善されており、問題が生じる可能性は少ないと思われますが、何らかの理由で設定を戻す必要がある場合は、オプション画面の [表示] > [書式] > [フォントと配色] > [詳細設定] を開き、エンコーディングを変更してください。

**Comment by dynamis** [comment]
ひとまずそれで良いかと思います。書き換えたりリンクしたりも必要なら更新できますし。

**Comment by dynamis** [comment]
改行周りの挙動の違いで単にエンコーディングの違いだけじゃない影響？があった点について、取りあえずここにメモしておきます:

Thunderbird は ISO-2022-JP などのときだけ編集画面で表示されている通り改行の入ったメールを送信しているが、UTF-8 だとそういうことはしないように思います。そのため「Thunerbird 52 にしてから編集画面では改行されて表示されているのに送信したら改行されてない！」的な反応があります。

それを回避するためには Thunderbird では現状
* 文字エンコーディングを ISO-2022-JP にする
* mailnews.send_plaintext_flowed=false とする
の両方をすれば編集画面の通り自動的に改行が挿入されて送信される(＆改行の自動除去 format=flowed を行わない) と思います。

UTF-8 のままで送る場合は取りあえず「編集 -> 再改行」にて改行してから送ることもできますが、デフォルトの挙動として改行を入れさせる方法は存在するのかどうか調べた限りでは見つけられませんでした。何かあるならそれも含めて SUMOMO に FAQ として日本語独自のページを追加したいところです。
