### ISSUE TITLE
メールクライアントに統合されたカレンダーとスケジュール長

### ISSUE THREAD

**Issue by Cai0407** [mozilla-japan/gecko-l10n#64]
https://github.com/mozilla-japan/gecko-l10n/commit/88fa913e223a17ec63c2f2cb2216a7cd38ea17ee

`-extensions.{e2fda1a4-762b-4020-b5ad-a41df1933103}.description=Thunderbird に統合されたカレンダー
+extensions.{e2fda1a4-762b-4020-b5ad-a41df1933103}.description=メールクライアントに統合されたカレンダーとスケジュール長`

「スケジュール長」ではなく「スケジュール帳」かと

**Comment by marsf** [comment]
ご指摘ありがとうございます。
修正しました。 m(_ _)m

**Comment by marsf** [comment]
Fixed on aurora (52.0):
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/7d9930c6688f
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/996c04f98556
