### ISSUE TITLE
enableOCSP.label

### ISSUE THREAD

**Issue by Cai0407** [mozilla-japan/gecko-l10n#65]
Firefox: browser/chrome/browser/preferences/advanced.dtd
`<!ENTITY enableOCSP.label "OCSP レスポンダに問い合わせてデジタル証明書の有効性をリアルタイムに確認する">`

Thunderbird: mail/chrome/messenger/preferences/advanced.dtd
`<!ENTITY enableOCSP.label "OCSP レスポンダサーバーに問い合わせて証明書の現在の正当性を確認する">`

1. どちらも原文は "Query OCSP responder servers to confirm the current validity of certificates" と同じですので、統一した方が良いと思います。
2. respond**er** なので、新しいルールに従えば「レスポンダ」ではなく「レスポンダー」では？

SeaMonkey だと実際に使われてるリソースがどれなのかちょっとわからなかったのですが

suite/chrome/common/pref/pref-certs.dtd
`<!ENTITY enableOCSP.label "オンライン証明書状態プロトコル (OCSP) を使用すると、証明書の現在の正当性を検証できます。">`
原文: Use the Online Certificate Status Protocol (OCSP) to confirm the current validity of certificates

このあたり？

**Comment by marsf** [comment]
ご指摘ありがとうございます。
現状で訳語が使われているのは、Firefox と Thunderbird だけのようです。
https://transvision.mozfr.org/?recherche=responder&repo=aurora&sourcelocale=en-US&locale=ja&search_type=strings

Issue #55 で対応するため、こちらは close とします。

**Comment by marsf** [comment]
すみません、Issue #55 は、ご指摘の 2 の対応だけですね。

**Comment by marsf** [comment]
SeaMonkey が以前の文字列、Firefox 33.0 で原文が変わったけれども訳文はほぼそのままだったようです。
機能的に同じなので訳文に問題はありませんが、統一するとなると Thunderbird に合わせるのが良さそうです。

https://hg.mozilla.org/releases/mozilla-aurora/rev/d29d68087657#l5.1
https://github.com/mozilla-japan/gecko-l10n/commit/4a94850184e2aff79416d5d5a5669bb59d0e752a#diff-db8e5fbd2d98c2c80f445e10028a8fb7

**Comment by marsf** [comment]
53.0:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja/rev/39de95d511a2
https://hg.mozilla.org/releases/l10n/mozilla-aurora/ja-JP-mac/rev/be2c7ffe4339
