### ISSUE TITLE
Yahoo! JAPANの検索でHTTPSを使う

### ISSUE THREAD

**Issue by vyv03354** [mozilla-japan/gecko-l10n#66]
l10nのレポジトリーはもはやFirefoxの検索プラグインを含んでいませんが、ThunderbirdやSeaMonkeyのものがまだ含まれているのでいちおうここでも報告しておきます。
Mozillaの関連バグ: https://bugzilla.mozilla.org/show_bug.cgi?id=1193636

**Comment by dynamis** [comment]
RESOLVED FIXED in Firefox 55

**Comment by makotokato** [comment]
@dynamis  Why do you close this?

This bug is for Thunderbird and Seamonkey.  Firefox is fixed by me, but I don't land it

suite/searchplugins/yahoo-jp.xml

**Comment by dynamis** [comment]
すみません、リポジトリ整理中にうっかりやってしまいました。
Sorry, just mistake during github repo/org transfer and cleanup.

**Comment by marsf** [comment]
Thunderbird の検索プラグインは [bug 1468686](https://bugzilla.mozilla.org/show_bug.cgi?id=1468686) で comm-central に移行済み。その際 https に変更されてた。
https://hg.mozilla.org/comm-central/file/tip/mail/components/search/searchplugins/yahoo-jp.xml

gecko-l10n の Thunderbird の検索プラグインのほうは削除。https://github.com/mozilla-japan/gecko-l10n/commit/f3a71dbe8a8f92b783506a2d67e8bfb81e1d9280

**Comment by marsf** [comment]
SeaMonkey の検索プラグインは [bug 1300198](https://bugzilla.mozilla.org/show_bug.cgi?id=1300198) で comm-central に移行、https に変更済み。
リリースされれば、SeaMonkey 2.75 で反映される？

Issue #72 も含まれている。

**Comment by marsf** [comment]
[bug 1642876](https://bugzilla.mozilla.org/show_bug.cgi?id=1642876) で各ロケールのフォルダから検索エンジンが削除されました。

Thunderbird の検索エンジン：
https://hg.mozilla.org/comm-central/file/tip/mail/components/search/extensions

SeaMonkey の検索エンジン：
https://hg.mozilla.org/comm-central/file/tip/suite/locales/searchplugins

**Comment by marsf** [comment]
close します。
