### ISSUE TITLE
「漏えい」などの交ぜ書き表記は好ましくない

### ISSUE THREAD

**Issue by kaizukadoryu** [mozilla-japan/gecko-l10n#67]
TLSで保護されていないウェブサイトにあるパスワード入力欄(フォーム)に入力しようとすると「この接続は安全ではありません。ここに入力したログイン情報は漏えいする可能性があります。」と警告が表示されますが、"漏えい"という表記はあまり好ましくないと思います。
"漏洩"に変更するか、他の言葉に言い換えるなどした方がいいと思いますが、この辺りは翻訳ガイドライン的にどうなのでしょうか。

**Comment by marsf** [comment]
ご意見ありがとうございます。

「漏えい」の表記については、共同通信社の記者ハンドブックに従っています。
また翻訳についても、原文の "This connection is not secure. Logins entered here could be compromised." を過不足なく、そのまま翻訳したものです。

表記が好ましくないというのは、どのようなことを懸念されているのでしょうか？

**Comment by kaizukadoryu** [comment]
返答ありがとうございます。
好ましくないというのは見ていて違和感を感じるというだけで、そこまで深い意味はありません。
ソフトウェアの翻訳の表記に通信社(や新聞社)の表記を参考にするなら賛成ですが、厳密に従うとなると少々やりすぎな気がします。

**Comment by marsf** [comment]
Mozilla の日本語ローカライズでは、一つの参考基準として記者ハンドブックに倣っています。

交ぜ書きに違和感があるということでしたら、ここだけでなく全体的な見直しが必要になります。具体的に、好みの問題ではない利点を挙げていただければ、変更した場合に他のユーザーの同意も得られるのではないかと思います。

国のほうでは一つの意見として、こういう考え方をしているようです。記者ハンドブックは、国の国語政策を反映して改訂されています。
[文化庁 | 国語施策・日本語教育 | 国語施策情報 | 第20期国語審議会 | 新しい時代に応じた国語施策について（審議経過報告） | Ⅱ 情報化への対応に関すること](http://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kakuki/20/tosin04/03.html)

#いろいろな意味で時代遅れの慣習を引きずっているとも言えます。

**Comment by kaizukadoryu** [comment]
近年、テレビ番組のテロップやリンク先にもあるように新聞の寄稿などを中心に交ぜ書きを避ける傾向があると感じます。
また新聞社・出版社の基準というのは厳密すぎて世間一般(主に通信社の文書や新聞以外の出版物)の感覚から少々ずれていると感じます。
私の知る限りでは各OSでも交ぜ書きを行っていませんし、その中でFirefoxが交ぜ書きを行うとなると統一感という観点からも良くないと思います。
基準を設けてそれに従うのも大事ですが、時には自然な文に近付ける為に例外的に従わないのはどうでしょうか。
# README.mdの記者ハンドブックのリンクが切れています

**Comment by marsf** [comment]
ひとまず issue のタイトルを変更しました。
記者ハンドブックのリンクも修正しました。ご指摘ありがとうございます。


交ぜ書き表記が OS や他のソフトウェアでどの程度使われているのか、使われていないのか、調べたことは全くありません。

[JTF スタイルガイド 2.3 版](https://www.jtf.jp/jp/style_guide/styleguide_top.html) では、2.1.2 漢字に「『常用漢字表』にない漢字であっても実務翻訳で慣用的に用いられる語には漢字を使います。」「ひらがなと混ぜ書きすると不自然（だ捕）（改ざん）（だ円）」とあるだけです。

Microsoft の日本語スタイルガイドでは、かなと漢字の使い分けについてのガイドラインは『用字用語 新表記辞典』（第一法規）を用いるとあります。

どの用語辞典も、使ってよいとされる漢字が増えたり、コンピューターのかな漢字変換で容易に使われるようになったおかげで、交ぜ書きの用語が減っているようです。


個人的には、交ぜ書き表記の（単語ごとではない）統一的なルールを決めてしまうのが良いと思います。
例えば、「～する」は交ぜ書きにしないとか。自然な文にも規則性があるはずです。

**Comment by kaizukadoryu** [comment]
そうですね。私も単語ごとに決めずにルールを設けるのが良いと思います。
草案として下記のルールを提案します。
1. 現在のルールで交ぜ書きする単語は言い換えを検討する。
2. 1で適切な言い換えが無い場合は交ぜ書きをせずに表記する。
「漏えい」の場合は『流出』『漏れ出す』などと言い換えることが出来ますが、前者の場合は原文とニュアンスがずれている気がしますし、後者は前後の文を考慮すると少々違和感があるので『漏洩』が適切でしょうか。

#Gecko内で「漏えい」以外で交ぜ書きされている単語はあるのでしょうか？

**Comment by marsf** [comment]
だいぶ間が空いてしまいました。交ぜ書きについて調べた事を書きます。

まず、世間的に交ぜ書き表記は「好ましくない」ようです。 (^^;　ただし、交ぜ書きの手段そのものが否定されているわけではありません。

交ぜ書き表記を解消する方法として、

1. 交ぜ書きしないで漢字表記にする
単語を構成する漢字そのものに意味があるもの、読みを聞いても意味が伝わらないものは、特に交ぜ書きしないほうがよい。

2. 漢字表記でルビを振る (※UI には不可)
上記に加えて、あまり使われない漢字を含む単語などにはルビを振るのが有効。

3. 別の単語に言い換える
上記1の場合でも一般的でない難しい単語、画数が多くてつぶれてしまう漢字を含む単語は、同じ意味を持つ易しい単語に言い換えたほうがよい。ただし、言い換えたことで本来の意味まで変えられてしまった例もあるので注意が必要。

「そもそも、言い換えが行われずに交ぜ書きしてまでも使われ続けているということに意味があるのだから、漢字表記を大切にすべき」という考えを書かれている方もいました。

**Comment by marsf** [comment]
> #Gecko内で「漏えい」以外で交ぜ書きされている単語はあるのでしょうか？

見つけられたものは、「漏えい」と「改ざん」だけです。
https://transvision.mozfr.org/?recherche=%E6%94%B9%E3%81%96%E3%82%93&repo=central&sourcelocale=en-US&locale=ja&search_type=strings

**Comment by marsf** [comment]
とりあえず、「漏えい」と「改ざん」に絞って解決します。他に交ぜ書きされている単語があれば教えてください。
方法としては、上記の解消方法を前提としたローカライズで、@kaizukadoryu さんの案の 2. と 1. を逆転したものでよいかと思います。つまり、

交ぜ書き表記の単語は次のようにする。
1. 漢字表記が適切である場合は漢字表記にする。（適切とは、表記された漢字が原文の英単語の意味を持ち、一般的に使われていること。）
2. 上記1.に該当しない場合は言い換えを検討し、文脈により適切な訳語を使う。

**Comment by marsf** [comment]
「漏えい」は、"**expose**" または "**be compromised**" の訳語として使われています。
「漏」と「洩」は共に「もれる」という意味があり、これらの英単語の意味とも一致するので、
そのまま漢字表記の「**漏洩**」とします。

「改ざん」の漢字表記は「改竄」で、「竄」には「もぐる、穴の中に押し込める」という意味があり、改竄は「他人の文章をこっそり自分の文章の中にもぐりこませる」という意味になるそうです。
しかし、これが使われている英語の原文がそれぞれ違うので少々面倒です。

 - Other people can view your information or **modify** the website’s behavior. 
第三者にあなたの情報を盗み見られたりウェブサイトの動作を改ざんされる可能性があります。 
[browser/chrome/browser.dtd#identity.description.weakCipher2](https://hg.mozilla.org/l10n-central/ja/file/default/browser/chrome/browser/browser.dtd)
 - The script element has a **malformed** hash in its integrity attribute: The correct format is ...
script 要素の integrity 属性に改ざんされたハッシュが含まれています: 正しい書式は ...
[dom/chrome/security.properties#MalformedIntegrityHash](https://hg.mozilla.org/l10n-central/ja/file/default/dom/chrome/security/security.properties)
 - ... this error could mean that someone is **tampering** with your connection.
... 誰かが通信を改ざんしているからこのエラーが表示されている可能性があるので十分に注意してください。
[mobile/android/chrome/aboutCertError.dtd#certerror.expert.content](https://hg.mozilla.org/l10n-central/ja/file/default/mobile/android/chrome/aboutCertError.dtd)

"modify" は文脈から、"tampering" はその意味から、「**不正に改変**」とします。
"malformed hash" については、書式が間違っているという文脈で第三者による改変とは限らないので、「**異常なハッシュ値**」でどうでしょうか。(元が誤訳っぽい)

**Comment by marsf** [comment]
57.0:
https://hg.mozilla.org/l10n-central/ja/rev/e8c9c104491f
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/0ecd650d99e9

他に交ぜ書き表記を見つけた方は re-open してコメントください。
