### ISSUE TITLE
「プロファイル」を「プロフィール」に統一？

### ISSUE THREAD

**Issue by kyoshino** [mozilla-japan/gecko-l10n#68]
これまで Firefox/Thunderbird の [(user) profile](https://transvision.mozfr.org/?recherche=profile&repo=central&sourcelocale=en-US&locale=ja&search_type=strings) については伝統的に「プロファイル」という訳語が当てられてきましたが、場面によって「プロフィール」と訳し分けるのは面倒なので、一般的な「プロフィール」に統一することを提案します。

**Comment by marsf** [comment]
訳し分けるのが面倒な場面てどこですか？ 製品のプロファイルと関係のある所ですか？

**Comment by kyoshino** [comment]
Pontoon のどこかのプロジェクトでサイト上の「プロフィール」と製品の「プロファイル」と混ざってたところがあった気がします。あと関係ないところでも「プロファイル」と訳されてしまっているところもありますね。

**Comment by kyoshino** [comment]
製品の「プロファイル」をそのままにするなら関係ないところも全部「プロファイル」に統一したほうがいいかなと。いずれにしても不統一なのは面倒です。

**Comment by marsf** [comment]
製品のプロファイルと開発ツールのプロファイラー以外を「プロフィール」に統一するのではだめですか？

ここは製品 l10n の issue なので、製品ローカライズ側の意見としては、他のプロジェクトと訳し分けるのが面倒だから変えるのでは説得力が弱いです。難しいとか判断に迷うとかならまだわかりますが、ただ面倒なだけなら、変えた場合の影響も考えてくださいってことになります。

[Mozilla 翻訳グループ](https://groups.google.com/forum/#!forum/mozilla-translations-ja)のほうできいてみてはいかがでしょうか。

**Comment by kyoshino** [comment]
判断に迷うのは確かです。実際にそういう場面がありました。Chrome も「プロフィール」にしているようだし、ここは製品側を合わせるべきだと思います。その場合に SUMO などの書き換えが必要になることは承知しています。

**Comment by hmatrjp** [comment]
9/10 のハンズオンで持ち出すネタとして、良さそうなので整理させてください。
（整理がつかないようなら、当日の説明では、「同じ英単語でも違った訳語が当てられていることがあります」の方のサンプルとして使います）

1.
Firefox と Thunderbirdこの二つのユーザー用 profile の表記は今の最新版でも「プロファイル」ですね？ （ESR版を使っているもので、最新の日本語版Firefox がどうなっているか見たことがないので。）

2.
pontoon に翻訳が格納されている、たとえば addon.mozilla.org で管理されている開発者Profile については、プロフィール の方が通りが良い、ということでしょうか。

3.開発ツールの Profiler については、「プロファイラー」と表記するのが一般的だという認識でいます。

**Comment by dynamis** [comment]
* Firefox/Thunderbird の訳語選択は一般の技術用語であれば広く使われている物、OS 依存で訳し分けがあるような物は OS の流儀に合わせることを原則としてきました
* Windows 用語的には一般に (フランス語読みのプロフィールではなく) 英語読みの方のプロファイルの方が採用されていると思います (Win Vista ~ Win 10 確認した限り)
* ウェブサイトの記載は製品側に合わせることを原則としてきました

なので、ウェブ側をプロファイルの方に統一するのが原則ではないかと思います。

プロフィールという訳語を採用しているのが Chrome だけなら OS (Windows) に合わせる方が優先度は高い用に思います。Chrome と一緒に使うのではなく Windows と一緒に使うものですので。

なお、プログラムのユーザデータのことではなく SNS のアカウント情報的な物は英単語としては同じであっても別の物として考えられると思います。なので、別の物を指しているので別の訳語を当てるというのは全然ありだと思います。同じ英単語でも訳し分けが発生するのは profile に限った物ではありません ([用語集](https://github.com/mozilla-japan/translation/wiki/Mozilla-L10N-Glossary)で文脈に応じて訳すため複数 OK 扱いの物がいっぱいあるように)。

**Comment by dynamis** [comment]
1. Firefox と Thunderbirdこの二つのユーザー用 profile の表記は今の最新版でも「プロファイル」ですね？
   * YES
2. pontoon に翻訳が格納されている、たとえば addon.mozilla.org で管理されている開発者Profile については、プロフィール の方が通りが良い、ということでしょうか。
   * 吉野さんの提案は製品のプロファイルの方を Chrome 同様にプロフィールに統一したらいいじゃんって提案かと思います。
3. 開発ツールの Profiler については、「プロファイラー」と表記するのが一般的だという認識でいます。
   * はい。それで良いかと思います。そういう意味でも技術系は英語から来ているので英語読みのプロファイルが多いんだと思います。

**Comment by hmatrjp** [comment]
なるほど。解説ありがとうございました。 @dynamis

**Comment by kyoshino** [comment]
返信が遅くなって済みません。これに関しては製品で採用されている「プロファイル」でサイトも統一しましょう。Pontoon で直せるところは後で直しておきます。
