### ISSUE TITLE
Whole Words→完全一致 は誤訳では?

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/gecko-l10n#71]
l10n forum で Ikadzuchi さんからフィードバックがありました:

http://forums.firehacks.org/l10n/viewtopic.php?t=19614

> Ctrl+Fのページ内検索で「完全一致(W)」というボタンがありますが、完全一致という字面からは(曖昧検索でなく)入力文字列に完全に一致する文字列を含むものを検索するのかと勘違いしてしまいます。
> 原語のWhole Wordsを見れば単語全体にマッチするものだけを検索する用途と分かります。
> なぜこのような訳になったのか分かりませんが、「単語全体」や「単語単位」などと訳すのがいいのではないかと思います。

指摘されているとおり、単語単位での検索をするモードに切り替えるボタンで、完全一致という表現は誤訳もしくは一般的ではないためわかりにくいかと思います。

**Comment by marsf** [comment]
すみません、誤訳です。
該当箇所は 3 箇所あります。
https://transvision.mozfr.org/?recherche=%E5%AE%8C%E5%85%A8%E4%B8%80%E8%87%B4&repo=central&sourcelocale=en-US&locale=ja&search_type=strings

- Whole Words
完全一致
- Search whole words only
指定文字列に完全一致する単語だけを検索します
- (Whole words only)
(完全一致のみ)

**Comment by marsf** [comment]
それぞれ、以下のようにします。
"Search whole words only" の訳は、通常の「部分を検索します」に対して「単語を検索します」にしました。

- Whole Words
 完全一致 → 単語単位
- Search whole words only
指定文字列に完全一致する単語だけを検索します → 指定文字列に一致する単語を検索します
- (Whole words only)
(完全一致のみ) → (単語単位)

**Comment by marsf** [comment]
57.0:
https://hg.mozilla.org/l10n-central/ja/rev/fa9207bc6680
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/365c732be16b
