### ISSUE TITLE
English strings remain in privacy.dtd#L23?

### ISSUE THREAD

**Issue by dskmori** [mozilla-japan/gecko-l10n#75]
This line seems to contain the unexpected strings. Could you inspect it? Thanks.

https://github.com/mozilla-japan/gecko-l10n/blob/fd78a285d844e8bcd01cda0efd6e10c2320e1a76/ja/browser/chrome/browser/preferences/privacy.dtd#L23

**Comment by marsf** [comment]
ご報告ありがとうございます。すぐに修正します。

[Bug 1400815 - [ja] Unexpected English string remains in /browser/preferences/privacy.dtd](https://bugzilla.mozilla.org/show_bug.cgi?id=1400815)

**Comment by marsf** [comment]
56.0 rc で修正されました。
