### ISSUE TITLE
Firefox iOS version9.3 は、主要な機能の一部が、英語表記のままです。

### ISSUE THREAD

**Issue by Shitennouji** [mozilla-japan/gecko-l10n#78]
iPad にて、iOS 版 Firefox をアップデート（v9.3（7374））させたところ・・・
ブラウザ（iOS 版 Firefox）自体は、日本語版でしたが、
メニューボタン（三）からの「プルダウンメニュー（ドロップダウンメニュー）」のメニュー項目は、英語表記のままです。
MozillaZine.jp フォーラム「掲示板トップ » 相互ユーザサポート » Firefox for iOS」に、投稿が寄せられています。
（https://forums.mozillazine.jp/viewtopic.php?f=40&t=16847）

**Comment by marsf** [comment]
ご報告ありがとうございます。
申し訳ありませんが、すでにリリースされたバージョン (v9.x) およびローカライズが締め切られたベータ版 (v10) の修正・変更はできません。

今回は v9.3 とのことですが、今までリリースされた iOS 版 Firefox で未訳が残っているものは無いはずですが、私自身は実機を持っていないので確認できません。
こちらの v9 のスクリーンショットに該当部分はあるでしょうか？
https://wopr.norad.org/~sarentz/fxios/screenshots-170913/ja/screenshots.html

**Comment by Shitennouji** [comment]
返信をありがとうございます。
URL 先を確認しました。
しかし、このスクリーンショットは「iPhone」のものなので、当方が確認した「iPad」とは同一ではありません。

MozillaZine.jp フォーラム「掲示板トップ » 相互ユーザサポート » Firefox for iOS」への投稿者は、
ユーザーエージェントなどの使用環境の情報がなく、どのタイプについてかは不明です。

あくまでも当方が所有している「iPad」を下に、お知らせします。
＞ 提示いただいたスクリーンショット内から相当する「画像」を選択し、そのアップロード（Attachment Files）を試みましたが、Something went really wrong, and we c'ant process that file. とのエラーで出来ませんでした。
＞ そのため、文章表現でお伝えします。
スクリーンショットでの左側から24番目の
メニューボタン（三）からの「プルダウンメニュー（ドロップダウンメニュー）」のメニュー項目に相当します。

**Comment by marsf** [comment]
この（メニューがローカライズされていない）問題自体は、まだ存在するとすれば、おそらく v11 以降での修正になります。

持っている方には一目瞭然なのでしょうが、私は確認できません。
そのメニュー項目を書き出していただけますか？ Firefox が持っているローカライズ対象の文字列かどうか判別できると思います。

**Comment by marsf** [comment]
ちなみに、v10 のスクリーンショットはこちらです。
https://wopr.norad.org/~fxios/screenshots/fxios/v10/ja/gallery.html

**Comment by Shitennouji** [comment]
早々の返信をありがとうございます。
公務を控えているため、これにて就寝させていただきます。
明日（今日）から月曜日までは、不在になり、（スマホを個人所有をしておらず）個人所有の有線接続での PC を操作できる環境にはないため、火曜日の21時過ぎ頃に返信をさせていただきます。
では後日、よろしくお願いします。

**Comment by Shitennouji** [comment]
お待たせしました。
①実機（iPad）に於ける iOS 版 Firefox v9.3（7374）でのメニュー項目（英文）は下記の通りです。
※ メニュー項目は、左上を右へ、序で下段を同様に書き出しました。
Find in Page
Request Desktop Site
Set Homepage
New Tab
New Private Tab
Add Bookmark

②下記に、v9 のスクリーンショットに該当部分です。
※ 前回のアップロード（Attachment Files）エラー（Something went really wrong, and we c'ant process that file. ）は、（Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101）Firefox/57.0 にて、拡張機能「uMatrix」を使用しており、その「Requests」の対処が不十分だったためでした。申し訳ないです。
<img width="320" alt="iphone se-10menuonwebpage-01" src="https://user-images.githubusercontent.com/5517475/32495783-6d9df89e-c40a-11e7-9928-97af09b11fb8.png">

③ v10 のスクリーンショットでは
「該当」するタイプは皆無でした。

では

**Comment by marsf** [comment]
書き出しありがとうございます。
v9.3 ではローカライズしたものが製品に反映されていなかった、ということでしょうか。
v10 のリリース後に確認していただいて、問題が無ければ、この issue は閉じたいと思います。
よろしくお願いいたします。

**Comment by Shitennouji** [comment]
プライベートに於ける「PC ライフ」は極めて限定的で、平日の（火）～（木）での夜間に 2時間ほど（資産管理、調べ物、e-mail の目的で）起動させる程度です。
大概は、（Windows）PC をスタンドアローン（オフライン）での利用です。
最近は、MozillaZine.jp フォーラムは最優先で閲覧をするようにしていますが・・・。
そのため、それらに不向きな「iPad」は、滅多に起動させません。

つきましては、v10 のリリース時に「一報」をお願いしたいのですが。
仮に、その「新版」でも同様に、ローカライズが反映されていなかった場合には、どのような進展になるのでしょうか？
先述の MozillaZine.jp フォーラム「掲示板トップ » 相互ユーザサポート » Firefox for iOS」への返信を行いたいので、現状と今後についてを明確にできればとの思いです。

**Comment by makotokato** [comment]
Cc: @mantaroh

**Comment by Shitennouji** [comment]
みなさん、サポートをありがとうございます。
「ｖ10」での再確認の件、承知しました。
また「Firefox for iOS Train Schedule」の存在を確認しました。

当サポートにて判明した「事情」を
先述の MozillaZine.jp フォーラム「掲示板トップ » 相互ユーザサポート » Firefox for iOS」へ返信させていただきます。
では、V10.0 Release（Nov 10, 2017）後（11/14 火 21時頃）に改めて。

**Comment by Shitennouji** [comment]
大変、お待たせしました。
iOS に更新（v11.1.1）があり、その他アプリ（17 item）も連動して更新が掛かってしまったため、iOS 版 Firefox の更新が出来なくなりました。
先ほど、ようやく v10.1 に更新が完了しました。
メニューも含め、チェック可能な全てを点検してみましたが、問題は皆無でした。
以上、回答です。

**Comment by marsf** [comment]
ご確認ありがとうございました。
