### ISSUE TITLE
firewall の訳語統一

### ISSUE THREAD

**Issue by dskmori** [mozilla-japan/gecko-l10n#80]
このファイル内にいくつかある **ファイアーウォール** は、ルール上、長音なしの **ファイアウォール** が適当ではないでしょうか。
[gecko-l10n/ja/browser/chrome/overrides/netError.dtd](https://github.com/mozilla-japan/gecko-l10n/blob/master/ja/browser/chrome/overrides/netError.dtd)

cf. 
* [カタカナ語の表記](https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline#カタカナ語の表記) (Wiki)
    * [詳細ルール](https://docs.google.com/spreadsheets/d/1yIKTUY07tjAALpBecYW0ZQ0r4pbAppEO82OwivfY7iQ/edit) (Google Sheets)

**Comment by marsf** [comment]
ご指摘の通り、「ファイアウォール」は長音なしに統一しています。
browser, dom, mail 合わせて全部で 8 か所ありますね。
https://transvision.mozfr.org/?recherche=%E3%83%95%E3%82%A1%E3%82%A4%E3%82%A2%E3%83%BC&repo=gecko_strings&sourcelocale=en-US&locale=ja&search_type=strings

**Comment by marsf** [comment]
issue #55 で扱うのでこちらは閉じます。
