### ISSUE TITLE
Tracking Protectionの翻訳はどれがいいのか

### ISSUE THREAD

**Issue by makotokato** [mozilla-japan/gecko-l10n#81]
From https://twitter.com/marsf/status/932600050827399169
@marsf @kyoshino どうしましょうか？

**Comment by Rockridge07** [comment]
「プライバシー保護のためのトラッキング保護機能」というふうに並べてみたときに、「トラッキング防止」機能と呼ぶほうが、目的と手段の関係が明確になり、ユーザーの認知的混乱を招くリスクが低下するのではないか、と考えます。「トラッキング防止」と訳すに1票。

**Comment by marsf** [comment]
「トラッキング防止」にしました。
57.0 の次のリリースから反映されるはずです。

https://hg.mozilla.org/l10n-central/ja/rev/a50b6b6478a40b386aa241c250fdfc9d35e3501b
https://hg.mozilla.org/l10n-central/ja-JP-mac/rev/d91df2e05ca060ddb898202da8bd79a49f1a357c

**Comment by marsf** [comment]
Pontoon サイトで、Firefox for iOS, Focus for Android/iOS 他も直す必要があります。

**Comment by kyoshino** [comment]
Pontoon で更新できるところは更新しました。

**Comment by kyoshino** [comment]
mozilla.jp 上のリリースノートにも反映しました。そんなに数はありませんでしたが、これは私の訳じゃないですね。

**Comment by marsf** [comment]
@kyoshino ありがとうございます。Pontoon での更新を確認しました。

**Comment by marsf** [comment]
Mozilla 翻訳グループにも投稿しました。
https://groups.google.com/forum/#!topic/mozilla-translations-ja/rGlbJRzZyhg
