### ISSUE TITLE
"Run Adobe Flash"の訳語について

### ISSUE THREAD

**Issue by Rockridge07** [mozilla-japan/gecko-l10n#82]
Firefox 58でFlashのCTPのUIが修正され、表示されるメッセージも"Activate Adobe Flash."から"Run Adobe Flash"へと変更になりました（<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1415978">Bug 1415978</a>）。<a href="https://hg.mozilla.org/mozilla-central/rev/5d321835674f">mozilla-centralのコミット内容</a>を見ると、"because it's shorter and feels less technical in English."という説明があり、文末のピリオドを削除したことも併せて指摘されています。

従前、"Activate Adobe Flash."は「Adobe Flashを有効にします。」と翻訳されていたところですが、上記変更の内容や理由を踏まえ、"Run Adobe Flash"の訳語として「Adobe Flashを実行します」を提案します。

**Comment by Rockridge07** [comment]
Firefox 58.0b14にて修正を確認しました。弊案を採用していただき、ありがとうございました。

**Comment by marsf** [comment]
ご提案ありがとうございました。
https://github.com/mozilla-japan/gecko-l10n/commit/2c756cda15c6fc1aab0372c51a5971b93021a63e#diff-b0440c1a3ef5cba98d8dd1f00540189cL363
