### ISSUE TITLE
Thunderbirdの予定作成について

### ISSUE THREAD

**Issue by zhaobangjun99** [mozilla-japan/gecko-l10n#96]
Thunderbirdのメール内容から、変換で予定を作成してから、予定の詳細内容には、元々のメール内容の中の改行がすべてなくなる、一行になります。
この問題はどのよう改修できますか、教えていただけませんか？

**Comment by marsf** [comment]
@zhaobangjun99 さん
ここは製品のローカライズ（日本語化）のために利用する場所です。

バグと思われるのであれば、[Bugzilla](https://bugzilla.mozilla.org/) に報告してください。
使い方やトラブルシューティングなどについては [MozillaZine.jp フォーラム](https://forums.mozillazine.jp/viewforum.php?f=3)をご利用ください。
